import type { ChineseLessonId, ChineseSkill, HSKLevel } from './chineseHskRegistry';

export type HanziPinyin = Readonly<{ hanzi: string; pinyin: string }>;
export type ChineseChoice = Readonly<{ id: string; text: HanziPinyin; meaningVi: string }>;
export type ChineseQuestion = Readonly<{ id: string; prompt: HanziPinyin; choices: readonly ChineseChoice[]; correctChoiceId: string; analysis: string }>;

export interface HskVocabularyItem {
  id: `zh:hsk:hsk1:vocab:${string}`; level: HSKLevel; hanzi: string; pinyin: string; meaningVi: string; partOfSpeech: string;
  decomposition?: Readonly<{ character: string; radical: string; note: string }>;
  example: HanziPinyin & Readonly<{ translationVi: string; audioRefId?: string }>;
}

const vocab = (id: string, hanzi: string, pinyin: string, meaningVi: string, partOfSpeech: string, exampleHanzi: string, examplePinyin: string, translationVi: string): HskVocabularyItem => ({
  id: `zh:hsk:hsk1:vocab:${id}`, level: 'HSK1', hanzi, pinyin, meaningVi, partOfSpeech, example: { hanzi: exampleHanzi, pinyin: examplePinyin, translationVi },
});

export const HSK1_VOCABULARY: readonly HskVocabularyItem[] = [
  vocab('001','你','nǐ','bạn','đại từ','你好！','nǐ hǎo','Xin chào!'), vocab('002','好','hǎo','tốt; khỏe','tính từ','我很好。','wǒ hěn hǎo','Tôi rất khỏe.'),
  vocab('003','我','wǒ','tôi','đại từ','我是学生。','wǒ shì xuésheng','Tôi là học sinh.'), vocab('004','是','shì','là','động từ','她是老师。','tā shì lǎoshī','Cô ấy là giáo viên.'),
  vocab('005','不','bù','không','phó từ','我不是老师。','wǒ bú shì lǎoshī','Tôi không phải giáo viên.'), vocab('006','吗','ma','không?','trợ từ','你是学生吗？','nǐ shì xuésheng ma','Bạn là học sinh phải không?'),
  vocab('007','他','tā','anh ấy','đại từ','他是中国人。','tā shì zhōngguó rén','Anh ấy là người Trung Quốc.'), vocab('008','她','tā','cô ấy','đại từ','她是我的朋友。','tā shì wǒ de péngyou','Cô ấy là bạn của tôi.'),
  vocab('009','人','rén','người','danh từ','他是越南人。','tā shì yuènán rén','Anh ấy là người Việt Nam.'), vocab('010','学生','xuésheng','học sinh; sinh viên','danh từ','我是学生。','wǒ shì xuésheng','Tôi là học sinh.'),
  vocab('011','老师','lǎoshī','giáo viên','danh từ','老师很好。','lǎoshī hěn hǎo','Giáo viên rất tốt.'), vocab('012','朋友','péngyou','bạn bè','danh từ','他是我的朋友。','tā shì wǒ de péngyou','Anh ấy là bạn của tôi.'),
  vocab('013','中国','zhōngguó','Trung Quốc','danh từ riêng','我去中国。','wǒ qù zhōngguó','Tôi đi Trung Quốc.'), vocab('014','家','jiā','nhà; gia đình','danh từ','我回家。','wǒ huí jiā','Tôi về nhà.'),
  vocab('015','水','shuǐ','nước','danh từ','我喝水。','wǒ hē shuǐ','Tôi uống nước.'), vocab('016','茶','chá','trà','danh từ','她喝茶。','tā hē chá','Cô ấy uống trà.'),
  vocab('017','吃','chī','ăn','động từ','我吃米饭。','wǒ chī mǐfàn','Tôi ăn cơm.'), vocab('018','喝','hē','uống','động từ','你喝茶吗？','nǐ hē chá ma','Bạn uống trà không?'),
  vocab('019','去','qù','đi','động từ','他去学校。','tā qù xuéxiào','Anh ấy đi học.'), vocab('020','今天','jīntiān','hôm nay','danh từ thời gian','今天天气很好。','jīntiān tiānqì hěn hǎo','Hôm nay thời tiết rất đẹp.'),
  vocab('021','有','yǒu','có','động từ','我有一个朋友。','wǒ yǒu yí ge péngyou','Tôi có một người bạn.'), vocab('022','没有','méiyǒu','không có','động từ','我没有茶。','wǒ méiyǒu chá','Tôi không có trà.'),
  vocab('023','在','zài','ở; tại','giới từ/động từ','我在家。','wǒ zài jiā','Tôi ở nhà.'), vocab('024','学校','xuéxiào','trường học','danh từ','学校很大。','xuéxiào hěn dà','Trường học rất lớn.'),
  vocab('025','工作','gōngzuò','làm việc; công việc','động từ/danh từ','他在工作。','tā zài gōngzuò','Anh ấy đang làm việc.'), vocab('026','学习','xuéxí','học','động từ','我学习中文。','wǒ xuéxí zhōngwén','Tôi học tiếng Trung.'),
  vocab('027','看','kàn','xem; đọc','động từ','我看书。','wǒ kàn shū','Tôi đọc sách.'), vocab('028','听','tīng','nghe','động từ','她听音乐。','tā tīng yīnyuè','Cô ấy nghe nhạc.'),
  vocab('029','说','shuō','nói','động từ','他说中文。','tā shuō zhōngwén','Anh ấy nói tiếng Trung.'), vocab('030','书','shū','sách','danh từ','这是一本书。','zhè shì yì běn shū','Đây là một quyển sách.'),
  vocab('031','现在','xiànzài','bây giờ','danh từ thời gian','现在是八点。','xiànzài shì bā diǎn','Bây giờ là tám giờ.'), vocab('032','早上','zǎoshang','buổi sáng','danh từ thời gian','我早上喝茶。','wǒ zǎoshang hē chá','Tôi uống trà buổi sáng.'),
  vocab('033','晚上','wǎnshang','buổi tối','danh từ thời gian','晚上我回家。','wǎnshang wǒ huí jiā','Buổi tối tôi về nhà.'), vocab('034','点','diǎn','giờ; điểm','lượng từ','现在九点。','xiànzài jiǔ diǎn','Bây giờ là chín giờ.'),
  vocab('035','也','yě','cũng','phó từ','我也是学生。','wǒ yě shì xuésheng','Tôi cũng là học sinh.'), vocab('036','很','hěn','rất','phó từ','她很好。','tā hěn hǎo','Cô ấy rất khỏe.'),
  vocab('037','大','dà','to; lớn','tính từ','中国很大。','zhōngguó hěn dà','Trung Quốc rất rộng lớn.'), vocab('038','小','xiǎo','nhỏ','tính từ','这个学校小。','zhège xuéxiào xiǎo','Ngôi trường này nhỏ.'),
  vocab('039','喜欢','xǐhuan','thích','động từ','我喜欢看书。','wǒ xǐhuan kàn shū','Tôi thích đọc sách.'), vocab('040','朋友们','péngyoumen','các bạn','danh từ','朋友们在学校。','péngyoumen zài xuéxiào','Các bạn ở trường.'),
] as const;

export interface HskVocabularyDeck { id: Extract<ChineseLessonId, `zh:hsk:hsk1:vocabulary:${string}`>; title: string; cards: readonly HskVocabularyItem[]; }
export const HSK1_VOCABULARY_DECKS: readonly HskVocabularyDeck[] = [
  { id: 'zh:hsk:hsk1:vocabulary:foundations-01', title: 'Từ nền tảng', cards: HSK1_VOCABULARY.slice(0, 20) },
  { id: 'zh:hsk:hsk1:vocabulary:daily-life-02', title: 'Sinh hoạt hằng ngày', cards: HSK1_VOCABULARY.slice(20, 40) },
] as const;

export interface ChineseLessonContent { id: string; level: HSKLevel; skill: Exclude<ChineseSkill, 'vocabulary'>; title: string; explanation: readonly string[]; examples: readonly (HanziPinyin & { translationVi: string })[]; questions: readonly ChineseQuestion[]; passage?: HanziPinyin & { translationVi: string } }

export const HSK1_LESSONS: readonly ChineseLessonContent[] = [
  { id:'zh:hsk:hsk1:pronunciation:tones-01', level:'HSK1', skill:'pronunciation', title:'Bốn thanh điệu và thanh nhẹ', explanation:['Thanh 1 cao đều (mā), thanh 2 đi lên (má), thanh 3 hạ rồi lên (mǎ), thanh 4 đi xuống mạnh (mà). Thanh nhẹ viết không dấu (ma).','Bài học chỉ kiểm tra đáp án ký hiệu đã biên soạn; không thu âm và không tuyên bố chấm phát âm.'], examples:[{hanzi:'妈 / 麻 / 马 / 骂 / 吗',pinyin:'mā / má / mǎ / mà / ma',translationVi:'mẹ / cây gai / ngựa / mắng / trợ từ hỏi'}], questions:[{id:'tone-q1',prompt:{hanzi:'马',pinyin:'mǎ'},choices:[{id:'a',text:{hanzi:'第三声',pinyin:'dì sān shēng'},meaningVi:'thanh 3'},{id:'b',text:{hanzi:'第四声',pinyin:'dì sì shēng'},meaningVi:'thanh 4'},{id:'c',text:{hanzi:'轻声',pinyin:'qīngshēng'},meaningVi:'thanh nhẹ'}],correctChoiceId:'a',analysis:'Dấu ˇ trong mǎ biểu thị thanh 3: âm vực hạ rồi lên.'}] },
  { id:'zh:hsk:hsk1:grammar:shi-ma-01', level:'HSK1', skill:'grammar', title:'Câu với 是 và 吗', explanation:['A + 是 + B dùng để xác định A là B. Thêm 吗 ở cuối câu trần thuật để tạo câu hỏi có/không.','Phủ định 是 bằng 不是. Khi đứng trước âm tiết thanh 4, 不 thường đọc biến điệu là bú.'], examples:[{hanzi:'我是学生。',pinyin:'wǒ shì xuésheng',translationVi:'Tôi là học sinh.'},{hanzi:'你是老师吗？',pinyin:'nǐ shì lǎoshī ma',translationVi:'Bạn là giáo viên phải không?'}], questions:[{id:'grammar-q1',prompt:{hanzi:'你___学生吗？',pinyin:'nǐ ___ xuésheng ma'},choices:[{id:'a',text:{hanzi:'是',pinyin:'shì'},meaningVi:'là'},{id:'b',text:{hanzi:'喝',pinyin:'hē'},meaningVi:'uống'},{id:'c',text:{hanzi:'去',pinyin:'qù'},meaningVi:'đi'}],correctChoiceId:'a',analysis:'是 nối chủ ngữ 你 với danh từ 学生; 吗 ở cuối biến câu thành câu hỏi yes/no.'}] },
  { id:'zh:hsk:hsk1:reading:introduction-01', level:'HSK1', skill:'reading', title:'Làm quen với Lý Minh', explanation:['Đọc toàn đoạn để xác định người, quốc tịch, nghề nghiệp và đồ uống. Sau đó đối chiếu từng câu hỏi với thông tin trực tiếp trong bài.'], examples:[], passage:{hanzi:'你好！我是李明。我是中国人，也是学生。她是安娜，是我的朋友。她喝茶，我喝水。',pinyin:'nǐ hǎo! wǒ shì lǐ míng. wǒ shì zhōngguó rén, yě shì xuésheng. tā shì ānnà, shì wǒ de péngyou. tā hē chá, wǒ hē shuǐ.',translationVi:'Xin chào! Tôi là Lý Minh. Tôi là người Trung Quốc và cũng là học sinh. Cô ấy là Anna, bạn của tôi. Cô ấy uống trà, tôi uống nước.'}, questions:[{id:'reading-q1',prompt:{hanzi:'李明是哪国人？',pinyin:'lǐ míng shì nǎ guó rén'},choices:[{id:'a',text:{hanzi:'中国人',pinyin:'zhōngguó rén'},meaningVi:'người Trung Quốc'},{id:'b',text:{hanzi:'老师',pinyin:'lǎoshī'},meaningVi:'giáo viên'},{id:'c',text:{hanzi:'朋友',pinyin:'péngyou'},meaningVi:'bạn bè'}],correctChoiceId:'a',analysis:'Đoạn văn nói trực tiếp “我是中国人”, vì vậy Lý Minh là người Trung Quốc.'},{id:'reading-q2',prompt:{hanzi:'安娜喝什么？',pinyin:'ānnà hē shénme'},choices:[{id:'a',text:{hanzi:'水',pinyin:'shuǐ'},meaningVi:'nước'},{id:'b',text:{hanzi:'茶',pinyin:'chá'},meaningVi:'trà'},{id:'c',text:{hanzi:'米饭',pinyin:'mǐfàn'},meaningVi:'cơm'}],correctChoiceId:'b',analysis:'Câu “她喝茶” cho biết Anna uống trà; Lý Minh mới là người uống nước.'}] },
  { id:'zh:hsk:hsk1:pronunciation:tone-sandhi-02', level:'HSK1', skill:'pronunciation', title:'Biến điệu 不 và 一', explanation:['不 thường đổi thành bú khi đứng trước một âm tiết thanh 4, ví dụ bú shì (不是). 一 đổi thành yí trước thanh 4 và yì trước thanh 1, 2, 3.','Đây là bài nhận diện ký hiệu/phiên âm xác định; không thu âm hoặc chấm phát âm bằng AI.'], examples:[{hanzi:'不是 / 一个 / 一天',pinyin:'bú shì / yí ge / yì tiān',translationVi:'không phải / một cái / một ngày'}], questions:[{id:'sandhi-q1',prompt:{hanzi:'不是',pinyin:'bú shì'},choices:[{id:'a',text:{hanzi:'bú',pinyin:'bú'},meaningVi:'不 đổi thành thanh 2 trước shì thanh 4'},{id:'b',text:{hanzi:'bǔ',pinyin:'bǔ'},meaningVi:'不 đổi thành thanh 3'},{id:'c',text:{hanzi:'bù',pinyin:'bù'},meaningVi:'không đổi thanh'}],correctChoiceId:'a',analysis:'不 được đọc bú khi âm tiết ngay sau mang thanh 4; 是 là shì nên 不是 đọc bú shì.'}] },
  { id:'zh:hsk:hsk1:grammar:you-meiyou-02', level:'HSK1', skill:'grammar', title:'Có với 有, không có với 没有', explanation:['有 diễn tả “có” hoặc sự tồn tại: 我有一本书. Dùng 没有 để phủ định 有; không nói 不有 trong mẫu câu cơ bản này.','Câu hỏi yes/no có thể dùng 有…吗？; trả lời ngắn là 有 hoặc 没有.'], examples:[{hanzi:'我有一个朋友。',pinyin:'wǒ yǒu yí ge péngyou',translationVi:'Tôi có một người bạn.'},{hanzi:'你有书吗？没有。',pinyin:'nǐ yǒu shū ma? méiyǒu.',translationVi:'Bạn có sách không? Không có.'}], questions:[{id:'you-q1',prompt:{hanzi:'我___茶。',pinyin:'wǒ ___ chá'},choices:[{id:'a',text:{hanzi:'没有',pinyin:'méiyǒu'},meaningVi:'không có'},{id:'b',text:{hanzi:'不是',pinyin:'bú shì'},meaningVi:'không phải'},{id:'c',text:{hanzi:'不有',pinyin:'bù yǒu'},meaningVi:'cách phủ định không dùng'}],correctChoiceId:'a',analysis:'Phủ định 有 bằng 没有. Câu 我没有茶 nghĩa là “Tôi không có trà”.'},{id:'you-q2',prompt:{hanzi:'你有书___？',pinyin:'nǐ yǒu shū ___'},choices:[{id:'a',text:{hanzi:'吗',pinyin:'ma'},meaningVi:'trợ từ hỏi yes/no'},{id:'b',text:{hanzi:'很',pinyin:'hěn'},meaningVi:'rất'},{id:'c',text:{hanzi:'也',pinyin:'yě'},meaningVi:'cũng'}],correctChoiceId:'a',analysis:'Thêm 吗 ở cuối câu trần thuật để hỏi “Bạn có sách không?”.'}] },
  { id:'zh:hsk:hsk1:reading:daily-life-02', level:'HSK1', skill:'reading', title:'Một ngày của Minh', explanation:['Đọc các mốc thời gian trước, rồi ghép hoạt động tương ứng. Mỗi đáp án đều có bằng chứng trực tiếp trong đoạn.'], examples:[], passage:{hanzi:'李明早上八点在学校学习中文。晚上他回家，看书，也听音乐。他有一个朋友，他们都喜欢喝茶。',pinyin:'lǐ míng zǎoshang bā diǎn zài xuéxiào xuéxí zhōngwén. wǎnshang tā huí jiā, kàn shū, yě tīng yīnyuè. tā yǒu yí ge péngyou, tāmen dōu xǐhuan hē chá.',translationVi:'Lý Minh học tiếng Trung ở trường lúc tám giờ sáng. Buổi tối anh ấy về nhà, đọc sách và cũng nghe nhạc. Anh ấy có một người bạn; cả hai đều thích uống trà.'}, questions:[{id:'daily-reading-q1',prompt:{hanzi:'李明几点学习中文？',pinyin:'lǐ míng jǐ diǎn xuéxí zhōngwén'},choices:[{id:'a',text:{hanzi:'早上八点',pinyin:'zǎoshang bā diǎn'},meaningVi:'8 giờ sáng'},{id:'b',text:{hanzi:'晚上八点',pinyin:'wǎnshang bā diǎn'},meaningVi:'8 giờ tối'},{id:'c',text:{hanzi:'今天',pinyin:'jīntiān'},meaningVi:'hôm nay'}],correctChoiceId:'a',analysis:'Câu đầu nói rõ “早上八点…学习中文”, tức là học tiếng Trung lúc 8 giờ sáng.'},{id:'daily-reading-q2',prompt:{hanzi:'晚上李明做什么？',pinyin:'wǎnshang lǐ míng zuò shénme'},choices:[{id:'a',text:{hanzi:'看书和听音乐',pinyin:'kàn shū hé tīng yīnyuè'},meaningVi:'đọc sách và nghe nhạc'},{id:'b',text:{hanzi:'去学校',pinyin:'qù xuéxiào'},meaningVi:'đi tới trường'},{id:'c',text:{hanzi:'喝水',pinyin:'hē shuǐ'},meaningVi:'uống nước'}],correctChoiceId:'a',analysis:'Đoạn đọc viết “晚上他回家，看书，也听音乐”, nên hoạt động buổi tối là đọc sách và nghe nhạc.'}] },
] as const;

const hasMarkedTone = (pinyin: string) => /[āáǎàēéěèīíǐìōóǒòūúǔùǖǘǚǜ]/iu.test(pinyin);
const neutralSyllables = new Set(['de', 'ge', 'ma', 'sheng', 'you']);
const requiresTone = (pinyin: string) => pinyin.split(/[\s/.,!?;:]+/u).some((syllable) => /^[a-zü]+$/iu.test(syllable) && !neutralSyllables.has(syllable.toLowerCase()) && !hasMarkedTone(syllable));
export function validateChineseHskContent(vocabulary: readonly HskVocabularyItem[], lessons: readonly ChineseLessonContent[]): string[] {
  const issues: string[]=[]; const ids=new Set<string>();
  for(const item of vocabulary){ if(ids.has(item.id)) issues.push(`duplicate id: ${item.id}`); ids.add(item.id); if(item.level!=='HSK1') issues.push(`wrong-level content: ${item.id}`); if(requiresTone(item.pinyin)||requiresTone(item.example.pinyin)) issues.push(`pinyin missing tone: ${item.id}`); }
  for(const lesson of lessons){ if(ids.has(lesson.id)) issues.push(`duplicate id: ${lesson.id}`); ids.add(lesson.id); if(lesson.level!=='HSK1'||!lesson.id.startsWith('zh:hsk:hsk1:')) issues.push(`wrong-level content: ${lesson.id}`); if(lesson.questions.length===0) issues.push(`missing questions: ${lesson.id}`); for(const q of lesson.questions){ const choiceIds=q.choices.map(c=>c.id); if(!choiceIds.includes(q.correctChoiceId)) issues.push(`missing answer: ${lesson.id}:${q.id}`); const labels=q.choices.map(c=>`${c.text.hanzi}|${c.meaningVi}`); if(new Set(labels).size!==labels.length) issues.push(`duplicate distractor: ${lesson.id}:${q.id}`); if(!q.analysis.trim()) issues.push(`empty lesson analysis: ${lesson.id}:${q.id}`); if(requiresTone(q.prompt.pinyin)||q.choices.some(c=>requiresTone(c.text.pinyin))) issues.push(`pinyin missing tone: ${lesson.id}:${q.id}`); } }
  return issues;
}
