export type EnglishSurvivalUnit = 1 | 2 | 3 | 4 | 5 | 6;

export type RetrievalPattern = {
  /** Core phrase fragments the learner must reproduce. Case-insensitive, normalized. All must be present. */
  requiredFragments: string[];
  /** Literal names from the exemplar that should NOT appear (learner must use own name). */
  rejectedNames?: string[];
};

type RetrievalSeed = {
  promptVi: string;
  cueVi: string;
  patterns: RetrievalPattern[];
  hintVi: string;
};

export type EnglishSurvivalLesson = {
  id: `en-survival-${number}`;
  unit: EnglishSurvivalUnit;
  order: number;
  titleVi: string;
  titleEn: string;
  canDoVi: string;
  scenario: { settingVi: string; roles: [string, string] };
  dialogue: { speaker: 'A' | 'B'; text: string; vi: string }[];
  chunks: { text: string; vi: string; useWhenVi: string; vietnameseLearnerCueVi: string }[];
  contextCue: { titleVi: string; bodyVi: string };
  comprehension: { promptVi: string; options: string[]; correctAnswer: string; explanationVi: string };
  production: { promptVi: string; requiredSlots: string[]; exemplar: string; rejectExactModelCopy: true };
  retrieval: { promptVi: string; cueVi: string; acceptedPatterns: RetrievalPattern[]; answerHintVi: string };
  selfReview: string[];
  audioAsset?: { url: string; owner: string; license: string; accent: string; speed: 'slow' | 'normal'; transcript: string };
};

type ChunkSeed = [text: string, vi: string, useWhenVi: string, cue: string];
type LessonSeed = {
  unit: EnglishSurvivalUnit; titleVi: string; titleEn: string; canDoVi: string;
  settingVi: string; roles: [string, string]; lines: [[string, string], [string, string]];
  chunks: [ChunkSeed, ChunkSeed, ChunkSeed]; answer: string; distractor: string;
  slots: string[]; exemplar: string;
  retrieval: RetrievalSeed;
};

const seeds: LessonSeed[] = [
  { unit: 1, titleVi: 'Chào và giới thiệu', titleEn: 'Say hello and introduce yourself', canDoVi: 'Tôi có thể nói tên của mình khi gặp người mới.', settingVi: 'Bạn gặp một người mới ở lớp.', roles: ['Người học', 'Bạn cùng lớp'], lines: [['Hello, I’m Lan.', 'Chào, tôi là Lan.'], ['Nice to meet you, Lan.', 'Rất vui được gặp bạn, Lan.']], chunks: [['Hello, I’m ...', 'Chào, tôi là ...', 'khi tự giới thiệu', 'Nói tên bạn sau I’m.'], ['Nice to meet you.', 'Rất vui được gặp bạn.', 'khi mới gặp ai', 'Dùng sau lời chào.'], ['What’s your name?', 'Bạn tên là gì?', 'khi hỏi tên', 'Mở đầu bằng What’s.']], answer: 'Hello, I’m Lan.', distractor: 'The platform is two.', slots: ['tên của bạn', 'lý do gặp'], exemplar: 'Hello, I’m Mai. Nice to meet you.',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để tự giới thiệu.', cueVi: 'Hello, I\'m ...', patterns: [{ requiredFragments: ["hello", "i'm"], rejectedNames: ["lan", "mai"] }, { requiredFragments: ["hello", "i am"], rejectedNames: ["lan", "mai"] }, { requiredFragments: ["hello", "my name is"], rejectedNames: ["lan", "mai"] }], hintVi: 'Gợi ý: bắt đầu bằng "Hello, I\'m ..." hoặc "Hello, my name is ...".' },
  },
  { unit: 1, titleVi: 'Nhờ nói lại', titleEn: 'Ask someone to repeat', canDoVi: 'Tôi có thể lịch sự nhờ người khác nói lại.', settingVi: 'Bạn chưa nghe rõ nhân viên nói gì.', roles: ['Khách', 'Nhân viên'], lines: [['Sorry, could you say that again?', 'Xin lỗi, bạn có thể nói lại không?'], ['Of course. The bus leaves at nine.', 'Được chứ. Xe buýt rời đi lúc chín giờ.']], chunks: [['Sorry, could you say that again?', 'Xin lỗi, bạn có thể nói lại không?', 'khi chưa nghe rõ', 'Bắt đầu bằng Sorry.'], ['Please speak slowly.', 'Làm ơn nói chậm.', 'khi cần tốc độ chậm hơn', 'Dùng Please để lịch sự.'], ['I didn’t catch that.', 'Tôi chưa nghe kịp.', 'khi bỏ lỡ một phần', 'Nói I didn’t, không phải I don’t.']], answer: 'Sorry, could you say that again?', distractor: 'I am a ticket.', slots: ['điều bạn chưa nghe rõ'], exemplar: 'Sorry, could you say the time again?',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để nhờ người khác nói lại.', cueVi: 'Sorry, could you say that again?', patterns: [{ requiredFragments: ["sorry", "say", "again"] }, { requiredFragments: ["could you say", "again"] }, { requiredFragments: ["didn't catch"] }], hintVi: 'Gợi ý: bắt đầu bằng "Sorry, could you ⬦"' },
  },
  { unit: 1, titleVi: 'Hỏi đường', titleEn: 'Ask for directions', canDoVi: 'Tôi có thể hỏi đường đến một nơi gần đó.', settingVi: 'Bạn đang ở trên phố và cần tìm ga tàu.', roles: ['Khách', 'Người đi đường'], lines: [['Excuse me, where is the station?', 'Xin lỗi, ga ở đâu?'], ['It’s next to the bank.', 'Nó ở cạnh ngân hàng.']], chunks: [['Excuse me, where is ...?', 'Xin lỗi, ... ở đâu?', 'khi hỏi vị trí', 'Nêu nơi cần tìm sau is.'], ['Is it far from here?', 'Nó có xa đây không?', 'khi muốn biết khoảng cách', 'Dùng far cho xa.'], ['Thank you for your help.', 'Cảm ơn bạn đã giúp.', 'sau khi được chỉ đường', 'Kết thúc bằng lời cảm ơn.']], answer: 'Excuse me, where is the station?', distractor: 'I need a menu.', slots: ['địa điểm cần tìm'], exemplar: 'Excuse me, where is the museum?',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để hỏi đường.', cueVi: 'Excuse me, where is ⬦?', patterns: [{ requiredFragments: ["excuse me", "where is"] }, { requiredFragments: ["excuse me", "where's"] }], hintVi: 'Gợi ý: bắt đầu bằng "Excuse me, where is ⬦?"' },
  },
  { unit: 1, titleVi: 'Tìm nhà vệ sinh', titleEn: 'Find the restroom', canDoVi: 'Tôi có thể hỏi vị trí nhà vệ sinh.', settingVi: 'Bạn đang ở một quán cà phê.', roles: ['Khách', 'Nhân viên quán'], lines: [['Where is the restroom, please?', 'Nhà vệ sinh ở đâu, làm ơn?'], ['It’s at the back, on the left.', 'Ở phía sau, bên trái.']], chunks: [['Where is the restroom, please?', 'Nhà vệ sinh ở đâu, làm ơn?', 'khi cần tìm nhà vệ sinh', 'Thêm please để lịch sự.'], ['At the back.', 'Ở phía sau.', 'khi nghe chỉ vị trí', 'Back là phía sau.'], ['On the left.', 'Ở bên trái.', 'khi xác nhận hướng', 'Left là bên trái.']], answer: 'Where is the restroom, please?', distractor: 'I work tomorrow.', slots: ['địa điểm hiện tại'], exemplar: 'Where is the restroom, please? I am at the café.',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để hỏi nhà vệ sinh.', cueVi: 'Where is the restroom, please?', patterns: [{ requiredFragments: ["where", "restroom"] }, { requiredFragments: ["where", "bathroom"] }, { requiredFragments: ["where", "toilet"] }], hintVi: 'Gợi ý: "Where is the restroom, please?"' },
  },
  { unit: 1, titleVi: 'Hỏi giờ mở cửa', titleEn: 'Ask opening hours', canDoVi: 'Tôi có thể hỏi một nơi mở cửa lúc nào.', settingVi: 'Bạn muốn biết cửa hàng có mở vào Chủ nhật không.', roles: ['Khách', 'Nhân viên cửa hàng'], lines: [['What time do you open on Sunday?', 'Bạn mở cửa lúc mấy giờ vào Chủ nhật?'], ['We open at ten.', 'Chúng tôi mở lúc mười giờ.']], chunks: [['What time do you open?', 'Bạn mở cửa lúc mấy giờ?', 'khi hỏi giờ mở cửa', 'What time hỏi giờ.'], ['Are you open on Sunday?', 'Bạn có mở cửa Chủ nhật không?', 'khi hỏi ngày mở cửa', 'Open dùng cho cửa hàng hoạt động.'], ['Thank you, that helps.', 'Cảm ơn, điều đó giúp ích.', 'khi đã có thông tin', 'Dùng câu ngắn để kết thúc.']], answer: 'What time do you open?', distractor: 'My room is blue.', slots: ['ngày muốn hỏi', 'thời gian'], exemplar: 'What time do you open on Monday?',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để hỏi giờ mở cửa.', cueVi: 'What time do you open?', patterns: [{ requiredFragments: ["what time", "open"] }, { requiredFragments: ["when", "open"] }], hintVi: 'Gợi ý: "What time do you open?"' },
  },
  { unit: 2, titleVi: 'Gọi đồ uống', titleEn: 'Order a drink', canDoVi: 'Tôi có thể gọi một đồ uống đơn giản.', settingVi: 'Bạn gọi đồ ở quầy cà phê.', roles: ['Khách', 'Nhân viên'], lines: [['Can I have a tea, please?', 'Tôi có thể lấy một trà không, làm ơn?'], ['Sure. Hot or iced?', 'Được. Nóng hay đá?']], chunks: [['Can I have ...?', 'Tôi có thể lấy ... không?', 'khi gọi đồ', 'Nói món sau have.'], ['Hot or iced?', 'Nóng hay đá?', 'khi chọn đồ uống', 'Iced nghĩa là có đá.'], ['That’s all, thank you.', 'Thế là hết, cảm ơn.', 'khi gọi xong', 'Dùng để kết thúc gọi món.']], answer: 'Can I have a tea, please?', distractor: 'The train is late.', slots: ['đồ uống', 'nóng hoặc đá'], exemplar: 'Can I have an iced coffee, please?',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để gọi đồ uống.', cueVi: 'Can I have ⬦, please?', patterns: [{ requiredFragments: ["can i have"] }, { requiredFragments: ["could i have"] }, { requiredFragments: ["i'd like", "please"] }], hintVi: 'Gợi ý: "Can I have ⬦, please?"' },
  },
  { unit: 2, titleVi: 'Gọi món ăn', titleEn: 'Order a meal', canDoVi: 'Tôi có thể gọi món ăn từ thực đơn.', settingVi: 'Bạn gọi bữa trưa ở nhà hàng.', roles: ['Khách', 'Phục vụ'], lines: [['I’d like the chicken rice, please.', 'Tôi muốn cơm gà, làm ơn.'], ['Anything else?', 'Bạn cần gì thêm không?']], chunks: [['I’d like ...', 'Tôi muốn ...', 'khi gọi món lịch sự', 'I’d là I would.'], ['Anything else?', 'Còn gì khác không?', 'khi nghe phục vụ hỏi thêm', 'Else là thêm/khác.'], ['No, thank you.', 'Không, cảm ơn.', 'khi không cần thêm', 'Câu ngắn, lịch sự.']], answer: 'I’d like the chicken rice, please.', distractor: 'Where is my passport?', slots: ['món ăn', 'đồ uống nếu có'], exemplar: 'I’d like the noodle soup, please.',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để gọi món ăn.', cueVi: 'I\'d like ..., please.', patterns: [{ requiredFragments: ["i'd like"] }, { requiredFragments: ["i would like"] }, { requiredFragments: ["can i have"] }], hintVi: 'Gợi ý: "I\'d like ..., please."' },
  },
  { unit: 2, titleVi: 'Hỏi giá', titleEn: 'Ask the price', canDoVi: 'Tôi có thể hỏi giá của một món đồ.', settingVi: 'Bạn đang xem một món hàng ở chợ.', roles: ['Khách', 'Người bán'], lines: [['How much is this?', 'Cái này bao nhiêu tiền?'], ['It’s five dollars.', 'Nó là năm đô la.']], chunks: [['How much is this?', 'Cái này bao nhiêu tiền?', 'khi cầm một món đồ', 'This là cái này.'], ['How much are these?', 'Những cái này bao nhiêu?', 'khi hỏi nhiều món', 'These dùng cho số nhiều.'], ['That’s too expensive.', 'Cái đó quá đắt.', 'khi giá vượt ngân sách', 'Too expensive là quá đắt.']], answer: 'How much is this?', distractor: 'Please open the door.', slots: ['món muốn hỏi', 'ngân sách của bạn'], exemplar: 'How much is this bag?',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để hỏi giá.', cueVi: 'How much is this?', patterns: [{ requiredFragments: ["how much"] }], hintVi: 'Gợi ý: "How much is this?"' },
  },
  { unit: 2, titleVi: 'Nói nhu cầu ăn uống', titleEn: 'State a dietary need', canDoVi: 'Tôi có thể nói một nhu cầu ăn uống cơ bản.', settingVi: 'Bạn cần hỏi món có chứa hạt không.', roles: ['Khách', 'Phục vụ'], lines: [['Does this have nuts?', 'Món này có hạt không?'], ['No, it doesn’t have nuts.', 'Không, nó không có hạt.']], chunks: [['Does this have nuts?', 'Món này có hạt không?', 'khi kiểm tra thành phần', 'Does this have ...? hỏi món có gì.'], ['I can’t eat ...', 'Tôi không thể ăn ...', 'khi nói điều cần tránh', 'Nói thực phẩm sau eat.'], ['Is there a vegetarian option?', 'Có lựa chọn chay không?', 'khi cần món chay', 'Option là lựa chọn.']], answer: 'Does this have nuts?', distractor: 'I am on platform six.', slots: ['thực phẩm cần tránh'], exemplar: 'I can’t eat peanuts. Does this have peanuts?',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để hỏi thành phần món ăn.', cueVi: 'Does this have ⬦?', patterns: [{ requiredFragments: ["does this have"] }, { requiredFragments: ["i can't eat"] }, { requiredFragments: ["i cannot eat"] }], hintVi: 'Gợi ý: "Does this have ⬦?" hoặc "I can\'t eat ..."' },
  },
  { unit: 2, titleVi: 'Thanh toán', titleEn: 'Pay for a purchase', canDoVi: 'Tôi có thể xin hóa đơn tại nhà hàng.', settingVi: 'Bạn đã ăn xong và muốn trả tiền.', roles: ['Khách', 'Phục vụ'], lines: [['Could I have the bill, please?', 'Tôi có thể xin hóa đơn không, làm ơn?'], ['Yes. You can pay by card.', 'Được. Bạn có thể trả bằng thẻ.']], chunks: [['Could I have the bill, please?', 'Tôi có thể xin hóa đơn không?', 'khi muốn thanh toán', 'Bill là hóa đơn nhà hàng.'], ['Can I pay by card?', 'Tôi có thể trả bằng thẻ không?', 'khi hỏi cách trả', 'Pay by card là trả thẻ.'], ['Here you are.', 'Của bạn đây.', 'khi đưa tiền hoặc thẻ', 'Dùng khi đưa vật cho ai.']], answer: 'Could I have the bill, please?', distractor: 'I need a doctor.', slots: ['cách thanh toán'], exemplar: 'Could I have the bill, please? Can I pay by card?',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để xin hóa đơn.', cueVi: 'Could I have the bill, please?', patterns: [{ requiredFragments: ["the bill"] }, { requiredFragments: ["the check"] }, { requiredFragments: ["pay", "card"] }], hintVi: 'Gợi ý: "Could I have the bill, please?"' },
  },
  { unit: 3, titleVi: 'Mua vé', titleEn: 'Buy a ticket', canDoVi: 'Tôi có thể mua vé cho một chuyến đi.', settingVi: 'Bạn mua vé tàu tại quầy.', roles: ['Khách', 'Nhân viên vé'], lines: [['One ticket to Da Nang, please.', 'Một vé đến Đà Nẵng, làm ơn.'], ['One way or return?', 'Một chiều hay khứ hồi?']], chunks: [['One ticket to ...', 'Một vé đến ...', 'khi mua vé', 'Nói điểm đến sau to.'], ['One way or return?', 'Một chiều hay khứ hồi?', 'khi chọn loại vé', 'One way là một chiều.'], ['What time is the next train?', 'Tàu tiếp theo lúc mấy giờ?', 'khi hỏi chuyến kế tiếp', 'Next là tiếp theo.']], answer: 'One ticket to Da Nang, please.', distractor: 'This soup has nuts.', slots: ['điểm đến', 'một chiều hoặc khứ hồi'], exemplar: 'One return ticket to Hue, please.',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để mua vé.', cueVi: 'One ticket to ⬦, please.', patterns: [{ requiredFragments: ["ticket", "to"] }, { requiredFragments: ["ticket", "please"] }], hintVi: 'Gợi ý: "One ticket to ⬦, please."' },
  },
  { unit: 3, titleVi: 'Xác nhận sân ga', titleEn: 'Confirm the platform', canDoVi: 'Tôi có thể hỏi sân ga cho chuyến tàu của mình.', settingVi: 'Bạn ở nhà ga và cần tìm sân ga.', roles: ['Hành khách', 'Nhân viên ga'], lines: [['Which platform for the airport train?', 'Tàu đi sân bay ở sân ga nào?'], ['Platform three.', 'Sân ga số ba.']], chunks: [['Which platform for ...?', 'Sân ga nào cho ...?', 'khi tìm sân ga', 'Which hỏi lựa chọn.'], ['Is this the right train?', 'Đây có phải tàu đúng không?', 'khi muốn xác nhận', 'Right là đúng.'], ['Thank you. Platform three.', 'Cảm ơn. Sân ga số ba.', 'khi nhắc lại thông tin', 'Nhắc lại số để kiểm tra.']], answer: 'Which platform for the airport train?', distractor: 'I’d like chicken rice.', slots: ['điểm đến'], exemplar: 'Which platform for the train to Hanoi?',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để hỏi sân ga.', cueVi: 'Which platform for ⬦?', patterns: [{ requiredFragments: ["which platform"] }, { requiredFragments: ["platform", "for"] }], hintVi: 'Gợi ý: "Which platform for ⬦?"' },
  },
  { unit: 3, titleVi: 'Gọi taxi', titleEn: 'Ask for a taxi', canDoVi: 'Tôi có thể yêu cầu một chuyến taxi.', settingVi: 'Bạn gọi taxi ở khách sạn.', roles: ['Khách', 'Lễ tân'], lines: [['Could you call a taxi for me?', 'Bạn có thể gọi taxi cho tôi không?'], ['Yes. Where are you going?', 'Được. Bạn đi đâu?']], chunks: [['Could you call a taxi for me?', 'Bạn có thể gọi taxi cho tôi không?', 'khi cần hỗ trợ gọi xe', 'Could you là lời nhờ lịch sự.'], ['I’m going to ...', 'Tôi đi đến ...', 'khi nói điểm đến', 'Going to nói nơi sắp đến.'], ['How long will it take?', 'Mất bao lâu?', 'khi hỏi thời gian đi', 'How long hỏi khoảng thời gian.']], answer: 'Could you call a taxi for me?', distractor: 'The restroom is left.', slots: ['điểm đến', 'thời gian muốn đi'], exemplar: 'Could you call a taxi for me? I’m going to the airport.',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để nhờ gọi taxi.', cueVi: 'Could you call a taxi for me?', patterns: [{ requiredFragments: ["call", "taxi"] }, { requiredFragments: ["call", "cab"] }, { requiredFragments: ["get", "taxi"] }], hintVi: 'Gợi ý: "Could you call a taxi for me?"' },
  },
  { unit: 3, titleVi: 'Nhận phòng khách sạn', titleEn: 'Check in at a hotel', canDoVi: 'Tôi có thể nói mình có đặt phòng.', settingVi: 'Bạn đến quầy lễ tân khách sạn.', roles: ['Khách', 'Lễ tân'], lines: [['I have a reservation under Nguyen.', 'Tôi có đặt phòng tên Nguyen.'], ['May I see your passport, please?', 'Tôi có thể xem hộ chiếu của bạn không?']], chunks: [['I have a reservation under ...', 'Tôi có đặt phòng tên ...', 'khi nhận phòng', 'Nói họ đặt phòng sau under.'], ['Here is my passport.', 'Đây là hộ chiếu của tôi.', 'khi đưa hộ chiếu', 'Here is là đây là.'], ['What time is breakfast?', 'Bữa sáng lúc mấy giờ?', 'khi hỏi tiện ích khách sạn', 'Breakfast là bữa sáng.']], answer: 'I have a reservation under Nguyen.', distractor: 'Can you say it again?', slots: ['tên đặt phòng', 'câu hỏi về khách sạn'], exemplar: 'I have a reservation under Tran.',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để nhận phòng khách sạn.', cueVi: 'I have a reservation under ⬦', patterns: [{ requiredFragments: ["reservation", "under"] }, { requiredFragments: ["i have", "reservation"] }, { requiredFragments: ["check in"] }], hintVi: 'Gợi ý: "I have a reservation under ⬦"' },
  },
  { unit: 3, titleVi: 'Báo vấn đề đặt phòng', titleEn: 'Report a booking problem', canDoVi: 'Tôi có thể báo rằng không tìm thấy đặt phòng.', settingVi: 'Lễ tân không thấy thông tin đặt phòng của bạn.', roles: ['Khách', 'Lễ tân'], lines: [['I booked a room, but I can’t find it.', 'Tôi đã đặt phòng, nhưng tôi không tìm thấy nó.'], ['Can I see your confirmation email?', 'Tôi có thể xem email xác nhận không?']], chunks: [['I booked a room, but ...', 'Tôi đã đặt phòng, nhưng ...', 'khi báo vấn đề', 'But nối hai ý trái nhau.'], ['I can’t find it.', 'Tôi không thể tìm thấy nó.', 'khi thông tin bị thiếu', 'Can’t là cannot.'], ['Here is my confirmation email.', 'Đây là email xác nhận của tôi.', 'khi đưa bằng chứng đặt phòng', 'Confirmation là xác nhận.']], answer: 'I can’t find it.', distractor: 'It costs five dollars.', slots: ['thông tin bị thiếu', 'tên đặt phòng'], exemplar: 'I booked a room, but I can’t find the reservation.',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để báo vấn đề đặt phòng.', cueVi: 'I booked a room, but ⬦', patterns: [{ requiredFragments: ["booked", "room"] }, { requiredFragments: ["can't find"] }, { requiredFragments: ["cannot find"] }], hintVi: 'Gợi ý: "I booked a room, but ⬦"' },
  },
  { unit: 4, titleVi: 'Mua đồ thiết yếu', titleEn: 'Shop for an essential', canDoVi: 'Tôi có thể hỏi nơi mua một đồ thiết yếu.', settingVi: 'Bạn cần mua nước và tìm siêu thị.', roles: ['Khách', 'Người dân'], lines: [['Is there a supermarket nearby?', 'Có siêu thị nào gần đây không?'], ['Yes, across the street.', 'Có, ở bên kia đường.']], chunks: [['Is there a ... nearby?', 'Có ... nào gần đây không?', 'khi tìm dịch vụ', 'Nearby là gần đây.'], ['I need to buy ...', 'Tôi cần mua ...', 'khi nói nhu cầu', 'Nói món cần mua sau buy.'], ['Across the street.', 'Ở bên kia đường.', 'khi nghe chỉ đường', 'Across là đối diện/bên kia.']], answer: 'Is there a supermarket nearby?', distractor: 'My reservation is lost.', slots: ['đồ cần mua', 'nơi cần tìm'], exemplar: 'Is there a supermarket nearby? I need to buy water.',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để tìm cửa hàng gần đây.', cueVi: 'Is there a ⬦ nearby?', patterns: [{ requiredFragments: ["is there", "nearby"] }, { requiredFragments: ["where", "supermarket"] }, { requiredFragments: ["where can i buy"] }], hintVi: 'Gợi ý: "Is there a ⬦ nearby?"' },
  },
  { unit: 4, titleVi: 'Đổi hoặc trả hàng', titleEn: 'Return or exchange an item', canDoVi: 'Tôi có thể xin đổi một món hàng.', settingVi: 'Bạn muốn đổi áo vì sai cỡ.', roles: ['Khách', 'Nhân viên cửa hàng'], lines: [['I’d like to exchange this, please.', 'Tôi muốn đổi cái này, làm ơn.'], ['Do you have the receipt?', 'Bạn có hóa đơn không?']], chunks: [['I’d like to exchange this.', 'Tôi muốn đổi cái này.', 'khi muốn đổi hàng', 'Exchange là đổi hàng.'], ['It’s too small.', 'Nó quá nhỏ.', 'khi nói lý do', 'Too small là quá nhỏ.'], ['I have the receipt.', 'Tôi có hóa đơn.', 'khi có bằng chứng mua hàng', 'Receipt là hóa đơn mua hàng.']], answer: 'I’d like to exchange this.', distractor: 'The bus leaves at nine.', slots: ['món muốn đổi', 'lý do'], exemplar: 'I’d like to exchange this. It’s too small.',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để xin đổi hàng.', cueVi: 'I\'d like to exchange this.', patterns: [{ requiredFragments: ["exchange"] }, { requiredFragments: ["return"] }, { requiredFragments: ["like to", "change"] }], hintVi: 'Gợi ý: "I\'d like to exchange this."' },
  },
  { unit: 4, titleVi: 'Đặt lịch hẹn', titleEn: 'Make an appointment', canDoVi: 'Tôi có thể hỏi giờ trống để đặt lịch.', settingVi: 'Bạn gọi để đặt lịch cắt tóc.', roles: ['Khách', 'Nhân viên'], lines: [['Do you have any time on Friday?', 'Bạn có giờ nào vào thứ Sáu không?'], ['Yes, at two o’clock.', 'Có, lúc hai giờ.']], chunks: [['Do you have any time on ...?', 'Bạn có giờ nào vào ... không?', 'khi xin lịch hẹn', 'Nói ngày sau on.'], ['I’d like to make an appointment.', 'Tôi muốn đặt lịch hẹn.', 'khi nói mục đích', 'Appointment là lịch hẹn.'], ['Two o’clock works for me.', 'Hai giờ phù hợp với tôi.', 'khi chốt giờ', 'Works for me là phù hợp.']], answer: 'I’d like to make an appointment.', distractor: 'I need the bill.', slots: ['ngày', 'giờ phù hợp'], exemplar: 'I’d like to make an appointment on Tuesday.',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để đặt lịch hẹn.', cueVi: 'I\'d like to make an appointment.', patterns: [{ requiredFragments: ["make", "appointment"] }, { requiredFragments: ["book", "appointment"] }, { requiredFragments: ["schedule", "appointment"] }], hintVi: 'Gợi ý: "I\'d like to make an appointment."' },
  },
  { unit: 4, titleVi: 'Mua thuốc cơ bản', titleEn: 'Ask at a pharmacy', canDoVi: 'Tôi có thể xin một loại thuốc cơ bản ở nhà thuốc.', settingVi: 'Bạn bị đau đầu và vào nhà thuốc.', roles: ['Khách', 'Dược sĩ'], lines: [['Do you have something for a headache?', 'Bạn có gì cho đau đầu không?'], ['Yes, this may help.', 'Có, cái này có thể giúp.']], chunks: [['Do you have something for ...?', 'Bạn có gì cho ... không?', 'khi xin sản phẩm', 'Something for nói công dụng.'], ['I have a headache.', 'Tôi bị đau đầu.', 'khi mô tả triệu chứng đơn giản', 'Headache là đau đầu.'], ['How often should I take it?', 'Tôi nên dùng nó bao lâu một lần?', 'khi hỏi cách dùng', 'How often hỏi tần suất.']], answer: 'I have a headache.', distractor: 'I am going to the station.', slots: ['triệu chứng đơn giản'], exemplar: 'I have a headache. Do you have something for it?',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để mô tả triệu chứng.', cueVi: 'I have a headache.', patterns: [{ requiredFragments: ["i have", "headache"] }, { requiredFragments: ["do you have something for"] }, { requiredFragments: ["my head hurts"] }], hintVi: 'Gợi ý: "I have a headache."' },
  },
  { unit: 4, titleVi: 'Xin trợ giúp', titleEn: 'Ask for help', canDoVi: 'Tôi có thể nhờ giúp khi gặp khó khăn.', settingVi: 'Bạn không biết dùng máy bán vé.', roles: ['Khách', 'Nhân viên'], lines: [['Could you help me with this machine?', 'Bạn có thể giúp tôi với máy này không?'], ['Sure, press this button.', 'Được, nhấn nút này.']], chunks: [['Could you help me with ...?', 'Bạn có thể giúp tôi với ... không?', 'khi cần hỗ trợ', 'With theo sau help me.'], ['I don’t understand.', 'Tôi không hiểu.', 'khi cần giải thích', 'Câu ngắn, rõ ràng.'], ['Which button?', 'Nút nào?', 'khi cần chỉ cụ thể', 'Which hỏi lựa chọn.']], answer: 'Could you help me with this machine?', distractor: 'I have a reservation.', slots: ['vật hoặc việc cần giúp'], exemplar: 'Could you help me with this ticket machine?',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để nhờ giúp.', cueVi: 'Could you help me with ⬦?', patterns: [{ requiredFragments: ["help me"] }, { requiredFragments: ["could you help"] }, { requiredFragments: ["can you help"] }], hintVi: 'Gợi ý: "Could you help me with ⬦?"' },
  },
  { unit: 5, titleVi: 'Gặp đồng nghiệp', titleEn: 'Meet a coworker', canDoVi: 'Tôi có thể tự giới thiệu với đồng nghiệp.', settingVi: 'Bạn gặp đồng nghiệp vào ngày đầu đi làm.', roles: ['Người học', 'Đồng nghiệp'], lines: [['Hi, I’m Minh. I’m new here.', 'Chào, tôi là Minh. Tôi mới ở đây.'], ['Welcome, Minh. I’m Hoa.', 'Chào mừng, Minh. Tôi là Hoa.']], chunks: [['I’m new here.', 'Tôi mới ở đây.', 'khi mới đến nơi', 'New here nói bạn vừa tham gia.'], ['I work with ...', 'Tôi làm việc với ...', 'khi nói nhóm làm việc', 'With nói cùng ai.'], ['Nice to meet you.', 'Rất vui được gặp bạn.', 'khi gặp đồng nghiệp', 'Dùng như lời chào thân thiện.']], answer: 'I’m new here.', distractor: 'This is too expensive.', slots: ['tên', 'nhóm hoặc vai trò'], exemplar: 'Hi, I’m An. I’m new here.',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để nói bạn mới đến.', cueVi: 'I\'m new here.', patterns: [{ requiredFragments: ["i'm new here"], rejectedNames: ["minh", "an", "hoa"] }, { requiredFragments: ["i am new here"], rejectedNames: ["minh", "an", "hoa"] }, { requiredFragments: ["new here"] }], hintVi: 'Gợi ý: "I\'m new here."' },
  },
  { unit: 5, titleVi: 'Nói chuyện ngắn', titleEn: 'Make simple small talk', canDoVi: 'Tôi có thể bắt đầu một cuộc trò chuyện ngắn thân thiện.', settingVi: 'Bạn đứng cạnh một người quen trong giờ nghỉ.', roles: ['Người học', 'Người quen'], lines: [['How is your day going?', 'Ngày của bạn thế nào?'], ['Pretty good, thanks.', 'Khá tốt, cảm ơn.']], chunks: [['How is your day going?', 'Ngày của bạn thế nào?', 'khi bắt đầu nói chuyện', 'Going hỏi diễn tiến.'], ['Pretty good, thanks.', 'Khá tốt, cảm ơn.', 'khi trả lời tích cực', 'Pretty good là khá tốt.'], ['What are you doing this weekend?', 'Cuối tuần này bạn làm gì?', 'khi hỏi kế hoạch nhẹ nhàng', 'This weekend là cuối tuần này.']], answer: 'How is your day going?', distractor: 'Which platform is the train?', slots: ['một câu hỏi thân thiện'], exemplar: 'How is your day going? Mine is good.',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để bắt đầu nói chuyện.', cueVi: 'How is your day going?', patterns: [{ requiredFragments: ["how", "your day"] }, { requiredFragments: ["how are you"] }, { requiredFragments: ["how's it going"] }], hintVi: 'Gợi ý: "How is your day going?"' },
  },
  { unit: 5, titleVi: 'Hỏi việc cần làm', titleEn: 'Ask about a work task', canDoVi: 'Tôi có thể hỏi rõ một việc cần làm.', settingVi: 'Bạn chưa rõ phần việc được giao.', roles: ['Nhân viên', 'Quản lý'], lines: [['What should I do first?', 'Tôi nên làm gì trước?'], ['Please email the customer.', 'Làm ơn gửi email cho khách hàng.']], chunks: [['What should I do first?', 'Tôi nên làm gì trước?', 'khi cần ưu tiên', 'Should I do hỏi việc nên làm.'], ['Could you show me?', 'Bạn có thể chỉ tôi không?', 'khi cần hướng dẫn', 'Show me là chỉ cho tôi.'], ['I understand now.', 'Bây giờ tôi hiểu rồi.', 'khi đã rõ', 'Now là bây giờ.']], answer: 'What should I do first?', distractor: 'Can I pay by card?', slots: ['việc bạn cần làm rõ'], exemplar: 'What should I do first for this report?',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để hỏi việc cần làm.', cueVi: 'What should I do first?', patterns: [{ requiredFragments: ["what should i do"] }, { requiredFragments: ["what do i do"] }, { requiredFragments: ["could you show me"] }], hintVi: 'Gợi ý: "What should I do first?"' },
  },
  { unit: 5, titleVi: 'Báo vắng mặt', titleEn: 'Explain an absence', canDoVi: 'Tôi có thể báo mình sẽ đến muộn hoặc vắng.', settingVi: 'Bạn cần nhắn cho quản lý vì bị ốm.', roles: ['Nhân viên', 'Quản lý'], lines: [['I’m not feeling well today.', 'Hôm nay tôi không khỏe.'], ['Thanks for letting me know.', 'Cảm ơn bạn đã cho tôi biết.']], chunks: [['I’m not feeling well.', 'Tôi không khỏe.', 'khi bị ốm', 'Feeling well là cảm thấy khỏe.'], ['I will be late.', 'Tôi sẽ đến muộn.', 'khi báo trễ', 'Will nói tương lai gần.'], ['I can come tomorrow.', 'Tôi có thể đến vào ngày mai.', 'khi nêu thời điểm mới', 'Tomorrow là ngày mai.']], answer: 'I will be late.', distractor: 'I need to exchange this.', slots: ['lý do', 'thời gian bạn có thể đến'], exemplar: 'I’m not feeling well. I will be late today.',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để báo vắng mặt.', cueVi: 'I\'m not feeling well. / I will be late.', patterns: [{ requiredFragments: ["not feeling well"] }, { requiredFragments: ["will be late"] }, { requiredFragments: ["i'm sick"] }, { requiredFragments: ["i am sick"] }], hintVi: 'Gợi ý: "I\'m not feeling well." hoặc "I will be late."' },
  },
  { unit: 5, titleVi: 'Để lại lời nhắn điện thoại', titleEn: 'Leave a phone message', canDoVi: 'Tôi có thể để lại lời nhắn ngắn qua điện thoại.', settingVi: 'Người bạn cần gặp không nghe máy.', roles: ['Người gọi', 'Lễ tân'], lines: [['Can I leave a message for Kim?', 'Tôi có thể để lại lời nhắn cho Kim không?'], ['Yes, what is your number?', 'Được, số của bạn là gì?']], chunks: [['Can I leave a message for ...?', 'Tôi có thể để lại lời nhắn cho ... không?', 'khi gọi điện', 'Message for nói cho ai.'], ['Please call me back.', 'Làm ơn gọi lại cho tôi.', 'khi cần phản hồi', 'Call back là gọi lại.'], ['My number is ...', 'Số của tôi là ...', 'khi để số điện thoại', 'Number là số điện thoại.']], answer: 'Can I leave a message for Kim?', distractor: 'The shop opens at ten.', slots: ['tên người nhận', 'số điện thoại'], exemplar: 'Can I leave a message for Mai? My number is 0900.',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để để lại lời nhắn.', cueVi: 'Can I leave a message for ⬦?', patterns: [{ requiredFragments: ["leave", "message"], rejectedNames: ["kim", "mai"] }, { requiredFragments: ["please call me back"] }], hintVi: 'Gợi ý: "Can I leave a message for ⬦?"' },
  },
  { unit: 6, titleVi: 'Báo mất đồ', titleEn: 'Report a lost item', canDoVi: 'Tôi có thể báo mình làm mất một món đồ.', settingVi: 'Bạn không tìm thấy ví ở sân bay.', roles: ['Hành khách', 'Nhân viên'], lines: [['I lost my wallet.', 'Tôi mất ví.'], ['Where did you last see it?', 'Lần cuối bạn thấy nó ở đâu?']], chunks: [['I lost my ...', 'Tôi mất ...', 'khi báo mất đồ', 'Nói món bị mất sau my.'], ['I last saw it at ...', 'Lần cuối tôi thấy nó ở ...', 'khi nhớ vị trí', 'Last saw là thấy lần cuối.'], ['It is black.', 'Nó màu đen.', 'khi mô tả đồ', 'Nói màu đơn giản.']], answer: 'I lost my wallet.', distractor: 'I’m new here.', slots: ['món bị mất', 'nơi thấy lần cuối'], exemplar: 'I lost my phone. I last saw it at the café.',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để báo mất đồ.', cueVi: 'I lost my ⬦', patterns: [{ requiredFragments: ["i lost my"] }, { requiredFragments: ["i've lost my"] }, { requiredFragments: ["i have lost my"] }], hintVi: 'Gợi ý: "I lost my ⬦"' },
  },
  { unit: 6, titleVi: 'Gọi hỗ trợ khẩn cấp', titleEn: 'Make an emergency call', canDoVi: 'Tôi có thể nói ngắn gọn rằng mình cần giúp gấp.', settingVi: 'Bạn chứng kiến một tình huống nguy hiểm và gọi hỗ trợ.', roles: ['Người gọi', 'Nhân viên hỗ trợ'], lines: [['I need help. It’s an emergency.', 'Tôi cần giúp. Đây là tình huống khẩn cấp.'], ['What is your location?', 'Bạn đang ở đâu?']], chunks: [['I need help.', 'Tôi cần giúp.', 'khi cần hỗ trợ gấp', 'Nói rõ và ngắn.'], ['It’s an emergency.', 'Đây là tình huống khẩn cấp.', 'khi tình huống nghiêm trọng', 'Emergency là khẩn cấp.'], ['My location is ...', 'Vị trí của tôi là ...', 'khi được hỏi nơi ở', 'Nói nơi cụ thể sau is.']], answer: 'I need help.', distractor: 'I’d like a tea.', slots: ['vị trí của bạn', 'điều đang xảy ra'], exemplar: 'I need help. My location is the station entrance.',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để gọi hỗ trợ khẩn cấp.', cueVi: 'I need help.', patterns: [{ requiredFragments: ["i need help"] }, { requiredFragments: ["it's an emergency"] }, { requiredFragments: ["emergency"] }], hintVi: 'Gợi ý: "I need help." hoặc "It\'s an emergency."' },
  },
  { unit: 6, titleVi: 'Mô tả cơn đau', titleEn: 'Describe pain simply', canDoVi: 'Tôi có thể mô tả một cơn đau đơn giản.', settingVi: 'Bạn nói với nhân viên y tế về chỗ đau.', roles: ['Bệnh nhân', 'Nhân viên y tế'], lines: [['My stomach hurts.', 'Bụng tôi đau.'], ['How long has it hurt?', 'Nó đau bao lâu rồi?']], chunks: [['My ... hurts.', '... của tôi đau.', 'khi nói vị trí đau', 'Nói bộ phận cơ thể trước hurts.'], ['It started this morning.', 'Nó bắt đầu sáng nay.', 'khi nói thời điểm', 'Started là bắt đầu.'], ['It hurts a lot.', 'Nó đau nhiều.', 'khi nói mức độ', 'A lot là nhiều.']], answer: 'My stomach hurts.', distractor: 'I have the receipt.', slots: ['bộ phận đau', 'thời điểm bắt đầu'], exemplar: 'My head hurts. It started this morning.',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để mô tả cơn đau.', cueVi: 'My ⬦ hurts.', patterns: [{ requiredFragments: ["hurts"] }, { requiredFragments: ["it hurts"] }, { requiredFragments: ["i have", "pain"] }], hintVi: 'Gợi ý: "My ⬦ hurts."' },
  },
  { unit: 6, titleVi: 'Dời lịch hẹn', titleEn: 'Reschedule an appointment', canDoVi: 'Tôi có thể xin dời lịch hẹn sang thời gian khác.', settingVi: 'Bạn không thể đến lịch hẹn vào ngày mai.', roles: ['Khách', 'Nhân viên'], lines: [['Can I change my appointment?', 'Tôi có thể đổi lịch hẹn không?'], ['Yes, what day works for you?', 'Được, ngày nào phù hợp với bạn?']], chunks: [['Can I change my appointment?', 'Tôi có thể đổi lịch hẹn không?', 'khi cần dời lịch', 'Change là đổi.'], ['I can’t come tomorrow.', 'Tôi không thể đến ngày mai.', 'khi nói lý do thời gian', 'Can’t come là không thể đến.'], ['Does Friday work?', 'Thứ Sáu có phù hợp không?', 'khi đề xuất ngày mới', 'Work ở đây là phù hợp.']], answer: 'Can I change my appointment?', distractor: 'Where is the restroom?', slots: ['lịch hẹn', 'ngày mới'], exemplar: 'Can I change my appointment to Friday?',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để dời lịch hẹn.', cueVi: 'Can I change my appointment?', patterns: [{ requiredFragments: ["change", "appointment"] }, { requiredFragments: ["reschedule"] }, { requiredFragments: ["move", "appointment"] }], hintVi: 'Gợi ý: "Can I change my appointment?"' },
  },
  { unit: 6, titleVi: 'Tạm biệt và hẹn gặp lại', titleEn: 'Say goodbye and make a future plan', canDoVi: 'Tôi có thể đề nghị gặp lại vào tuần sau.', settingVi: 'Bạn kết thúc cuộc gặp với một người bạn mới.', roles: ['Người học', 'Bạn mới'], lines: [['It was nice talking with you.', 'Nói chuyện với bạn rất vui.'], ['Let’s meet again next week.', 'Hãy gặp lại tuần sau.']], chunks: [['It was nice talking with you.', 'Nói chuyện với bạn rất vui.', 'khi kết thúc trò chuyện', 'Was nice là đã rất vui.'], ['Let’s meet again.', 'Hãy gặp lại.', 'khi muốn hẹn lần sau', 'Let’s là hãy cùng.'], ['See you next week.', 'Hẹn gặp bạn tuần sau.', 'khi chào tạm biệt', 'See you là hẹn gặp lại.']], answer: 'Let’s meet again.', distractor: 'I lost my wallet.', slots: ['thời gian gặp lại', 'lời chào tạm biệt'], exemplar: 'It was nice talking with you. See you next week.',   retrieval: { promptVi: 'Hãy gõ lại câu dùng để hẹn gặp lại.', cueVi: 'Let\'s meet again. / See you …', patterns: [{ requiredFragments: ["let's meet"] }, { requiredFragments: ["let us meet"] }, { requiredFragments: ["see you"] }, { requiredFragments: ["nice talking"] }], hintVi: 'Gợi ý: "Let\'s meet again." hoặc "See you next week."' },
  },
];

function makeLesson(seed: LessonSeed, index: number): EnglishSurvivalLesson {
  const [firstLine, secondLine] = seed.lines;
  return {
    id: `en-survival-${index + 1}`,
    unit: seed.unit,
    order: index + 1,
    titleVi: seed.titleVi,
    titleEn: seed.titleEn,
    canDoVi: seed.canDoVi,
    scenario: { settingVi: seed.settingVi, roles: seed.roles },
    dialogue: [
      { speaker: 'A', text: firstLine[0], vi: firstLine[1] },
      { speaker: 'B', text: secondLine[0], vi: secondLine[1] },
    ],
    chunks: seed.chunks.map(([text, vi, useWhenVi, vietnameseLearnerCueVi]) => ({ text, vi, useWhenVi, vietnameseLearnerCueVi })),
    contextCue: { titleVi: 'Dùng ngay trong tình huống này', bodyVi: seed.settingVi },
    comprehension: {
      promptVi: 'Trong tình huống này, câu nào giúp bạn đạt mục tiêu?',
      options: [seed.answer, seed.distractor],
      correctAnswer: seed.answer,
      explanationVi: 'Câu đúng khớp với mục tiêu giao tiếp của bài học.',
    },
    production: {
      promptVi: 'Nói hoặc viết một câu dùng chi tiết thật của bạn. Đừng chép nguyên mẫu.',
      requiredSlots: seed.slots,
      exemplar: seed.exemplar,
      rejectExactModelCopy: true,
    },
    retrieval: {
      promptVi: seed.retrieval.promptVi,
      cueVi: seed.retrieval.cueVi,
      acceptedPatterns: seed.retrieval.patterns,
      answerHintVi: seed.retrieval.hintVi,
    },
    selfReview: [
      `Tôi có thể nói: “${seed.chunks[0][0]}”.`,
      `Tôi nhớ khi nào dùng: “${seed.chunks[1][0]}”.`,
      'Tôi đã thêm ít nhất một chi tiết thật của mình.',
      'Tôi biết một câu tôi muốn luyện lại vào lần sau.',
    ],
  };
}

export const englishSurvival30: EnglishSurvivalLesson[] = seeds.map(makeLesson);

export function getEnglishSurvivalLesson(id: string): EnglishSurvivalLesson | undefined {
  return englishSurvival30.find((lesson) => lesson.id === id);
}

export function isEnglishSurvivalLesson(id: string): id is EnglishSurvivalLesson['id'] {
  return getEnglishSurvivalLesson(id) !== undefined;
}
