import type { GrammarTopic } from './grammarBank.ts';

export const grammarBankZh: GrammarTopic[] = [
  // ═══ B1 / HSK4 ═══
  {
    id: 'zh_g1',
    title: '把字句 (Ba construction)',
    level: 'B1',
    description: 'The disposal construction for emphasizing action on a specific object',
    theory: 'The 把 (bǎ) construction is used to indicate what happens to a specific, definite object as a result of an action. It moves the object before the verb and emphasizes the disposal, handling, or result of the action on that object. The object after 把 must be specific (not indefinite). The verb cannot stand alone — it must have a complement, 了, or another element after it.',
    formula: 'Subject + 把 + Object + Verb + Complement/了/Result',
    examples: [
      { sentence: '请你把门关上。', explanation: 'Please close the door. 把 moves "door" before the verb "close", with directional complement 上.' },
      { sentence: '他把作业做完了。', explanation: 'He finished the homework. The result complement 完 indicates completion.' },
      { sentence: '我把那本书放在桌子上了。', explanation: 'I put that book on the table. Location complement follows the verb.' },
    ],
    commonMistakes: [
      '❌ "我把看了那本书" → ✅ "我把那本书看了" — The object must follow 把, not the verb.',
      '❌ "他把一个苹果吃" → ✅ "他把那个苹果吃了" — The verb needs a complement or 了; the object should be definite.',
      '❌ "我把不喜欢这个" → ✅ This cannot use 把; 把 requires action verbs with a result on the object.',
    ],
    questions: [
      {
        id: 'zh_g1q1',
        question: '请你把窗户___。',
        options: ['打开', '打', '开', '打开着'],
        correctAnswer: '打开',
        explanation: 'The 把 construction requires the verb to have a complement. 打开 (open) is a verb-complement combination.',
      },
      {
        id: 'zh_g1q2',
        question: '她把衣服___干净了。',
        options: ['洗得', '洗', '洗了', '洗着'],
        correctAnswer: '洗得',
        explanation: '洗得干净 uses the degree complement structure with 得 to express "washed clean".',
      },
      {
        id: 'zh_g1q3',
        question: '他___那杯咖啡喝完了。',
        options: ['把', '被', '让', '给'],
        correctAnswer: '把',
        explanation: '把 is used when the subject actively does something to a specific object (the coffee).',
      },
      {
        id: 'zh_g1q4',
        question: 'Which sentence correctly uses the 把 construction?',
        options: [
          '我把书看了。',
          '我把看了书。',
          '我把书看。',
          '把我书看了。',
        ],
        correctAnswer: '我把书看了。',
        explanation: 'Correct order: Subject + 把 + Object + Verb + 了. The verb must have 了 or a complement.',
      },
    ],
    tags: ['ba-construction', 'disposal', 'HSK4', 'word-order'],
  },
  {
    id: 'zh_g2',
    title: '被字句 (Bei construction)',
    level: 'B1',
    description: 'Passive voice construction in Mandarin Chinese',
    theory: 'The 被 (bèi) construction is the primary way to express passive voice in Chinese. It indicates that the subject is the receiver of an action. Traditionally, 被 sentences often carry a negative or undesirable connotation, though modern usage has expanded. The agent (doer) can be included or omitted.',
    formula: 'Subject (receiver) + 被 + (Agent) + Verb + Complement/了',
    examples: [
      { sentence: '我的手机被偷了。', explanation: 'My phone was stolen. Agent omitted; negative connotation.' },
      { sentence: '那本书被他借走了。', explanation: 'That book was borrowed (and taken) by him. Agent included.' },
      { sentence: '蛋糕被孩子们吃光了。', explanation: 'The cake was eaten up by the children. Result complement 光 means "completely".' },
    ],
    commonMistakes: [
      '❌ "书被看" → ✅ "书被看了" — The verb in a 被 sentence must have a complement or 了.',
      '❌ "我被喜欢他" → ✅ 被 is not used with stative/psychological verbs like 喜欢.',
      '❌ "被他书拿走了" → ✅ "书被他拿走了" — The subject (receiver) must come before 被.',
    ],
    questions: [
      {
        id: 'zh_g2q1',
        question: '那个花瓶___孩子打碎了。',
        options: ['被', '把', '让', '由'],
        correctAnswer: '被',
        explanation: 'The vase (subject) received the action of being broken — passive voice uses 被.',
      },
      {
        id: 'zh_g2q2',
        question: '他的钱包被人___了。',
        options: ['偷走', '偷', '偷着', '在偷'],
        correctAnswer: '偷走',
        explanation: 'In a 被 sentence the verb needs a complement. 偷走 means "stolen and taken away".',
      },
      {
        id: 'zh_g2q3',
        question: 'Which sentence correctly uses 被?',
        options: [
          '作业被我写完了。',
          '被我作业写完了。',
          '我被作业写完了。',
          '作业被写我完了。',
        ],
        correctAnswer: '作业被我写完了。',
        explanation: 'Correct order: Receiver + 被 + Agent + Verb + Complement. The homework was finished by me.',
      },
    ],
    tags: ['passive', 'bei-construction', 'HSK4', 'voice'],
  },
  {
    id: 'zh_g3',
    title: '程度补语 (Degree complements)',
    level: 'B1',
    description: 'Expressing the degree or extent of an action or state',
    theory: 'Degree complements (程度补语) use 得 (de) after a verb or adjective to describe how well, how much, or to what extent an action is performed. The complement after 得 can be an adjective, a phrase, or a clause. When there is an object, the verb is often repeated: Verb + Object, Verb + 得 + Complement.',
    formula: 'Verb/Adj + 得 + Complement (adjective/clause)',
    examples: [
      { sentence: '她唱歌唱得很好听。', explanation: 'She sings very beautifully. The verb 唱 is repeated because of the object 歌.' },
      { sentence: '他跑得很快。', explanation: 'He runs very fast. Simple degree complement with adjective.' },
      { sentence: '我累得说不出话来。', explanation: 'I am so tired that I cannot speak. Clause as complement.' },
    ],
    commonMistakes: [
      '❌ "她唱得歌很好" → ✅ "她唱歌唱得很好" — When there is an object, repeat the verb before 得.',
      '❌ "他跑很快得" → ✅ "他跑得很快" — 得 comes right after the verb, before the complement.',
    ],
    questions: [
      {
        id: 'zh_g3q1',
        question: '他说中文说___很流利。',
        options: ['得', '的', '地', '了'],
        correctAnswer: '得',
        explanation: '得 is used for degree complements after a verb to describe how the action is done.',
      },
      {
        id: 'zh_g3q2',
        question: '她高兴___跳了起来。',
        options: ['得', '的', '地', '着'],
        correctAnswer: '得',
        explanation: 'Degree complement: so happy that she jumped up. 得 links the adjective to the result.',
      },
      {
        id: 'zh_g3q3',
        question: '这道菜做得___。',
        options: ['非常好吃', '非常好吃了', '很好吃的', '好吃很'],
        correctAnswer: '非常好吃',
        explanation: 'After 得, the complement is an adjective phrase describing the degree: 非常好吃 (extremely delicious).',
      },
    ],
    tags: ['complements', 'degree', 'HSK4', 'de-particle'],
  },
  {
    id: 'zh_g4',
    title: '结果补语 (Result complements)',
    level: 'B1',
    description: 'Expressing the result or outcome of an action',
    theory: 'Result complements (结果补语) are placed directly after the verb to indicate the outcome of an action. Common result complements include: 完 (finished), 到 (achieved/reached), 见 (perceived), 好 (done properly), 错 (wrong), 懂 (understood), 会 (learned). Unlike degree complements, result complements attach directly to the verb without 得.',
    formula: 'Verb + Result Complement (+ 了)',
    examples: [
      { sentence: '我听懂了老师说的话。', explanation: 'I understood what the teacher said. 懂 is the result complement meaning "understood".' },
      { sentence: '作业写完了吗？', explanation: 'Is the homework finished? 完 indicates completion.' },
      { sentence: '你找到钥匙了吗？', explanation: 'Did you find the keys? 到 indicates the goal was reached.' },
    ],
    commonMistakes: [
      '❌ "我看了见他" → ✅ "我看见了他" — The result complement comes directly after the verb, before 了.',
      '❌ "我听得懂了" when meaning simple past → ✅ "我听懂了" — 得 makes it a potential complement, not a result complement.',
    ],
    questions: [
      {
        id: 'zh_g4q1',
        question: '这本书我看___了。',
        options: ['完', '得', '着', '过完'],
        correctAnswer: '完',
        explanation: '完 as a result complement means the action (reading) was completed.',
      },
      {
        id: 'zh_g4q2',
        question: '你听___老师说什么了吗？',
        options: ['见', '到', '清', '清楚'],
        correctAnswer: '清楚',
        explanation: '听清楚 means "heard clearly". 清楚 is a result complement indicating clarity.',
      },
      {
        id: 'zh_g4q3',
        question: '我学___开车了。',
        options: ['会', '好', '得', '过'],
        correctAnswer: '会',
        explanation: '学会 means "learned (and now can do it)". 会 indicates the skill was acquired.',
      },
    ],
    tags: ['complements', 'result', 'HSK4', 'verb-complement'],
  },
  {
    id: 'zh_g5',
    title: '量词 (Measure words/classifiers)',
    level: 'B1',
    description: 'Correct use of measure words and classifiers with nouns',
    theory: 'Chinese requires measure words (量词) between a number or demonstrative and a noun. Different nouns use different classifiers based on shape, category, or convention. 个 (gè) is the most general classifier, but using the correct specific classifier is important for fluency. Common classifiers: 本 (books), 张 (flat objects), 条 (long/thin objects), 只 (small animals), 件 (clothing/matters), 把 (objects with handles), 位 (polite for people), 辆 (vehicles).',
    formula: 'Number/Demonstrative + Measure Word + Noun',
    examples: [
      { sentence: '一本书', explanation: 'One book. 本 is the classifier for bound volumes.' },
      { sentence: '两条鱼', explanation: 'Two fish. 条 is used for long, thin things including fish.' },
      { sentence: '三位老师', explanation: 'Three teachers. 位 is the polite classifier for people.' },
    ],
    commonMistakes: [
      '❌ "一个书" → ✅ "一本书" — Books use 本, not the generic 个.',
      '❌ "两个车" → ✅ "两辆车" — Vehicles use 辆.',
      '❌ "三个纸" → ✅ "三张纸" — Flat objects like paper use 张.',
    ],
    questions: [
      {
        id: 'zh_g5q1',
        question: '我买了三___衬衫。',
        options: ['件', '条', '个', '张'],
        correctAnswer: '件',
        explanation: '件 is the classifier for clothing items like shirts.',
      },
      {
        id: 'zh_g5q2',
        question: '桌子上有一___报纸。',
        options: ['份', '本', '条', '个'],
        correctAnswer: '份',
        explanation: '份 is the classifier for newspapers, documents, and copies.',
      },
      {
        id: 'zh_g5q3',
        question: '他养了两___猫。',
        options: ['只', '条', '个', '头'],
        correctAnswer: '只',
        explanation: '只 is the classifier for small animals like cats, birds, and insects.',
      },
      {
        id: 'zh_g5q4',
        question: '请给我一___水。',
        options: ['杯', '个', '瓶', '碗'],
        correctAnswer: '杯',
        explanation: '杯 (cup/glass) is used when asking for a cup of water. 瓶 would mean a bottle.',
      },
    ],
    tags: ['classifiers', 'measure-words', 'HSK4', 'nouns'],
  },
  // ═══ B2 / HSK5 ═══
  {
    id: 'zh_g6',
    title: '关联词 (Correlative conjunctions)',
    level: 'B2',
    description: 'Paired connectors linking clauses in complex sentences',
    theory: 'Correlative conjunctions (关联词) are paired words that connect two clauses to express relationships such as addition, contrast, condition, or cause-effect. Key pairs include: 不但...而且 (not only...but also), 虽然...但是 (although...but), 因为...所以 (because...therefore), 如果...就 (if...then), 只有...才 (only if...then), 既然...就 (since...then), 不管...都 (regardless...all). Both parts of the pair are typically required.',
    formula: 'Conjunction₁ + Clause₁, + Conjunction₂ + Clause₂',
    examples: [
      { sentence: '虽然他很累，但是他还是坚持跑完了。', explanation: 'Although he was very tired, he still persisted and finished running.' },
      { sentence: '不但价格便宜，而且质量也很好。', explanation: 'Not only is the price cheap, but the quality is also good.' },
      { sentence: '如果明天下雨，我们就不去了。', explanation: 'If it rains tomorrow, we will not go.' },
    ],
    commonMistakes: [
      '❌ "虽然他很累，所以他休息了" → ✅ "虽然...但是" or "因为...所以" — Do not mix pairs.',
      '❌ "因为下雨但是我没去" → ✅ "因为下雨所以我没去" — 因为 pairs with 所以, not 但是.',
    ],
    questions: [
      {
        id: 'zh_g6q1',
        question: '___他不同意，我们___要这样做。',
        options: ['即使...也', '因为...所以', '虽然...但是', '不但...而且'],
        correctAnswer: '即使...也',
        explanation: '"Even if he disagrees, we still have to do it." 即使...也 expresses concession with determination.',
      },
      {
        id: 'zh_g6q2',
        question: '___你努力学习，___能取得好成绩。',
        options: ['只有...才', '不但...而且', '虽然...但是', '因为...所以'],
        correctAnswer: '只有...才',
        explanation: '"Only if you study hard can you achieve good results." 只有...才 expresses a necessary condition.',
      },
      {
        id: 'zh_g6q3',
        question: '他___会说英语，___会说法语。',
        options: ['不但...而且', '虽然...但是', '如果...就', '只有...才'],
        correctAnswer: '不但...而且',
        explanation: '"He not only speaks English, but also speaks French." Progressive/additive relationship.',
      },
    ],
    tags: ['conjunctions', 'complex-sentences', 'HSK5', 'connectors'],
  },
  {
    id: 'zh_g7',
    title: '复合补语 (Complex complements)',
    level: 'B2',
    description: 'Potential complements and directional complements in Mandarin',
    theory: 'Complex complements include potential complements (可能补语) and compound directional complements (趋向补语). Potential complements use 得 (can) or 不 (cannot) between the verb and the result/directional complement to express ability or possibility: V得C (can do) vs V不C (cannot do). Compound directional complements combine simple directional words: 上来, 下去, 出来, 回去, 过来, 起来, etc.',
    formula: 'Potential: V + 得/不 + Complement | Directional: V + Direction₁ + Direction₂',
    examples: [
      { sentence: '这个箱子太重，我搬不动。', explanation: 'This box is too heavy, I cannot move it. 不动 = unable to move.' },
      { sentence: '你听得懂中文吗？', explanation: 'Can you understand Chinese? 得懂 = able to understand.' },
      { sentence: '他从楼上跑下来了。', explanation: 'He ran down from upstairs. 下来 = downward toward speaker.' },
    ],
    commonMistakes: [
      '❌ "我不能搬动" for inability → ✅ "我搬不动" — Use potential complement, not 不能, for inherent inability.',
      '❌ "走出去来" → ✅ "走出来" or "走出去" — Direction₂ is either 来 (toward speaker) or 去 (away), not both.',
    ],
    questions: [
      {
        id: 'zh_g7q1',
        question: '这首歌太难了，我唱___。',
        options: ['不好', '不得', '得不好', '没好'],
        correctAnswer: '不好',
        explanation: 'Potential complement negative form: 唱不好 means "cannot sing well". V + 不 + complement.',
      },
      {
        id: 'zh_g7q2',
        question: '快把行李拿___吧！',
        options: ['出来', '出去来', '来出', '了来'],
        correctAnswer: '出来',
        explanation: '出来 is a compound directional complement meaning "out (toward the speaker)".',
      },
      {
        id: 'zh_g7q3',
        question: '这么多菜，你吃___吗？',
        options: ['得完', '得了完', '完得', '了完'],
        correctAnswer: '得完',
        explanation: 'Potential complement positive form: 吃得完 means "can finish eating". V + 得 + complement.',
      },
    ],
    tags: ['complements', 'potential', 'directional', 'HSK5'],
  },
  {
    id: 'zh_g8',
    title: '比较句型 (Comparison patterns)',
    level: 'B2',
    description: 'Expressing comparisons using 比, 没有, and 跟...一样',
    theory: 'Chinese has several comparison structures. 比 (bǐ) for "more than": A 比 B + Adj. 没有 (méiyǒu) for "not as...as": A 没有 B + (那么) + Adj. 跟...一样 (gēn...yíyàng) for equality: A 跟 B 一样 + Adj. 不如 (bùrú) for "not as good as". Specific differences use 比 with a quantified amount: A 比 B + Adj + amount.',
    formula: 'A 比 B + Adj | A 没有 B (那么) Adj | A 跟 B 一样 Adj',
    examples: [
      { sentence: '他比我高五厘米。', explanation: 'He is five centimeters taller than me. Specific difference after adjective.' },
      { sentence: '今天没有昨天那么冷。', explanation: 'Today is not as cold as yesterday. 没有...那么 structure.' },
      { sentence: '这个跟那个一样贵。', explanation: 'This one is as expensive as that one. Equality comparison.' },
    ],
    commonMistakes: [
      '❌ "他比我很高" → ✅ "他比我高很多" — Cannot use 很 directly after adjective in 比 sentences; use 多, 得多, or a specific amount.',
      '❌ "他比我不高" → ✅ "他没有我高" — Negate comparisons with 没有, not 不 in a 比 sentence.',
    ],
    questions: [
      {
        id: 'zh_g8q1',
        question: '上海___北京大。',
        options: ['比', '没有', '跟', '不如'],
        correctAnswer: '没有',
        explanation: 'Shanghai is not as big as Beijing. 没有 is used for "not as...as" comparisons.',
      },
      {
        id: 'zh_g8q2',
        question: '我的手机跟你的___。',
        options: ['一样', '比', '没有', '不如'],
        correctAnswer: '一样',
        explanation: '跟...一样 expresses equality: my phone is the same as yours.',
      },
      {
        id: 'zh_g8q3',
        question: '他跑得比我___。',
        options: ['快', '很快', '快很', '更很快'],
        correctAnswer: '快',
        explanation: 'In 比 comparisons, the adjective stands alone without 很. "He runs faster than me."',
      },
    ],
    tags: ['comparison', 'bi', 'HSK5', 'adjectives'],
  },
  {
    id: 'zh_g9',
    title: '成语运用 (Chengyu usage)',
    level: 'B2',
    description: 'Correct application of four-character Chinese idioms',
    theory: 'Chengyu (成语) are fixed four-character expressions, mostly derived from classical Chinese stories, literature, or history. They function as compact units with meanings that often cannot be deduced from individual characters. Correct usage requires understanding the precise meaning, connotation (positive, negative, or neutral), and grammatical role (adjective, adverb, verb, etc.). Common HSK5 chengyu include: 自言自语 (talk to oneself), 半途而废 (give up halfway), 一举两得 (kill two birds with one stone), 爱不释手 (love it so much one cannot let go).',
    formula: 'Four-character fixed expression used as a grammatical unit',
    examples: [
      { sentence: '做事不能半途而废。', explanation: 'You cannot give up halfway when doing things. 半途而废 acts as the predicate.' },
      { sentence: '这个方法一举两得。', explanation: 'This method achieves two goals at once. Literally: one action, two gains.' },
      { sentence: '她对那本小说爱不释手。', explanation: 'She could not put that novel down. Expresses deep fondness.' },
    ],
    commonMistakes: [
      '❌ Using 雪中送炭 (giving charcoal in snow = timely help) to describe unhelpful actions — it only applies to help given in times of need.',
      '❌ Using 对牛弹琴 (playing the lute to a cow) as a compliment — it criticizes speaking to an unappreciative audience.',
    ],
    questions: [
      {
        id: 'zh_g9q1',
        question: 'Which chengyu means "to give up halfway"?',
        options: ['半途而废', '一举两得', '自言自语', '爱不释手'],
        correctAnswer: '半途而废',
        explanation: '半途而废: 半途 (halfway) + 而废 (and abandon). It describes quitting before completion.',
      },
      {
        id: 'zh_g9q2',
        question: '他一个人在那儿___。',
        options: ['自言自语', '半途而废', '一举两得', '雪中送炭'],
        correctAnswer: '自言自语',
        explanation: '自言自语 means "talking to oneself". He was talking to himself over there.',
      },
      {
        id: 'zh_g9q3',
        question: '这个计划既能省钱又能省时间，真是___。',
        options: ['一举两得', '半途而废', '自言自语', '对牛弹琴'],
        correctAnswer: '一举两得',
        explanation: 'The plan saves both money and time — "one action, two gains" fits perfectly.',
      },
    ],
    tags: ['chengyu', 'idioms', 'HSK5', 'vocabulary'],
  },
  {
    id: 'zh_g10',
    title: '修辞句式 (Rhetorical patterns)',
    level: 'B2',
    description: 'Rhetorical questions and emphasis patterns in Chinese',
    theory: 'Chinese rhetorical patterns include rhetorical questions (反问句) that state opinions emphatically, and emphasis constructions. Key patterns: 难道...吗？(Could it be that...? — implying "of course not"), 不是...吗？(Isn\'t it...? — implying "obviously yes"), 连...都/也 (even... — emphasis on extremes), 是...的 (it is...that — cleft sentence for emphasis on time, place, manner). Rhetorical questions do not expect an answer; they express strong assertions.',
    formula: '难道 + Statement + 吗？| 连 + Extreme + 都/也 + VP | 是...的',
    examples: [
      { sentence: '难道你不知道吗？', explanation: 'Don\'t you know? (Implies: You obviously should know!)' },
      { sentence: '连小孩子都知道这个道理。', explanation: 'Even children know this principle. 连...都 emphasizes how basic it is.' },
      { sentence: '我是昨天来的。', explanation: 'It was yesterday that I came. 是...的 emphasizes the time.' },
    ],
    commonMistakes: [
      '❌ "难道你知道吗？" to genuinely ask → ✅ Use 难道 only for rhetorical emphasis, not real questions.',
      '❌ "连他都不会也" → ✅ "连他都不会" or "连他也不会" — Use 都 or 也, not both together.',
    ],
    questions: [
      {
        id: 'zh_g10q1',
        question: '___这么简单的题你___不会做？',
        options: ['难道...也', '因为...所以', '虽然...但是', '不但...而且'],
        correctAnswer: '难道...也',
        explanation: 'Rhetorical question expressing surprise: "Could it really be that you cannot even do such a simple problem?"',
      },
      {
        id: 'zh_g10q2',
        question: '___三岁的小孩___能做到。',
        options: ['连...都', '从...到', '把...给', '被...所'],
        correctAnswer: '连...都',
        explanation: '"Even a three-year-old can do it." 连...都 emphasizes that the extreme case is true.',
      },
      {
        id: 'zh_g10q3',
        question: '她是在北京___大学的。',
        options: ['上的', '上了', '上', '上着'],
        correctAnswer: '上的',
        explanation: '是...的 construction emphasizes where she attended university. 的 closes the emphasis.',
      },
    ],
    tags: ['rhetoric', 'emphasis', 'HSK5', 'questions'],
  },
  // ═══ C1 / HSK6 ═══
  {
    id: 'zh_g11',
    title: '书面语 (Formal written Chinese)',
    level: 'C1',
    description: 'Distinguishing literary and colloquial expressions in written Chinese',
    theory: 'Written Chinese (书面语) differs significantly from spoken Chinese (口语) in vocabulary, grammar, and style. Formal writing uses classical-influenced words, compressed structures, and avoids colloquial fillers. Key substitutions: 然而 instead of 但是 (however), 因此 instead of 所以 (therefore), 倘若 instead of 如果 (if), 此 instead of 这 (this), 其 instead of 他的 (his/its), 予以 instead of 给 (to give), 亦 instead of 也 (also), 及 instead of 和 (and). Formal writing also favors four-character phrases and parallel structures.',
    formula: 'Colloquial form → Written/Literary equivalent',
    examples: [
      { sentence: '此项政策旨在促进经济发展。', explanation: 'This policy aims to promote economic development. 此 (this), 旨在 (aims to) are literary.' },
      { sentence: '然而，问题并未得到解决。', explanation: 'However, the problem has not been resolved. 然而 and 并未 are formal alternatives.' },
      { sentence: '倘若条件允许，我们亦可考虑此方案。', explanation: 'If conditions permit, we may also consider this plan. 倘若, 亦, 此 are written-register words.' },
    ],
    commonMistakes: [
      '❌ Using 然后 (then, colloquial) in formal essays → ✅ Use 随后, 继而, or 其后.',
      '❌ Mixing registers: "这个问题很重要，所以咱们得好好想想" → ✅ "该问题至关重要，因此需慎重考虑。"',
    ],
    questions: [
      {
        id: 'zh_g11q1',
        question: 'Which is the formal written equivalent of 但是?',
        options: ['然而', '然后', '不过', '可是'],
        correctAnswer: '然而',
        explanation: '然而 is the literary/formal equivalent of 但是 (but/however). 不过 and 可是 are also colloquial.',
      },
      {
        id: 'zh_g11q2',
        question: '___条件成熟，可___实施该方案。',
        options: ['倘若...予以', '如果...给', '要是...来', '假如...弄'],
        correctAnswer: '倘若...予以',
        explanation: '倘若 (if, formal) and 予以 (to give/carry out, formal) are appropriate for written register.',
      },
      {
        id: 'zh_g11q3',
        question: 'Which sentence uses appropriate formal written Chinese?',
        options: [
          '此举旨在提升公众意识。',
          '这个做法是为了让大家知道。',
          '这样做就是想让人们了解一下。',
          '这么干是为了让大伙儿明白。',
        ],
        correctAnswer: '此举旨在提升公众意识。',
        explanation: '此举 (this measure), 旨在 (aims to), 提升 (elevate), 公众意识 (public awareness) are all formal register.',
      },
    ],
    tags: ['register', 'formal-writing', 'HSK6', 'literary'],
  },
  {
    id: 'zh_g12',
    title: '双重否定 (Double negation)',
    level: 'C1',
    description: 'Using double negatives for emphatic affirmation in Chinese',
    theory: 'Double negation (双重否定) in Chinese uses two negative elements to create a strong affirmative meaning. Unlike English, double negation in Chinese is standard and emphatic, not informal. Key patterns: 不得不 (have no choice but to), 不能不 (cannot not = must), 没有...不 (there is nothing that...not = everything), 非...不可 (must, absolutely have to), 无不 (without exception, all). These constructions convey stronger assertion than simple affirmatives.',
    formula: '不得不 + VP | 不能不 + VP | 没有...不... | 非...不可',
    examples: [
      { sentence: '面对这种情况，我们不得不采取措施。', explanation: 'Facing this situation, we have no choice but to take measures.' },
      { sentence: '他的表演，没有人不称赞。', explanation: 'There is no one who does not praise his performance. (= Everyone praises it.)' },
      { sentence: '这件事非做不可。', explanation: 'This thing absolutely must be done. 非...不可 = must without exception.' },
    ],
    commonMistakes: [
      '❌ Confusing 不得不 (must/no choice) with 不得 (must not/forbidden) — they have opposite meanings.',
      '❌ "没有不人喜欢" → ✅ "没有人不喜欢" — The noun goes between 没有 and 不.',
    ],
    questions: [
      {
        id: 'zh_g12q1',
        question: '时间紧迫，我们___加快速度。',
        options: ['不得不', '不得', '不用', '不必'],
        correctAnswer: '不得不',
        explanation: '不得不 means "have no choice but to". Time is pressing, so we must speed up.',
      },
      {
        id: 'zh_g12q2',
        question: '这件事___完成___。',
        options: ['非...不可', '不...不行', '没...不了', '无...不能'],
        correctAnswer: '非...不可',
        explanation: '非...不可 means "must absolutely". This matter must be completed.',
      },
      {
        id: 'zh_g12q3',
        question: '他的善良，认识他的人___称赞。',
        options: ['无不', '不不', '没不', '不无'],
        correctAnswer: '无不',
        explanation: '无不 means "without exception, all". Everyone who knows him praises his kindness.',
      },
    ],
    tags: ['double-negation', 'emphasis', 'HSK6', 'advanced-grammar'],
  },
  {
    id: 'zh_g13',
    title: '让步复句 (Concessive complex sentences)',
    level: 'C1',
    description: 'Complex sentences expressing concession with 即使, 哪怕, 纵然',
    theory: 'Concessive complex sentences (让步复句) acknowledge a condition or fact in one clause while asserting an unexpected or contrary result in the other. Key patterns: 即使/就算...也 (even if...still), 哪怕...也 (even if/no matter...still), 纵然/纵使...也 (even though...still, literary), 尽管...还是 (despite...still). The concessive clause states a hypothetical or real condition; the main clause states that the result holds regardless. 即使 is for hypothetical situations; 尽管 is for acknowledged facts.',
    formula: '即使/哪怕/纵然 + Condition, + 也/还是 + Result',
    examples: [
      { sentence: '即使明天下雨，我也要去。', explanation: 'Even if it rains tomorrow, I will still go. Hypothetical concession.' },
      { sentence: '哪怕只有一点希望，我们也不能放弃。', explanation: 'Even if there is only a sliver of hope, we cannot give up.' },
      { sentence: '尽管他很努力，成绩还是不理想。', explanation: 'Despite his hard work, his results are still unsatisfactory. Factual concession.' },
    ],
    commonMistakes: [
      '❌ "即使他努力了，但是成绩不好" → ✅ "即使...也" — 即使 pairs with 也, not 但是.',
      '❌ Using 即使 for known facts → ✅ Use 尽管 for facts already true; 即使 is for hypothetical conditions.',
    ],
    questions: [
      {
        id: 'zh_g13q1',
        question: '___困难再大，我们___要坚持下去。',
        options: ['哪怕...也', '因为...所以', '虽然...但是', '不但...而且'],
        correctAnswer: '哪怕...也',
        explanation: '"Even if the difficulties are great, we still must persist." 哪怕...也 for hypothetical concession.',
      },
      {
        id: 'zh_g13q2',
        question: '___他已经道歉了，她___没有原谅他。',
        options: ['尽管...还是', '即使...也', '哪怕...也', '只要...就'],
        correctAnswer: '尽管...还是',
        explanation: 'He has already apologized (a fact), so 尽管...还是 is correct for factual concession.',
      },
      {
        id: 'zh_g13q3',
        question: '___天塌下来，我___不会改变主意。',
        options: ['即使...也', '尽管...还是', '因为...所以', '只有...才'],
        correctAnswer: '即使...也',
        explanation: '"Even if the sky falls" is a hypothetical extreme. 即使...也 fits hypothetical concession.',
      },
    ],
    tags: ['concession', 'complex-sentences', 'HSK6', 'conjunctions'],
  },
  {
    id: 'zh_g14',
    title: '古文结构 (Classical Chinese structures)',
    level: 'C1',
    description: 'Classical Chinese patterns commonly used in modern Chinese',
    theory: 'Many classical Chinese (文言文) structures survive in modern Mandarin, especially in formal writing, set phrases, and chengyu. Key patterns include: 以 as a preposition meaning "with/by/using" (以德服人 — win people over with virtue), 之 as a possessive or structural particle (百分之十 — ten percent), 而 as a conjunction meaning "and/but/yet" (学而时习之 — study and review regularly), 所 as a nominalizer (所见所闻 — what one sees and hears), 于 as a preposition meaning "at/in/to" (生于北京 — born in Beijing). Understanding these aids reading formal texts and using idiomatic expressions.',
    formula: '以 + N + V | N + 之 + N | V + 而 + V | 所 + V | V + 于 + N',
    examples: [
      { sentence: '以理服人', explanation: 'Convince people with reason. 以 = with/using (classical preposition).' },
      { sentence: '三分之一', explanation: 'One-third. 之 functions as a classical possessive particle in fractions.' },
      { sentence: '不劳而获', explanation: 'To gain without working. 而 = yet/but (classical conjunction).' },
    ],
    commonMistakes: [
      '❌ Using 以 as "already" (confusing with 已) → ✅ 以 means "with/by"; 已 means "already".',
      '❌ "百分的十" → ✅ "百分之十" — Fractions and percentages require the classical 之, not modern 的.',
    ],
    questions: [
      {
        id: 'zh_g14q1',
        question: '百分___二十的学生通过了考试。',
        options: ['之', '的', '而', '以'],
        correctAnswer: '之',
        explanation: 'Percentages use the classical particle 之: 百分之二十 = 20 percent.',
      },
      {
        id: 'zh_g14q2',
        question: 'Which phrase uses a classical Chinese structure?',
        options: ['以德报怨', '用好的报答坏的', '拿道德还恩', '靠品德回报'],
        correctAnswer: '以德报怨',
        explanation: '以德报怨 (repay grievance with virtue) uses classical 以 (with) in a four-character set phrase.',
      },
      {
        id: 'zh_g14q3',
        question: '取___所需',
        options: ['其', '他的', '那个', '这的'],
        correctAnswer: '其',
        explanation: '取其所需 means "take what one needs." 其 is a classical pronoun meaning "his/its/their."',
      },
    ],
    tags: ['classical', 'literary', 'HSK6', 'wenyan'],
  },
  {
    id: 'zh_g15',
    title: '公文语体 (Official document register)',
    level: 'C1',
    description: 'Formal and bureaucratic language patterns used in official documents',
    theory: 'Official document Chinese (公文语体) is a highly formal register used in government notices, legal texts, corporate communications, and official reports. It features fixed phrases, formal verbs, and standardized structures. Key vocabulary: 兹 (hereby), 拟 (to plan/propose), 予以 (to give/carry out), 鉴于 (in view of), 特此 (hereby, at the end), 责成 (to instruct/charge with), 函告 (to notify by letter), 批复 (to reply to a request for instructions), 遵照 (in accordance with), 贯彻 (to implement/carry out). Sentences tend to be long, use passive-like constructions, and avoid personal pronouns.',
    formula: '兹 + VP | 鉴于 + Reason, + 特/拟 + Action | 特此 + VP',
    examples: [
      { sentence: '兹定于十月一日召开全体会议。', explanation: 'It is hereby decided to hold a plenary meeting on October 1st. 兹 = hereby.' },
      { sentence: '鉴于上述情况，拟采取以下措施。', explanation: 'In view of the above situation, it is proposed to adopt the following measures.' },
      { sentence: '特此通知。', explanation: 'Hereby notified. A standard closing phrase in official notices.' },
    ],
    commonMistakes: [
      '❌ Using 兹 in casual speech or informal writing — it is exclusively for official documents.',
      '❌ "因为上面说的情况" → ✅ "鉴于上述情况" — Official register requires formal phrasing.',
    ],
    questions: [
      {
        id: 'zh_g15q1',
        question: '___定于本月十五日举行开幕式。',
        options: ['兹', '现在', '今天', '这里'],
        correctAnswer: '兹',
        explanation: '兹 (hereby) is the standard official-document word to introduce a decision or announcement.',
      },
      {
        id: 'zh_g15q2',
        question: '___上述原因，决定暂停该项目。',
        options: ['鉴于', '因为', '由于', '所以'],
        correctAnswer: '鉴于',
        explanation: '鉴于 (in view of) is the formal/official equivalent of 因为 or 由于 in government documents.',
      },
      {
        id: 'zh_g15q3',
        question: 'Which is the correct official closing phrase for a notice?',
        options: ['特此通知', '就这样通知大家', '跟大家说一下', '告诉你们了'],
        correctAnswer: '特此通知',
        explanation: '特此通知 (hereby notified) is the standard formal closing used in official notices and announcements.',
      },
    ],
    tags: ['official', 'bureaucratic', 'HSK6', 'formal-register'],
  },
];
