import type { GrammarTopic } from './grammarBank';

export const grammarBankJa: GrammarTopic[] = [
  // ═══ A1 ═══
  {
    id: 'ja_g1', title: 'です/ます形 (Desu/Masu Polite Form)', level: 'A1',
    description: 'Using polite speech forms in Japanese conversation and formal settings',
    theory: 'Japanese has distinct speech levels, and the です/ます form is the foundation of polite speech. です (desu) functions as a copula — it links a subject to a noun or na-adjective, similar to "is/am/are" in English. ます (masu) is the polite ending attached to the stem of a verb to elevate the formality of the sentence. You should use です/ます form when speaking to strangers, elders, colleagues, or in any situation that calls for politeness. Mixing polite and plain forms within the same sentence is considered grammatically awkward and socially inappropriate. Note that na-adjectives require です after them (e.g., 静かです), while i-adjectives can directly take です without modification (e.g., 高いです).',
    formula: 'Noun + です / Verb-stem + ます',
    examples: [
      { sentence: '私は学生です。', explanation: '"I am a student." — Noun + です links the subject to a noun.' },
      { sentence: '毎日勉強します。', explanation: '"I study every day." — Verb stem 勉強し + ます creates polite present tense.' },
      { sentence: 'これはペンです。', explanation: '"This is a pen." — Demonstrative + noun + です for identification.' },
      { sentence: '明日行きます。', explanation: '"I will go tomorrow." — Verb stem 行き + ます for polite future/present.' },
    ],
    commonMistakes: [
      '❌ Mixing plain and polite forms in the same sentence: "私は学生だ。明日行きます。" → ✅ Keep consistent: "私は学生です。明日行きます。"',
      '❌ Forgetting です after na-adjectives: "ここは静か。" → ✅ "ここは静かです。"',
    ],
    questions: [
      {
        id: 'ja_g1q1',
        question: '「私は先生___。」に入る正しい言葉は？',
        options: ['だ', 'です', 'ます', 'である'],
        correctAnswer: 'です',
        explanation: '名詞の後にはです を使って丁寧な文を作ります。「私は先生です」が正しい丁寧形です。',
      },
      {
        id: 'ja_g1q2',
        question: '「毎朝コーヒーを飲み___。」に入る正しい言葉は？',
        options: ['る', 'ます', 'です', 'た'],
        correctAnswer: 'ます',
        explanation: '動詞の語幹「飲み」の後に「ます」を付けて丁寧形にします。',
      },
      {
        id: 'ja_g1q3',
        question: '次のうち、正しい丁寧な文はどれですか？',
        options: [
          '私は日本人だ。',
          '私は日本人です。',
          '私は日本人である。',
          '私は日本人じゃ。',
        ],
        correctAnswer: '私は日本人です。',
        explanation: '「です」を使った文が標準的な丁寧形です。「だ」は普通体、「である」は書き言葉の硬い表現です。',
      },
    ],
    tags: ['grammar', 'JLPT-N5', 'polite-form', 'desu-masu'],
  },
  {
    id: 'ja_g2', title: '助詞 (Particles)', level: 'A1',
    description: 'Understanding and using Japanese grammatical particles to mark sentence roles',
    theory: 'Particles are small words placed after nouns, verbs, or phrases to indicate their grammatical function in a sentence. は (wa) marks the topic of conversation — the thing being talked about. が (ga) marks the grammatical subject, often introducing new information or emphasizing who/what does something. を (o) marks the direct object of a transitive verb. に (ni) indicates a destination, point in time, or indirect object. で (de) marks the location where an action takes place or the means/tool used. へ (e) indicates the direction of movement, similar to に but more about the direction than the destination. と (to) means "and" when listing nouns or "with" when indicating companionship. から (kara) means "from" (starting point in time or space), and まで (made) means "until" or "up to."',
    examples: [
      { sentence: '私は学生です。', explanation: 'は marks "I" as the topic of the sentence.' },
      { sentence: '猫が好きです。', explanation: 'が marks "cats" as the subject of the predicate "like."' },
      { sentence: '本を読みます。', explanation: 'を marks "book" as the direct object of "read."' },
      { sentence: '学校に行きます。', explanation: 'に marks "school" as the destination of "go."' },
      { sentence: '図書館で勉強します。', explanation: 'で marks "library" as the location where the action "study" takes place.' },
      { sentence: '東京へ行きます。', explanation: 'へ indicates the direction of movement toward Tokyo.' },
      { sentence: '友達と映画を見ます。', explanation: 'と means "with" — watching a movie with a friend.' },
      { sentence: '9時から5時まで働きます。', explanation: 'から (from) and まで (until) mark the time range of working.' },
    ],
    commonMistakes: [
      '❌ Confusing は and が: "誰は来ましたか？" → ✅ "誰が来ましたか？" (Use が with question words like 誰, 何.)',
      '❌ Using を instead of に for location of existence: "部屋をいます" → ✅ "部屋にいます" (に marks the location where something exists.)',
    ],
    questions: [
      {
        id: 'ja_g2q1',
        question: '「東京___住んでいます。」に入る正しい助詞は？',
        options: ['を', 'に', 'で', 'が'],
        correctAnswer: 'に',
        explanation: '「住む」は存在・居場所を示す動詞なので、場所を示す助詞「に」を使います。',
      },
      {
        id: 'ja_g2q2',
        question: '「バス___学校に行きます。」に入る正しい助詞は？',
        options: ['に', 'を', 'で', 'が'],
        correctAnswer: 'で',
        explanation: '「で」は手段・方法を表します。バスという手段で学校に行くという意味です。',
      },
      {
        id: 'ja_g2q3',
        question: '「誰___来ましたか？」に入る正しい助詞は？',
        options: ['は', 'が', 'を', 'に'],
        correctAnswer: 'が',
        explanation: '疑問詞（誰、何など）が主語の場合は「が」を使います。「は」は不自然です。',
      },
    ],
    tags: ['grammar', 'JLPT-N5', 'particles'],
  },
  {
    id: 'ja_g3', title: 'て形 (Te-form)', level: 'A1',
    description: 'Conjugating verbs into the te-form and using it for requests, sequential actions, and ongoing states',
    theory: 'The te-form is one of the most versatile and important verb conjugations in Japanese. For u-verbs (godan), the ending changes according to the final kana: く→いて (書く→書いて), ぐ→いで (泳ぐ→泳いで), す→して (話す→話して), む/ぶ/ぬ→んで (読む→読んで, 遊ぶ→遊んで, 死ぬ→死んで), and る/う/つ→って (取る→取って, 買う→買って, 待つ→待って). For ru-verbs (ichidan), simply drop る and add て (食べる→食べて, 見る→見て). The two main irregular verbs are する→して and くる→きて. Note that 行く is an exception among u-verbs: 行く→行って (not 行いて). The te-form has many uses: adding ください makes a polite request (食べてください = "please eat"), chaining te-forms connects sequential actions (朝起きて歯を磨いて学校に行きます = "I wake up, brush my teeth, and go to school"), and adding いる creates the progressive form (食べている = "is eating").',
    formula: 'Verb te-form + ください (request) / Verb て + Verb (sequential)',
    examples: [
      { sentence: '食べてください。', explanation: '"Please eat." — Te-form + ください for a polite request.' },
      { sentence: '本を読んで寝ます。', explanation: '"I read a book and then sleep." — Te-form connects sequential actions.' },
      { sentence: '東京に行って買い物をしました。', explanation: '"I went to Tokyo and did some shopping." — Sequential past actions.' },
    ],
    commonMistakes: [
      '❌ Wrong te-form for u-verbs ending in る: "帰るて" → ✅ "帰って" (帰る is an u-verb, so る→って; be careful to distinguish from ru-verbs like 食べる→食べて.)',
    ],
    questions: [
      {
        id: 'ja_g3q1',
        question: '「読む」のて形は？',
        options: ['読みて', '読んで', '読って', '読して'],
        correctAnswer: '読んで',
        explanation: '「む」で終わる五段動詞は、む→んで と変化します。読む→読んで。',
      },
      {
        id: 'ja_g3q2',
        question: '「ここに座っ___。」リクエストを完成させてください。',
        options: ['てます', 'てください', 'てだ', 'てある'],
        correctAnswer: 'てください',
        explanation: 'て形 + ください で丁寧な依頼を表します。「座ってください」＝「Please sit here.」',
      },
      {
        id: 'ja_g3q3',
        question: '「する」のて形は？',
        options: ['すて', 'して', 'さて', 'すって'],
        correctAnswer: 'して',
        explanation: '「する」は不規則動詞で、て形は「して」です。',
      },
    ],
    tags: ['grammar', 'JLPT-N5', 'te-form', 'conjugation'],
  },
  {
    id: 'ja_g4', title: '過去形 (Past Tense)', level: 'A1',
    description: 'Forming past tense sentences in both polite and plain speech styles',
    theory: 'Japanese past tense has two main registers: polite (丁寧体) and plain (普通体). In polite speech, the affirmative past is formed by replacing ます with ました (食べます→食べました), and the negative past is formed by replacing ません with ませんでした (食べません→食べませんでした). In plain speech, the affirmative past uses the た-form, which follows the same consonant-change rules as the te-form but ends in た/だ instead of て/で: 書く→書いた, 泳ぐ→泳いだ, 飲む→飲んだ, 待つ→待った, 食べる→食べた. The plain negative past uses なかった: 食べない→食べなかった, 行かない→行かなかった. For the copula です, the polite past is でした and the plain past is だった. Understanding both registers is essential for reading casual text and for expressing yourself properly in formal situations.',
    formula: 'Verb-stem + ました (polite past) / Verb た-form (plain past)',
    examples: [
      { sentence: '昨日映画を見ました。', explanation: '"I watched a movie yesterday." — Polite past: 見ます→見ました.' },
      { sentence: '朝ごはんを食べなかった。', explanation: '"I did not eat breakfast." — Plain negative past: 食べない→食べなかった.' },
      { sentence: '学校に行きませんでした。', explanation: '"I did not go to school." — Polite negative past: 行きません→行きませんでした.' },
    ],
    commonMistakes: [
      '❌ Confusing た-form conjugation with te-form: they follow the same pattern, but た-form ends in た/だ while te-form ends in て/で. 書く→書いた (past) vs 書いて (te-form).',
    ],
    questions: [
      {
        id: 'ja_g4q1',
        question: '「飲みます」の丁寧な過去形は？',
        options: ['飲みた', '飲みました', '飲んだ', '飲みませんでした'],
        correctAnswer: '飲みました',
        explanation: '丁寧な過去形は「ます」を「ました」に変えます。飲みます→飲みました。',
      },
      {
        id: 'ja_g4q2',
        question: '「行く」の普通体の過去形は？',
        options: ['行いた', '行った', '行きた', '行くた'],
        correctAnswer: '行った',
        explanation: '「行く」は特殊で、た形は「行った」になります（行いた ではありません）。',
      },
    ],
    tags: ['grammar', 'JLPT-N5', 'past-tense'],
  },
  {
    id: 'ja_g5', title: '形容詞の活用 (Adjective Conjugation)', level: 'A1',
    description: 'Conjugating i-adjectives and na-adjectives for negation, past, and negative past',
    theory: 'Japanese adjectives are divided into two groups: い-adjectives (i-adjectives) and な-adjectives (na-adjectives), and each group follows different conjugation rules. For い-adjectives, the basic pattern is: drop the final い and add くない for negative (高い→高くない = "not expensive"), かった for past (高い→高かった = "was expensive"), and くなかった for negative past (高い→高くなかった = "was not expensive"). For な-adjectives, add じゃない for negative (静かな→静かじゃない = "not quiet"), だった for past (静かな→静かだった = "was quiet"), and じゃなかった for negative past (静かな→静かじゃなかった = "was not quiet"). The most important exception is いい (good), which uses the stem よ- for all conjugated forms: よくない (not good), よかった (was good), よくなかった (was not good). Be careful not to say いくない or いかった. Another common pitfall is きれい (beautiful/clean) — despite ending in い, it is a な-adjective and conjugates as きれいじゃない, not きれくない.',
    formula: 'い-adj stem + くない/かった/くなかった | な-adj + じゃない/だった/じゃなかった',
    examples: [
      { sentence: '高い→高くない', explanation: 'い-adjective negative: drop い, add くない. "Not expensive."' },
      { sentence: '静かな→静かじゃない', explanation: 'な-adjective negative: add じゃない after the stem. "Not quiet."' },
      { sentence: 'いい→よかった', explanation: 'Irregular: いい uses the stem よ- for conjugation. "Was good."' },
      { sentence: '大きい→大きかった', explanation: 'い-adjective past: drop い, add かった. "Was big."' },
    ],
    commonMistakes: [
      '❌ Treating きれい as an i-adjective: "きれくない" → ✅ "きれいじゃない" (きれい is a na-adjective despite ending in い.)',
      '❌ Forgetting the irregular stem of いい: "いくない" or "いかった" → ✅ "よくない" / "よかった" (いい changes to よ- in all conjugated forms.)',
    ],
    questions: [
      {
        id: 'ja_g5q1',
        question: '「おいしい」の否定形は？',
        options: ['おいしいじゃない', 'おいしくない', 'おいしない', 'おいしじゃない'],
        correctAnswer: 'おいしくない',
        explanation: 'い-形容詞の否定形は「い」を取って「くない」を付けます。おいしい→おいしくない。',
      },
      {
        id: 'ja_g5q2',
        question: '「いい」の過去形は？',
        options: ['いかった', 'いいだった', 'よかった', 'よいだった'],
        correctAnswer: 'よかった',
        explanation: '「いい」は不規則で、活用するときは「よ」に変わります。いい→よかった。',
      },
      {
        id: 'ja_g5q3',
        question: '「きれい」の否定形は？',
        options: ['きれくない', 'きれいくない', 'きれいじゃない', 'きれいない'],
        correctAnswer: 'きれいじゃない',
        explanation: '「きれい」は「い」で終わりますが、な形容詞です。な形容詞の否定形は「じゃない」を付けます。',
      },
    ],
    tags: ['grammar', 'JLPT-N5', 'adjectives', 'conjugation'],
  },
  {
    id: 'ja_g6', title: '条件形 (Conditional forms)', level: 'A2',
    description: 'と・ば・たら・ならの使い分け',
    theory: '日本語には4つの条件形があります。「と」は自然な結果や習慣に使います。「ば」は仮定条件に使います。「たら」は完了した後の動作に使います。「なら」は話題に基づく条件に使います。',
    formula: 'V-る→V-れば | V-た→V-たら | V-る+と | N+なら',
    examples: [{ sentence: '春になると、桜が咲きます。', explanation: '「と」= 自然な結果（春→桜が咲く）' }],
    commonMistakes: ['❌ 「雨が降ると、傘を持っていきなさい」→ ✅ 「雨が降ったら」（命令文には「と」は使えない）'],
    questions: [
      { id: 'ja_g6q1', question: '春に___、花が咲きます。', options: ['なると', 'なれば', 'なったら', 'なるなら'], correctAnswer: 'なると', explanation: '自然な結果には「と」を使います。' },
      { id: 'ja_g6q2', question: '時間が___、映画を見に行きましょう。', options: ['あれば', 'あると', 'あるなら', 'あって'], correctAnswer: 'あれば', explanation: '仮定条件には「ば」を使います。' },
    ],
    tags: ['grammar', 'JLPT-N4', 'conditionals'],
  },
  {
    id: 'ja_g7', title: '受身形 (Passive voice)', level: 'A2',
    description: '受身形の作り方と使い方',
    theory: '受身形は「〜られる/される」で作ります。一段動詞：る→られる。五段動詞：う段→あ段+れる。する→される。来る→来られる。迷惑の受身（被害）は日本語独特の用法です。',
    formula: '一段: V-る→V-られる | 五段: V-う段→V-あ段+れる',
    examples: [{ sentence: '電車の中で足を踏まれました。', explanation: '迷惑の受身：被害を受けた経験を表す' }],
    commonMistakes: ['❌ 「先生に褒めされた」→ ✅ 「先生に褒められた」（褒める→褒められる）'],
    questions: [
      { id: 'ja_g7q1', question: '「食べる」の受身形は？', options: ['食べられる', '食べれる', '食べされる', '食べらせる'], correctAnswer: '食べられる', explanation: '一段動詞：る→られる。' },
      { id: 'ja_g7q2', question: '私は先生に___。(叱る)', options: ['叱られた', '叱された', '叱れた', '叱らせた'], correctAnswer: '叱られた', explanation: '五段動詞：叱る→叱られる→叱られた。' },
    ],
    tags: ['grammar', 'JLPT-N4', 'passive'],
  },
  {
    id: 'ja_g8', title: '授受表現 (Giving/Receiving)', level: 'A2',
    description: 'あげる・もらう・くれるの使い分け',
    theory: '「あげる」は自分が他人に与える時に使います。「もらう」は自分が他人から受ける時に使います。「くれる」は他人が自分（または身内）に与える時に使います。敬語形：差し上げる、いただく、くださる。',
    formula: 'A が B に あげる | A が B に/から もらう | B が A に くれる',
    examples: [{ sentence: '友達が誕生日プレゼントをくれました。', explanation: '友達→自分（くれる：他人が自分に与える）' }],
    commonMistakes: ['❌ 「先生が私にあげた」→ ✅ 「先生が私にくださった/くれた」（他人→自分は「くれる」）'],
    questions: [
      { id: 'ja_g8q1', question: '母が私にセーターを___。', options: ['くれました', 'あげました', 'もらいました', 'やりました'], correctAnswer: 'くれました', explanation: '母（他人）→私（自分）＝くれる。' },
      { id: 'ja_g8q2', question: '私は友達___本をもらいました。', options: ['に', 'から', 'を', 'で'], correctAnswer: 'から', explanation: 'もらう：〜から/に もらう。' },
    ],
    tags: ['grammar', 'JLPT-N4', 'giving-receiving'],
  },
  {
    id: 'ja_g9', title: '敬語 (Keigo: Honorific language)', level: 'B1',
    description: '尊敬語・謙譲語・丁寧語の基本',
    theory: '敬語には3種類あります。尊敬語は相手の動作を高める（いらっしゃる、おっしゃる）。謙譲語は自分の動作を低める（参る、申す）。丁寧語は「です・ます」で丁寧に話す。ビジネスや接客で必須です。',
    formula: '尊敬語: お+V-ます+になる | 謙譲語: お+V-ます+する',
    examples: [{ sentence: '社長はもうお帰りになりました。', explanation: '尊敬語：帰る→お帰りになる（社長の動作を高める）' }],
    commonMistakes: ['❌ 「お客様が申しました」→ ✅ 「お客様がおっしゃいました」（申す＝謙譲語、おっしゃる＝尊敬語）'],
    questions: [
      { id: 'ja_g9q1', question: '「食べる」の尊敬語は？', options: ['召し上がる', 'いただく', '食べられる', '食べます'], correctAnswer: '召し上がる', explanation: '尊敬語（相手の動作）＝召し上がる。謙譲語＝いただく。' },
      { id: 'ja_g9q2', question: '「行く」の謙譲語は？', options: ['参る', 'いらっしゃる', '行かれる', '行きます'], correctAnswer: '参る', explanation: '謙譲語（自分の動作を低める）＝参る。尊敬語＝いらっしゃる。' },
    ],
    tags: ['grammar', 'JLPT-N3', 'keigo', 'honorific'],
  },
  {
    id: 'ja_g10', title: '様態表現 (Appearance/Hearsay)', level: 'B1',
    description: 'そうだ・ようだ・らしい・みたいだの違い',
    theory: '「〜そうだ」（様態）は見た目の判断（おいしそうだ）。「〜そうだ」（伝聞）は聞いた情報。「〜ようだ」は推量（書き言葉的）。「〜らしい」は根拠ある推量。「〜みたいだ」は「ようだ」の口語形。',
    formula: 'V-ます+そうだ(様態) | V-る+そうだ(伝聞) | V-る+ようだ/らしい/みたいだ',
    examples: [{ sentence: 'このケーキはおいしそうだ。', explanation: '様態の「そうだ」：見た目からの判断' }],
    commonMistakes: ['❌ 「いいそうだ」→ ✅ 「よさそうだ」（いい→よさそう、特別な変化）'],
    questions: [
      { id: 'ja_g10q1', question: '空が暗いです。雨が降り___。', options: ['そうです', 'ようです', 'らしいです', 'みたいです'], correctAnswer: 'そうです', explanation: '見た目の判断→様態の「そうだ」。V-ます+そうだ。' },
      { id: 'ja_g10q2', question: 'ニュースによると、明日は雪が降る___。', options: ['そうです', 'そうだ', 'ようです', 'みたいです'], correctAnswer: 'そうです', explanation: '伝聞の「そうだ」：聞いた情報。V-る+そうだ。' },
    ],
    tags: ['grammar', 'JLPT-N3', 'appearance', 'hearsay'],
  },
];
