/**
 * IELTS Academic Word List (AWL) — 570 word families across 10 sublists.
 * Based on Averil Coxhead's Academic Word List (Victoria University of Wellington).
 * The word list itself is public domain; definitions, examples, and translations are original.
 *
 * Source: https://github.com/lpmi-13/machine_readable_wordlists (MIT License)
 * Vietnamese translations and example sentences are hand-written for EchLearn.
 */

export interface AWLWord {
  readonly id: string;
  readonly word: string;
  readonly ipa: string;
  readonly pos: string;
  readonly sublist: number;
  readonly meaning: string;
  readonly meaningVi: string;
  readonly example: string;
  readonly exampleVi: string;
  readonly topic: string;
  readonly wordFamily: readonly string[];
}

export type AWLSublist = readonly AWLWord[];

// ─── Sublist 1 (most frequent academic words) ───────────────────────
const sublist1: AWLSublist = [
  { id: 'awl-001', word: 'analyse', ipa: '/ˈæn.ə.laɪz/', pos: 'verb', sublist: 1, meaning: 'To examine something in detail to understand it', meaningVi: 'Phân tích', example: 'We need to analyse the data before drawing conclusions.', exampleVi: 'Chúng ta cần phân tích dữ liệu trước khi đưa ra kết luận.', topic: 'Research', wordFamily: ['analysed', 'analysis', 'analyst', 'analytical'] },
  { id: 'awl-002', word: 'approach', ipa: '/əˈprəʊtʃ/', pos: 'noun/verb', sublist: 1, meaning: 'A way of dealing with something; to come near', meaningVi: 'Cách tiếp cận; đến gần', example: 'A new approach to language teaching has been developed.', exampleVi: 'Một cách tiếp cận mới trong giảng dạy ngôn ngữ đã được phát triển.', topic: 'Education', wordFamily: ['approached', 'approaches', 'approaching'] },
  { id: 'awl-003', word: 'area', ipa: '/ˈeə.ri.ə/', pos: 'noun', sublist: 1, meaning: 'A particular part of a place, subject, or activity', meaningVi: 'Khu vực; lĩnh vực', example: 'This area of research requires further investigation.', exampleVi: 'Lĩnh vực nghiên cứu này cần được điều tra thêm.', topic: 'General', wordFamily: ['areas'] },
  { id: 'awl-004', word: 'assess', ipa: '/əˈses/', pos: 'verb', sublist: 1, meaning: 'To judge or decide the amount, value, or importance of something', meaningVi: 'Đánh giá', example: 'Teachers assess students through various methods.', exampleVi: 'Giáo viên đánh giá học sinh qua nhiều phương pháp khác nhau.', topic: 'Education', wordFamily: ['assessed', 'assessment', 'assessments', 'reassess'] },
  { id: 'awl-005', word: 'assume', ipa: '/əˈsjuːm/', pos: 'verb', sublist: 1, meaning: 'To accept something as true without proof', meaningVi: 'Giả định; cho rằng', example: 'We cannot assume that all students learn at the same pace.', exampleVi: 'Chúng ta không thể giả định rằng tất cả học sinh đều học cùng tốc độ.', topic: 'Research', wordFamily: ['assumed', 'assumption', 'assumptions'] },
  { id: 'awl-006', word: 'authority', ipa: '/ɔːˈθɒr.ɪ.ti/', pos: 'noun', sublist: 1, meaning: 'The power or right to give orders; an expert', meaningVi: 'Quyền lực; cơ quan chức năng', example: 'The local authority approved the new housing project.', exampleVi: 'Cơ quan chức năng địa phương đã phê duyệt dự án nhà ở mới.', topic: 'Government', wordFamily: ['authoritative', 'authorities'] },
  { id: 'awl-007', word: 'available', ipa: '/əˈveɪ.lə.bəl/', pos: 'adjective', sublist: 1, meaning: 'Able to be used or obtained', meaningVi: 'Có sẵn; khả dụng', example: 'The report will be available online next week.', exampleVi: 'Báo cáo sẽ có sẵn trực tuyến vào tuần tới.', topic: 'General', wordFamily: ['availability', 'unavailable'] },
  { id: 'awl-008', word: 'benefit', ipa: '/ˈben.ɪ.fɪt/', pos: 'noun/verb', sublist: 1, meaning: 'An advantage or profit; to receive an advantage', meaningVi: 'Lợi ích; hưởng lợi', example: 'Exercise has many health benefits.', exampleVi: 'Tập thể dục mang lại nhiều lợi ích sức khỏe.', topic: 'Health', wordFamily: ['beneficial', 'beneficiary', 'benefited'] },
  { id: 'awl-009', word: 'concept', ipa: '/ˈkɒn.sept/', pos: 'noun', sublist: 1, meaning: 'An abstract idea or general notion', meaningVi: 'Khái niệm', example: 'The concept of sustainability is central to modern urban planning.', exampleVi: 'Khái niệm bền vững là trọng tâm trong quy hoạch đô thị hiện đại.', topic: 'Education', wordFamily: ['concepts', 'conceptual', 'conceptualise'] },
  { id: 'awl-010', word: 'consist', ipa: '/kənˈsɪst/', pos: 'verb', sublist: 1, meaning: 'To be made up of; to be composed of', meaningVi: 'Bao gồm', example: 'The committee consists of twelve members.', exampleVi: 'Ủy ban bao gồm mười hai thành viên.', topic: 'General', wordFamily: ['consisted', 'consistency', 'consistent', 'consistently'] },
  { id: 'awl-011', word: 'constitute', ipa: '/ˈkɒn.stɪ.tjuːt/', pos: 'verb', sublist: 1, meaning: 'To form or make up; to establish', meaningVi: 'Cấu thành; thiết lập', example: 'Women constitute 60% of the student population.', exampleVi: 'Phụ nữ cấu thành 60% dân số sinh viên.', topic: 'Society', wordFamily: ['constituent', 'constitution', 'constitutional'] },
  { id: 'awl-012', word: 'context', ipa: '/ˈkɒn.tekst/', pos: 'noun', sublist: 1, meaning: 'The circumstances or setting in which something occurs', meaningVi: 'Bối cảnh; ngữ cảnh', example: 'The meaning of the word depends on the context.', exampleVi: 'Nghĩa của từ phụ thuộc vào ngữ cảnh.', topic: 'Education', wordFamily: ['contexts', 'contextual', 'contextualise'] },
  { id: 'awl-013', word: 'contract', ipa: '/ˈkɒn.trækt/', pos: 'noun/verb', sublist: 1, meaning: 'A written legal agreement; to decrease in size', meaningVi: 'Hợp đồng; co lại', example: 'They signed a five-year contract with the supplier.', exampleVi: 'Họ đã ký hợp đồng năm năm với nhà cung cấp.', topic: 'Business', wordFamily: ['contracted', 'contractor', 'contracts'] },
  { id: 'awl-014', word: 'create', ipa: '/kriˈeɪt/', pos: 'verb', sublist: 1, meaning: 'To bring something into existence', meaningVi: 'Tạo ra; sáng tạo', example: 'The government plans to create thousands of new jobs.', exampleVi: 'Chính phủ có kế hoạch tạo ra hàng nghìn việc làm mới.', topic: 'General', wordFamily: ['created', 'creation', 'creative', 'creativity', 'creator'] },
  { id: 'awl-015', word: 'data', ipa: '/ˈdeɪ.tə/', pos: 'noun', sublist: 1, meaning: 'Facts and statistics collected for analysis', meaningVi: 'Dữ liệu', example: 'The data suggests a significant improvement in test scores.', exampleVi: 'Dữ liệu cho thấy sự cải thiện đáng kể trong điểm thi.', topic: 'Research', wordFamily: [] },
  { id: 'awl-016', word: 'define', ipa: '/dɪˈfaɪn/', pos: 'verb', sublist: 1, meaning: 'To state the exact meaning of something', meaningVi: 'Định nghĩa; xác định', example: 'It is important to clearly define the scope of the study.', exampleVi: 'Điều quan trọng là xác định rõ ràng phạm vi nghiên cứu.', topic: 'Research', wordFamily: ['defined', 'definition', 'definitions', 'redefine', 'undefined'] },
  { id: 'awl-017', word: 'derive', ipa: '/dɪˈraɪv/', pos: 'verb', sublist: 1, meaning: 'To obtain something from a source; to originate from', meaningVi: 'Bắt nguồn; rút ra', example: 'Many English words are derived from Latin.', exampleVi: 'Nhiều từ tiếng Anh bắt nguồn từ tiếng Latin.', topic: 'Education', wordFamily: ['derivation', 'derivative', 'derived'] },
  { id: 'awl-018', word: 'distribute', ipa: '/dɪˈstrɪb.juːt/', pos: 'verb', sublist: 1, meaning: 'To give or spread out to several people or places', meaningVi: 'Phân phối; phân bổ', example: 'The charity distributes food to families in need.', exampleVi: 'Tổ chức từ thiện phân phối thực phẩm cho các gia đình cần giúp đỡ.', topic: 'Society', wordFamily: ['distributed', 'distribution', 'distributive', 'redistribute'] },
  { id: 'awl-019', word: 'economy', ipa: '/ɪˈkɒn.ə.mi/', pos: 'noun', sublist: 1, meaning: 'The system of production and trade in a country', meaningVi: 'Kinh tế', example: 'The global economy has been affected by the pandemic.', exampleVi: 'Kinh tế toàn cầu đã bị ảnh hưởng bởi đại dịch.', topic: 'Economics', wordFamily: ['economic', 'economical', 'economically', 'economics', 'economist'] },
  { id: 'awl-020', word: 'environment', ipa: '/ɪnˈvaɪ.rən.mənt/', pos: 'noun', sublist: 1, meaning: 'The natural world; the conditions in which one lives', meaningVi: 'Môi trường', example: 'Protecting the environment is everyone\'s responsibility.', exampleVi: 'Bảo vệ môi trường là trách nhiệm của mọi người.', topic: 'Environment', wordFamily: ['environmental', 'environmentalist', 'environmentally'] },
  { id: 'awl-021', word: 'establish', ipa: '/ɪˈstæb.lɪʃ/', pos: 'verb', sublist: 1, meaning: 'To set up or create something on a firm basis', meaningVi: 'Thành lập; thiết lập', example: 'The university was established in 1850.', exampleVi: 'Trường đại học được thành lập vào năm 1850.', topic: 'Education', wordFamily: ['established', 'establishment'] },
  { id: 'awl-022', word: 'estimate', ipa: '/ˈes.tɪ.meɪt/', pos: 'verb/noun', sublist: 1, meaning: 'To roughly calculate or judge the value of something', meaningVi: 'Ước tính', example: 'Scientists estimate that sea levels could rise by one metre.', exampleVi: 'Các nhà khoa học ước tính rằng mực nước biển có thể tăng một mét.', topic: 'Research', wordFamily: ['estimated', 'estimation', 'overestimate', 'underestimate'] },
  { id: 'awl-023', word: 'evident', ipa: '/ˈev.ɪ.dənt/', pos: 'adjective', sublist: 1, meaning: 'Clearly seen or understood; obvious', meaningVi: 'Rõ ràng; hiển nhiên', example: 'The benefits of education are evident in society.', exampleVi: 'Lợi ích của giáo dục là hiển nhiên trong xã hội.', topic: 'General', wordFamily: ['evidence', 'evidenced', 'evidently'] },
  { id: 'awl-024', word: 'export', ipa: '/ɪkˈspɔːt/', pos: 'verb/noun', sublist: 1, meaning: 'To send goods to another country for sale', meaningVi: 'Xuất khẩu', example: 'Vietnam exports rice to many countries worldwide.', exampleVi: 'Việt Nam xuất khẩu gạo sang nhiều quốc gia trên thế giới.', topic: 'Economics', wordFamily: ['exported', 'exporter', 'exports'] },
  { id: 'awl-025', word: 'factor', ipa: '/ˈfæk.tər/', pos: 'noun', sublist: 1, meaning: 'A circumstance or element that contributes to a result', meaningVi: 'Yếu tố; nhân tố', example: 'Several factors contributed to the company\'s success.', exampleVi: 'Nhiều yếu tố đã góp phần vào sự thành công của công ty.', topic: 'Business', wordFamily: ['factors'] },
  { id: 'awl-026', word: 'finance', ipa: '/ˈfaɪ.næns/', pos: 'noun/verb', sublist: 1, meaning: 'The management of money; to provide funding for', meaningVi: 'Tài chính; tài trợ', example: 'The project was financed by the World Bank.', exampleVi: 'Dự án được tài trợ bởi Ngân hàng Thế giới.', topic: 'Economics', wordFamily: ['financed', 'financial', 'financially', 'financing'] },
  { id: 'awl-027', word: 'formula', ipa: '/ˈfɔː.mjʊ.lə/', pos: 'noun', sublist: 1, meaning: 'A mathematical relationship or a method for achieving something', meaningVi: 'Công thức', example: 'There is no simple formula for success.', exampleVi: 'Không có công thức đơn giản nào cho sự thành công.', topic: 'Science', wordFamily: ['formulae', 'formulas', 'formulate', 'formulation'] },
  { id: 'awl-028', word: 'function', ipa: '/ˈfʌŋk.ʃən/', pos: 'noun/verb', sublist: 1, meaning: 'A purpose or role; to work or operate', meaningVi: 'Chức năng; hoạt động', example: 'Each organ in the body has a specific function.', exampleVi: 'Mỗi cơ quan trong cơ thể có một chức năng cụ thể.', topic: 'Science', wordFamily: ['functional', 'functionally', 'functioning'] },
  { id: 'awl-029', word: 'identify', ipa: '/aɪˈden.tɪ.faɪ/', pos: 'verb', sublist: 1, meaning: 'To recognize or establish who or what something is', meaningVi: 'Nhận diện; xác định', example: 'Police have identified the suspect from CCTV footage.', exampleVi: 'Cảnh sát đã xác định nghi phạm từ camera an ninh.', topic: 'General', wordFamily: ['identifiable', 'identification', 'identified', 'identity'] },
  { id: 'awl-030', word: 'income', ipa: '/ˈɪn.kʌm/', pos: 'noun', sublist: 1, meaning: 'Money received through work or investments', meaningVi: 'Thu nhập', example: 'Average household income has risen by 5% this year.', exampleVi: 'Thu nhập hộ gia đình trung bình đã tăng 5% trong năm nay.', topic: 'Economics', wordFamily: ['incomes'] },
  { id: 'awl-031', word: 'indicate', ipa: '/ˈɪn.dɪ.keɪt/', pos: 'verb', sublist: 1, meaning: 'To point out; to show or suggest', meaningVi: 'Chỉ ra; cho thấy', example: 'The survey results indicate a growing demand for online learning.', exampleVi: 'Kết quả khảo sát cho thấy nhu cầu ngày càng tăng đối với học trực tuyến.', topic: 'Research', wordFamily: ['indicated', 'indication', 'indicator', 'indicators'] },
  { id: 'awl-032', word: 'individual', ipa: '/ˌɪn.dɪˈvɪdʒ.u.əl/', pos: 'noun/adj', sublist: 1, meaning: 'A single person; relating to one person', meaningVi: 'Cá nhân; riêng lẻ', example: 'Each individual has unique learning needs.', exampleVi: 'Mỗi cá nhân có nhu cầu học tập riêng biệt.', topic: 'Society', wordFamily: ['individually', 'individuals', 'individualism'] },
  { id: 'awl-033', word: 'interpret', ipa: '/ɪnˈtɜː.prɪt/', pos: 'verb', sublist: 1, meaning: 'To explain the meaning of; to understand in a particular way', meaningVi: 'Diễn giải; phiên dịch', example: 'Different cultures may interpret the same gesture differently.', exampleVi: 'Các nền văn hóa khác nhau có thể diễn giải cùng một cử chỉ theo cách khác nhau.', topic: 'Education', wordFamily: ['interpretation', 'interpreted', 'misinterpret'] },
  { id: 'awl-034', word: 'involve', ipa: '/ɪnˈvɒlv/', pos: 'verb', sublist: 1, meaning: 'To include as a necessary part; to participate in', meaningVi: 'Liên quan đến; bao gồm', example: 'The project involves collaboration between five universities.', exampleVi: 'Dự án bao gồm sự hợp tác giữa năm trường đại học.', topic: 'General', wordFamily: ['involved', 'involvement', 'involving'] },
  { id: 'awl-035', word: 'issue', ipa: '/ˈɪʃ.uː/', pos: 'noun/verb', sublist: 1, meaning: 'An important topic for discussion; to officially give out', meaningVi: 'Vấn đề; phát hành', example: 'Climate change is a critical issue facing the world today.', exampleVi: 'Biến đổi khí hậu là một vấn đề nghiêm trọng mà thế giới đang đối mặt.', topic: 'Environment', wordFamily: ['issued', 'issues', 'issuing'] },
  { id: 'awl-036', word: 'labour', ipa: '/ˈleɪ.bər/', pos: 'noun/verb', sublist: 1, meaning: 'Physical or mental work; the workforce', meaningVi: 'Lao động; nhân công', example: 'The labour market has changed significantly due to automation.', exampleVi: 'Thị trường lao động đã thay đổi đáng kể do tự động hóa.', topic: 'Economics', wordFamily: ['labor', 'laboured', 'labouring'] },
  { id: 'awl-037', word: 'legal', ipa: '/ˈliː.ɡəl/', pos: 'adjective', sublist: 1, meaning: 'Relating to the law; permitted by law', meaningVi: 'Hợp pháp; thuộc pháp luật', example: 'All employees have legal rights to a safe workplace.', exampleVi: 'Tất cả nhân viên đều có quyền hợp pháp được làm việc trong môi trường an toàn.', topic: 'Law', wordFamily: ['illegal', 'illegality', 'legally'] },
  { id: 'awl-038', word: 'legislate', ipa: '/ˈledʒ.ɪ.sleɪt/', pos: 'verb', sublist: 1, meaning: 'To make or enact laws', meaningVi: 'Lập pháp; ban hành luật', example: 'The government has legislated to reduce carbon emissions.', exampleVi: 'Chính phủ đã ban hành luật để giảm phát thải carbon.', topic: 'Government', wordFamily: ['legislation', 'legislative', 'legislator', 'legislature'] },
  { id: 'awl-039', word: 'major', ipa: '/ˈmeɪ.dʒər/', pos: 'adjective', sublist: 1, meaning: 'Very large or important', meaningVi: 'Chủ yếu; lớn; quan trọng', example: 'Traffic congestion is a major problem in urban areas.', exampleVi: 'Tắc nghẽn giao thông là một vấn đề lớn ở khu vực đô thị.', topic: 'General', wordFamily: ['majority'] },
  { id: 'awl-040', word: 'method', ipa: '/ˈmeθ.əd/', pos: 'noun', sublist: 1, meaning: 'A particular way of doing something', meaningVi: 'Phương pháp', example: 'The study employed mixed research methods.', exampleVi: 'Nghiên cứu sử dụng phương pháp nghiên cứu hỗn hợp.', topic: 'Research', wordFamily: ['methodical', 'methodology', 'methods'] },
  { id: 'awl-041', word: 'occur', ipa: '/əˈkɜːr/', pos: 'verb', sublist: 1, meaning: 'To happen; to take place', meaningVi: 'Xảy ra', example: 'Earthquakes frequently occur along tectonic plate boundaries.', exampleVi: 'Động đất thường xảy ra dọc theo ranh giới mảng kiến tạo.', topic: 'Science', wordFamily: ['occurred', 'occurrence', 'occurring', 'occurs'] },
  { id: 'awl-042', word: 'percent', ipa: '/pəˈsent/', pos: 'noun', sublist: 1, meaning: 'One part in every hundred', meaningVi: 'Phần trăm', example: 'Approximately 70 percent of the Earth\'s surface is covered by water.', exampleVi: 'Khoảng 70 phần trăm bề mặt Trái Đất được bao phủ bởi nước.', topic: 'Research', wordFamily: ['percentage', 'percentages'] },
  { id: 'awl-043', word: 'period', ipa: '/ˈpɪə.ri.əd/', pos: 'noun', sublist: 1, meaning: 'A length of time', meaningVi: 'Giai đoạn; thời kỳ', example: 'The study was conducted over a period of six months.', exampleVi: 'Nghiên cứu được tiến hành trong giai đoạn sáu tháng.', topic: 'Research', wordFamily: ['periodic', 'periodically', 'periods'] },
  { id: 'awl-044', word: 'policy', ipa: '/ˈpɒl.ə.si/', pos: 'noun', sublist: 1, meaning: 'A plan of action adopted by a government or organization', meaningVi: 'Chính sách', example: 'The new education policy aims to improve literacy rates.', exampleVi: 'Chính sách giáo dục mới nhằm cải thiện tỷ lệ biết chữ.', topic: 'Government', wordFamily: ['policies'] },
  { id: 'awl-045', word: 'principle', ipa: '/ˈprɪn.sə.pəl/', pos: 'noun', sublist: 1, meaning: 'A fundamental truth or belief that guides behavior', meaningVi: 'Nguyên tắc; nguyên lý', example: 'The principle of equality underpins democratic societies.', exampleVi: 'Nguyên tắc bình đẳng là nền tảng của các xã hội dân chủ.', topic: 'Society', wordFamily: ['principled', 'principles'] },
  { id: 'awl-046', word: 'proceed', ipa: '/prəˈsiːd/', pos: 'verb', sublist: 1, meaning: 'To continue or move forward', meaningVi: 'Tiến hành; tiếp tục', example: 'Please proceed to the next section of the exam.', exampleVi: 'Vui lòng tiếp tục sang phần tiếp theo của bài thi.', topic: 'General', wordFamily: ['procedure', 'procedures', 'proceedings', 'proceeds'] },
  { id: 'awl-047', word: 'process', ipa: '/ˈprəʊ.ses/', pos: 'noun/verb', sublist: 1, meaning: 'A series of actions to achieve a result; to handle systematically', meaningVi: 'Quá trình; xử lý', example: 'The manufacturing process has been streamlined.', exampleVi: 'Quy trình sản xuất đã được tinh giản.', topic: 'Business', wordFamily: ['processed', 'processes', 'processing'] },
  { id: 'awl-048', word: 'require', ipa: '/rɪˈkwaɪər/', pos: 'verb', sublist: 1, meaning: 'To need something; to make something necessary', meaningVi: 'Yêu cầu; đòi hỏi', example: 'This course requires a minimum IELTS score of 6.5.', exampleVi: 'Khóa học này yêu cầu điểm IELTS tối thiểu 6.5.', topic: 'Education', wordFamily: ['required', 'requirement', 'requirements', 'requiring'] },
  { id: 'awl-049', word: 'research', ipa: '/rɪˈsɜːtʃ/', pos: 'noun/verb', sublist: 1, meaning: 'Systematic investigation to establish facts', meaningVi: 'Nghiên cứu', example: 'Scientific research has led to many medical breakthroughs.', exampleVi: 'Nghiên cứu khoa học đã dẫn đến nhiều đột phá y khoa.', topic: 'Research', wordFamily: ['researched', 'researcher', 'researchers'] },
  { id: 'awl-050', word: 'respond', ipa: '/rɪˈspɒnd/', pos: 'verb', sublist: 1, meaning: 'To say or do something as a reaction', meaningVi: 'Phản hồi; đáp lại', example: 'The government must respond to public concerns about pollution.', exampleVi: 'Chính phủ phải phản hồi những lo ngại của công chúng về ô nhiễm.', topic: 'General', wordFamily: ['responded', 'response', 'responses', 'responsive'] },
  { id: 'awl-051', word: 'role', ipa: '/rəʊl/', pos: 'noun', sublist: 1, meaning: 'A function or part played by someone', meaningVi: 'Vai trò', example: 'Technology plays an important role in modern education.', exampleVi: 'Công nghệ đóng vai trò quan trọng trong giáo dục hiện đại.', topic: 'General', wordFamily: ['roles'] },
  { id: 'awl-052', word: 'section', ipa: '/ˈsek.ʃən/', pos: 'noun', sublist: 1, meaning: 'A distinct part of something', meaningVi: 'Phần; mục', example: 'Please read the relevant section of the textbook.', exampleVi: 'Vui lòng đọc phần liên quan trong sách giáo khoa.', topic: 'Education', wordFamily: ['sections'] },
  { id: 'awl-053', word: 'sector', ipa: '/ˈsek.tər/', pos: 'noun', sublist: 1, meaning: 'A distinct part of the economy or society', meaningVi: 'Lĩnh vực; khu vực (kinh tế)', example: 'The technology sector has experienced rapid growth.', exampleVi: 'Lĩnh vực công nghệ đã trải qua sự tăng trưởng nhanh chóng.', topic: 'Economics', wordFamily: ['sectors'] },
  { id: 'awl-054', word: 'significant', ipa: '/sɪɡˈnɪf.ɪ.kənt/', pos: 'adjective', sublist: 1, meaning: 'Important enough to have an effect; large enough to be noticed', meaningVi: 'Đáng kể; quan trọng', example: 'There has been a significant increase in renewable energy usage.', exampleVi: 'Đã có sự gia tăng đáng kể trong việc sử dụng năng lượng tái tạo.', topic: 'Research', wordFamily: ['significance', 'significantly', 'insignificant'] },
  { id: 'awl-055', word: 'similar', ipa: '/ˈsɪm.ɪ.lər/', pos: 'adjective', sublist: 1, meaning: 'Resembling but not identical', meaningVi: 'Tương tự', example: 'The two languages share similar grammatical structures.', exampleVi: 'Hai ngôn ngữ chia sẻ cấu trúc ngữ pháp tương tự.', topic: 'Education', wordFamily: ['dissimilar', 'similarity', 'similarly'] },
  { id: 'awl-056', word: 'source', ipa: '/sɔːs/', pos: 'noun/verb', sublist: 1, meaning: 'Where something comes from; an origin', meaningVi: 'Nguồn; nguồn gốc', example: 'Renewable energy sources include solar and wind power.', exampleVi: 'Các nguồn năng lượng tái tạo bao gồm năng lượng mặt trời và gió.', topic: 'Environment', wordFamily: ['sourced', 'sources', 'sourcing'] },
  { id: 'awl-057', word: 'specific', ipa: '/spəˈsɪf.ɪk/', pos: 'adjective', sublist: 1, meaning: 'Clearly defined or identified; particular', meaningVi: 'Cụ thể; đặc thù', example: 'The guidelines provide specific instructions for each task.', exampleVi: 'Hướng dẫn cung cấp chỉ dẫn cụ thể cho mỗi nhiệm vụ.', topic: 'General', wordFamily: ['specifically', 'specification', 'specificity'] },
  { id: 'awl-058', word: 'structure', ipa: '/ˈstrʌk.tʃər/', pos: 'noun/verb', sublist: 1, meaning: 'The way something is organized or arranged', meaningVi: 'Cấu trúc', example: 'The essay must have a clear structure with an introduction, body, and conclusion.', exampleVi: 'Bài luận phải có cấu trúc rõ ràng với phần mở đầu, thân bài và kết luận.', topic: 'Education', wordFamily: ['restructure', 'structural', 'structured'] },
  { id: 'awl-059', word: 'theory', ipa: '/ˈθɪə.ri/', pos: 'noun', sublist: 1, meaning: 'A set of ideas intended to explain something', meaningVi: 'Lý thuyết', example: 'Darwin\'s theory of evolution changed our understanding of biology.', exampleVi: 'Thuyết tiến hóa của Darwin đã thay đổi hiểu biết của chúng ta về sinh học.', topic: 'Science', wordFamily: ['theoretical', 'theoretically', 'theories', 'theorist'] },
  { id: 'awl-060', word: 'vary', ipa: '/ˈveə.ri/', pos: 'verb', sublist: 1, meaning: 'To differ; to change or be different', meaningVi: 'Thay đổi; khác nhau', example: 'Temperatures vary significantly between summer and winter.', exampleVi: 'Nhiệt độ thay đổi đáng kể giữa mùa hè và mùa đông.', topic: 'Science', wordFamily: ['variable', 'variables', 'variance', 'variation', 'varied', 'varies'] },
];

// ─── Sublist 2 ───────────────────────────────────────────────────────
const sublist2: AWLSublist = [
  { id: 'awl-061', word: 'achieve', ipa: '/əˈtʃiːv/', pos: 'verb', sublist: 2, meaning: 'To succeed in reaching a goal or standard', meaningVi: 'Đạt được; hoàn thành', example: 'Students can achieve higher scores through regular practice.', exampleVi: 'Học sinh có thể đạt được điểm số cao hơn thông qua luyện tập thường xuyên.', topic: 'Education', wordFamily: ['achievable', 'achieved', 'achievement'] },
  { id: 'awl-062', word: 'acquire', ipa: '/əˈkwaɪər/', pos: 'verb', sublist: 2, meaning: 'To gain or obtain something through effort', meaningVi: 'Tiếp thu; thu được', example: 'Children acquire language skills through interaction.', exampleVi: 'Trẻ em tiếp thu kỹ năng ngôn ngữ thông qua tương tác.', topic: 'Education', wordFamily: ['acquired', 'acquisition'] },
  { id: 'awl-063', word: 'administrate', ipa: '/ədˈmɪn.ɪ.streɪt/', pos: 'verb', sublist: 2, meaning: 'To manage or organize the running of something', meaningVi: 'Quản trị; quản lý', example: 'A team of professionals administrates the university.', exampleVi: 'Một đội ngũ chuyên gia quản trị trường đại học.', topic: 'Business', wordFamily: ['administration', 'administrative', 'administrator'] },
  { id: 'awl-064', word: 'affect', ipa: '/əˈfekt/', pos: 'verb', sublist: 2, meaning: 'To have an influence on; to produce a change in', meaningVi: 'Ảnh hưởng đến; tác động', example: 'Climate change affects food production worldwide.', exampleVi: 'Biến đổi khí hậu ảnh hưởng đến sản xuất lương thực trên toàn thế giới.', topic: 'Environment', wordFamily: ['affected', 'affecting', 'affects', 'unaffected'] },
  { id: 'awl-065', word: 'appropriate', ipa: '/əˈprəʊ.pri.ət/', pos: 'adjective', sublist: 2, meaning: 'Suitable or proper in the circumstances', meaningVi: 'Phù hợp; thích hợp', example: 'It is important to use appropriate language in academic writing.', exampleVi: 'Điều quan trọng là sử dụng ngôn ngữ phù hợp trong viết học thuật.', topic: 'Education', wordFamily: ['appropriately', 'appropriateness', 'inappropriate'] },
  { id: 'awl-066', word: 'aspect', ipa: '/ˈæs.pekt/', pos: 'noun', sublist: 2, meaning: 'A particular part or feature of something', meaningVi: 'Khía cạnh; phương diện', example: 'This report examines several aspects of urban development.', exampleVi: 'Báo cáo này xem xét nhiều khía cạnh của phát triển đô thị.', topic: 'General', wordFamily: ['aspects'] },
  { id: 'awl-067', word: 'assist', ipa: '/əˈsɪst/', pos: 'verb', sublist: 2, meaning: 'To help or support', meaningVi: 'Hỗ trợ; giúp đỡ', example: 'Technology can assist teachers in delivering effective lessons.', exampleVi: 'Công nghệ có thể hỗ trợ giáo viên trong việc giảng dạy hiệu quả.', topic: 'Education', wordFamily: ['assistance', 'assistant', 'assisted'] },
  { id: 'awl-068', word: 'category', ipa: '/ˈkæt.ə.ɡər.i/', pos: 'noun', sublist: 2, meaning: 'A group of things sharing similar characteristics', meaningVi: 'Loại; hạng mục', example: 'The books are organized into different categories.', exampleVi: 'Các cuốn sách được sắp xếp theo các loại khác nhau.', topic: 'General', wordFamily: ['categories', 'categorise', 'categorised'] },
  { id: 'awl-069', word: 'chapter', ipa: '/ˈtʃæp.tər/', pos: 'noun', sublist: 2, meaning: 'A main division of a book', meaningVi: 'Chương', example: 'Chapter three discusses the methodology of the study.', exampleVi: 'Chương ba thảo luận về phương pháp nghiên cứu.', topic: 'Education', wordFamily: ['chapters'] },
  { id: 'awl-070', word: 'commission', ipa: '/kəˈmɪʃ.ən/', pos: 'noun/verb', sublist: 2, meaning: 'An official group given authority; to formally order work', meaningVi: 'Ủy ban; ủy nhiệm', example: 'The government commissioned a report on air quality.', exampleVi: 'Chính phủ ủy nhiệm một báo cáo về chất lượng không khí.', topic: 'Government', wordFamily: ['commissioned', 'commissioner'] },
  { id: 'awl-071', word: 'community', ipa: '/kəˈmjuː.nə.ti/', pos: 'noun', sublist: 2, meaning: 'A group of people living in the same area or sharing interests', meaningVi: 'Cộng đồng', example: 'The local community benefits from the new library.', exampleVi: 'Cộng đồng địa phương hưởng lợi từ thư viện mới.', topic: 'Society', wordFamily: ['communities'] },
  { id: 'awl-072', word: 'complex', ipa: '/ˈkɒm.pleks/', pos: 'adjective', sublist: 2, meaning: 'Consisting of many interconnected parts; not simple', meaningVi: 'Phức tạp', example: 'Language is a complex system of communication.', exampleVi: 'Ngôn ngữ là một hệ thống giao tiếp phức tạp.', topic: 'General', wordFamily: ['complexities', 'complexity'] },
  { id: 'awl-073', word: 'compute', ipa: '/kəmˈpjuːt/', pos: 'verb', sublist: 2, meaning: 'To calculate; to reckon mathematically', meaningVi: 'Tính toán', example: 'Modern computers can compute billions of operations per second.', exampleVi: 'Máy tính hiện đại có thể tính toán hàng tỷ phép tính mỗi giây.', topic: 'Technology', wordFamily: ['computation', 'computer', 'computing'] },
  { id: 'awl-074', word: 'conclude', ipa: '/kənˈkluːd/', pos: 'verb', sublist: 2, meaning: 'To bring to an end; to reach a judgment after reasoning', meaningVi: 'Kết luận', example: 'The researchers concluded that the treatment was effective.', exampleVi: 'Các nhà nghiên cứu kết luận rằng phương pháp điều trị có hiệu quả.', topic: 'Research', wordFamily: ['concluded', 'conclusion', 'conclusions', 'conclusive'] },
  { id: 'awl-075', word: 'conduct', ipa: '/kənˈdʌkt/', pos: 'verb/noun', sublist: 2, meaning: 'To carry out; behavior or the way one acts', meaningVi: 'Tiến hành; cách ứng xử', example: 'The university conducted a survey on student satisfaction.', exampleVi: 'Trường đại học tiến hành một cuộc khảo sát về sự hài lòng của sinh viên.', topic: 'Research', wordFamily: ['conducted', 'conducting', 'conducts'] },
  { id: 'awl-076', word: 'consequent', ipa: '/ˈkɒn.sɪ.kwənt/', pos: 'adjective', sublist: 2, meaning: 'Following as a result; resulting', meaningVi: 'Kết quả; hệ quả', example: 'Deforestation and the consequent loss of biodiversity are major concerns.', exampleVi: 'Phá rừng và hệ quả mất đa dạng sinh học là những mối lo ngại lớn.', topic: 'Environment', wordFamily: ['consequence', 'consequences', 'consequently'] },
  { id: 'awl-077', word: 'construct', ipa: '/kənˈstrʌkt/', pos: 'verb', sublist: 2, meaning: 'To build or make something', meaningVi: 'Xây dựng; kiến tạo', example: 'The bridge was constructed using sustainable materials.', exampleVi: 'Cây cầu được xây dựng bằng vật liệu bền vững.', topic: 'Technology', wordFamily: ['constructed', 'construction', 'constructive', 'reconstruct'] },
  { id: 'awl-078', word: 'consume', ipa: '/kənˈsjuːm/', pos: 'verb', sublist: 2, meaning: 'To eat, drink, or use up resources', meaningVi: 'Tiêu thụ; tiêu dùng', example: 'Developed nations consume a disproportionate share of resources.', exampleVi: 'Các quốc gia phát triển tiêu thụ một phần tài nguyên không cân xứng.', topic: 'Environment', wordFamily: ['consumer', 'consumers', 'consumption'] },
  { id: 'awl-079', word: 'credit', ipa: '/ˈkred.ɪt/', pos: 'noun/verb', sublist: 2, meaning: 'Recognition for achievement; borrowed money', meaningVi: 'Tín dụng; công nhận', example: 'Students earn credits by completing each course module.', exampleVi: 'Sinh viên kiếm tín chỉ bằng cách hoàn thành mỗi học phần.', topic: 'Education', wordFamily: ['credited', 'creditor', 'credits'] },
  { id: 'awl-080', word: 'culture', ipa: '/ˈkʌl.tʃər/', pos: 'noun', sublist: 2, meaning: 'The beliefs, customs, and arts of a particular society', meaningVi: 'Văn hóa', example: 'Understanding different cultures is essential for global communication.', exampleVi: 'Hiểu các nền văn hóa khác nhau là thiết yếu cho giao tiếp toàn cầu.', topic: 'Society', wordFamily: ['cultural', 'culturally', 'cultures'] },
];

// ─── IELTS Topic Vocabulary (8 core IELTS topics) ────────────────────
export interface IELTSTopicVocab {
  readonly id: string;
  readonly word: string;
  readonly ipa: string;
  readonly pos: string;
  readonly band: string;
  readonly topic: string;
  readonly meaning: string;
  readonly meaningVi: string;
  readonly example: string;
  readonly exampleVi: string;
  readonly collocations: readonly string[];
}

export const IELTS_TOPIC_VOCABULARY: readonly IELTSTopicVocab[] = [
  // ── Education ──
  { id: 'ielts-edu-001', word: 'curriculum', ipa: '/kəˈrɪk.jʊ.ləm/', pos: 'noun', band: '6.0+', topic: 'Education', meaning: 'The subjects comprising a course of study', meaningVi: 'Chương trình giảng dạy', example: 'The school has updated its curriculum to include digital literacy.', exampleVi: 'Trường đã cập nhật chương trình giảng dạy để bao gồm kỹ năng số.', collocations: ['national curriculum', 'core curriculum', 'curriculum development'] },
  { id: 'ielts-edu-002', word: 'pedagogy', ipa: '/ˈped.ə.ɡɒdʒ.i/', pos: 'noun', band: '7.0+', topic: 'Education', meaning: 'The method and practice of teaching', meaningVi: 'Phương pháp sư phạm', example: 'Modern pedagogy emphasizes student-centered learning.', exampleVi: 'Phương pháp sư phạm hiện đại nhấn mạnh việc học lấy học sinh làm trung tâm.', collocations: ['progressive pedagogy', 'critical pedagogy'] },
  { id: 'ielts-edu-003', word: 'vocational', ipa: '/vəʊˈkeɪ.ʃən.əl/', pos: 'adjective', band: '6.5+', topic: 'Education', meaning: 'Relating to skills needed for a particular job or profession', meaningVi: 'Hướng nghiệp; nghề nghiệp', example: 'Vocational training programs help students prepare for specific careers.', exampleVi: 'Các chương trình đào tạo nghề giúp học sinh chuẩn bị cho nghề nghiệp cụ thể.', collocations: ['vocational training', 'vocational education', 'vocational qualifications'] },
  { id: 'ielts-edu-004', word: 'literacy', ipa: '/ˈlɪt.ər.ə.si/', pos: 'noun', band: '6.0+', topic: 'Education', meaning: 'The ability to read and write; competence in a specified area', meaningVi: 'Biết chữ; khả năng đọc viết', example: 'Improving digital literacy is essential in the 21st century.', exampleVi: 'Cải thiện kỹ năng số là thiết yếu trong thế kỷ 21.', collocations: ['digital literacy', 'financial literacy', 'media literacy'] },
  { id: 'ielts-edu-005', word: 'rote learning', ipa: '/rəʊt ˈlɜː.nɪŋ/', pos: 'noun', band: '7.0+', topic: 'Education', meaning: 'Learning by repetition without understanding', meaningVi: 'Học vẹt; học thuộc lòng', example: 'Many educators criticize rote learning as ineffective.', exampleVi: 'Nhiều nhà giáo dục phê phán việc học vẹt là không hiệu quả.', collocations: ['rely on rote learning', 'move away from rote learning'] },

  // ── Environment ──
  { id: 'ielts-env-001', word: 'biodiversity', ipa: '/ˌbaɪ.əʊ.daɪˈvɜː.sə.ti/', pos: 'noun', band: '6.5+', topic: 'Environment', meaning: 'The variety of plant and animal life in a habitat', meaningVi: 'Đa dạng sinh học', example: 'Coral reefs support incredible biodiversity.', exampleVi: 'Rạn san hô hỗ trợ đa dạng sinh học đáng kinh ngạc.', collocations: ['loss of biodiversity', 'biodiversity conservation', 'rich biodiversity'] },
  { id: 'ielts-env-002', word: 'sustainability', ipa: '/səˌsteɪ.nəˈbɪl.ə.ti/', pos: 'noun', band: '6.5+', topic: 'Environment', meaning: 'The ability to maintain ecological balance', meaningVi: 'Tính bền vững', example: 'Sustainability must be at the heart of economic policy.', exampleVi: 'Tính bền vững phải là trọng tâm của chính sách kinh tế.', collocations: ['environmental sustainability', 'promote sustainability', 'sustainability goals'] },
  { id: 'ielts-env-003', word: 'carbon footprint', ipa: '/ˌkɑː.bən ˈfʊt.prɪnt/', pos: 'noun', band: '6.5+', topic: 'Environment', meaning: 'The amount of carbon dioxide produced by one\'s activities', meaningVi: 'Dấu chân carbon', example: 'Flying internationally significantly increases your carbon footprint.', exampleVi: 'Bay quốc tế làm tăng đáng kể dấu chân carbon của bạn.', collocations: ['reduce carbon footprint', 'measure carbon footprint', 'individual carbon footprint'] },
  { id: 'ielts-env-004', word: 'deforestation', ipa: '/diːˌfɒr.ɪˈsteɪ.ʃən/', pos: 'noun', band: '6.0+', topic: 'Environment', meaning: 'The clearing of forests on a large scale', meaningVi: 'Phá rừng', example: 'Deforestation in the Amazon threatens global climate stability.', exampleVi: 'Phá rừng ở Amazon đe dọa sự ổn định khí hậu toàn cầu.', collocations: ['illegal deforestation', 'rate of deforestation', 'combat deforestation'] },
  { id: 'ielts-env-005', word: 'renewable', ipa: '/rɪˈnjuː.ə.bəl/', pos: 'adjective', band: '6.0+', topic: 'Environment', meaning: 'Able to be replenished naturally and not used up', meaningVi: 'Tái tạo được', example: 'Solar and wind are examples of renewable energy sources.', exampleVi: 'Năng lượng mặt trời và gió là ví dụ về các nguồn năng lượng tái tạo.', collocations: ['renewable energy', 'renewable resources', 'renewable sources'] },

  // ── Technology ──
  { id: 'ielts-tech-001', word: 'innovation', ipa: '/ˌɪn.əˈveɪ.ʃən/', pos: 'noun', band: '6.0+', topic: 'Technology', meaning: 'The introduction of new ideas, methods, or products', meaningVi: 'Sự đổi mới; sáng tạo', example: 'Technological innovation drives economic growth.', exampleVi: 'Đổi mới công nghệ thúc đẩy tăng trưởng kinh tế.', collocations: ['technological innovation', 'drive innovation', 'innovation in education'] },
  { id: 'ielts-tech-002', word: 'automation', ipa: '/ˌɔː.təˈmeɪ.ʃən/', pos: 'noun', band: '6.5+', topic: 'Technology', meaning: 'The use of machines or computers instead of people', meaningVi: 'Tự động hóa', example: 'Automation has transformed the manufacturing industry.', exampleVi: 'Tự động hóa đã biến đổi ngành công nghiệp sản xuất.', collocations: ['industrial automation', 'automation of tasks', 'increasing automation'] },
  { id: 'ielts-tech-003', word: 'obsolete', ipa: '/ˈɒb.sə.liːt/', pos: 'adjective', band: '7.0+', topic: 'Technology', meaning: 'No longer in use; outdated', meaningVi: 'Lỗi thời; không còn sử dụng', example: 'Many traditional skills have become obsolete due to technology.', exampleVi: 'Nhiều kỹ năng truyền thống đã trở nên lỗi thời do công nghệ.', collocations: ['become obsolete', 'render obsolete', 'technologically obsolete'] },
  { id: 'ielts-tech-004', word: 'artificial intelligence', ipa: '/ˌɑː.tɪ.fɪʃ.əl ɪnˈtel.ɪ.dʒəns/', pos: 'noun', band: '6.5+', topic: 'Technology', meaning: 'Computer systems able to perform tasks requiring human intelligence', meaningVi: 'Trí tuệ nhân tạo', example: 'Artificial intelligence is being used to diagnose diseases.', exampleVi: 'Trí tuệ nhân tạo đang được sử dụng để chẩn đoán bệnh.', collocations: ['AI technology', 'AI-powered', 'advances in AI'] },

  // ── Health ──
  { id: 'ielts-health-001', word: 'sedentary', ipa: '/ˈsed.ən.tər.i/', pos: 'adjective', band: '7.0+', topic: 'Health', meaning: 'Involving much sitting and little physical activity', meaningVi: 'Ít vận động; ngồi nhiều', example: 'A sedentary lifestyle increases the risk of heart disease.', exampleVi: 'Lối sống ít vận động làm tăng nguy cơ mắc bệnh tim.', collocations: ['sedentary lifestyle', 'sedentary job', 'sedentary behaviour'] },
  { id: 'ielts-health-002', word: 'epidemic', ipa: '/ˌep.ɪˈdem.ɪk/', pos: 'noun', band: '6.5+', topic: 'Health', meaning: 'A widespread occurrence of a disease in a community', meaningVi: 'Dịch bệnh; đại dịch', example: 'Obesity has reached epidemic proportions in many countries.', exampleVi: 'Béo phì đã đạt mức dịch bệnh ở nhiều quốc gia.', collocations: ['global epidemic', 'obesity epidemic', 'epidemic proportions'] },
  { id: 'ielts-health-003', word: 'well-being', ipa: '/ˌwel ˈbiː.ɪŋ/', pos: 'noun', band: '6.0+', topic: 'Health', meaning: 'The state of being comfortable, healthy, or happy', meaningVi: 'Hạnh phúc; sức khỏe tinh thần', example: 'Mental well-being is as important as physical health.', exampleVi: 'Sức khỏe tinh thần quan trọng như sức khỏe thể chất.', collocations: ['mental well-being', 'emotional well-being', 'promote well-being'] },
  { id: 'ielts-health-004', word: 'malnutrition', ipa: '/ˌmæl.njuːˈtrɪʃ.ən/', pos: 'noun', band: '7.0+', topic: 'Health', meaning: 'Lack of proper nutrition due to insufficient or unbalanced diet', meaningVi: 'Suy dinh dưỡng', example: 'Malnutrition remains a serious problem in developing countries.', exampleVi: 'Suy dinh dưỡng vẫn là một vấn đề nghiêm trọng ở các nước đang phát triển.', collocations: ['child malnutrition', 'combat malnutrition', 'severe malnutrition'] },

  // ── Society & Culture ──
  { id: 'ielts-soc-001', word: 'globalisation', ipa: '/ˌɡləʊ.bəl.aɪˈzeɪ.ʃən/', pos: 'noun', band: '6.5+', topic: 'Society', meaning: 'The process of interaction among people and nations worldwide', meaningVi: 'Toàn cầu hóa', example: 'Globalisation has both benefits and drawbacks for local cultures.', exampleVi: 'Toàn cầu hóa có cả lợi ích và hạn chế đối với văn hóa địa phương.', collocations: ['effects of globalisation', 'economic globalisation', 'cultural globalisation'] },
  { id: 'ielts-soc-002', word: 'demographics', ipa: '/ˌdem.əˈɡræf.ɪks/', pos: 'noun', band: '7.0+', topic: 'Society', meaning: 'Statistical data relating to the population', meaningVi: 'Nhân khẩu học', example: 'Changing demographics will affect the demand for healthcare services.', exampleVi: 'Thay đổi nhân khẩu học sẽ ảnh hưởng đến nhu cầu dịch vụ y tế.', collocations: ['shifting demographics', 'demographic trends', 'demographic data'] },
  { id: 'ielts-soc-003', word: 'disparity', ipa: '/dɪˈspær.ə.ti/', pos: 'noun', band: '7.0+', topic: 'Society', meaning: 'A great difference or inequality', meaningVi: 'Sự chênh lệch; bất bình đẳng', example: 'There is a growing disparity between rich and poor.', exampleVi: 'Có sự chênh lệch ngày càng tăng giữa giàu và nghèo.', collocations: ['income disparity', 'wealth disparity', 'growing disparity'] },
  { id: 'ielts-soc-004', word: 'assimilate', ipa: '/əˈsɪm.ɪ.leɪt/', pos: 'verb', band: '7.0+', topic: 'Society', meaning: 'To absorb into a wider culture or system', meaningVi: 'Hòa nhập; đồng hóa', example: 'Immigrants often struggle to assimilate into a new culture.', exampleVi: 'Người nhập cư thường gặp khó khăn trong việc hòa nhập vào nền văn hóa mới.', collocations: ['assimilate into society', 'cultural assimilation', 'fully assimilate'] },

  // ── Economics & Work ──
  { id: 'ielts-econ-001', word: 'infrastructure', ipa: '/ˈɪn.frə.strʌk.tʃər/', pos: 'noun', band: '6.5+', topic: 'Economics', meaning: 'The basic physical and organizational structures needed', meaningVi: 'Cơ sở hạ tầng', example: 'Investment in infrastructure is crucial for economic development.', exampleVi: 'Đầu tư vào cơ sở hạ tầng là rất quan trọng cho phát triển kinh tế.', collocations: ['transport infrastructure', 'public infrastructure', 'invest in infrastructure'] },
  { id: 'ielts-econ-002', word: 'outsource', ipa: '/ˈaʊt.sɔːs/', pos: 'verb', band: '7.0+', topic: 'Economics', meaning: 'To obtain goods or services from an outside supplier', meaningVi: 'Thuê ngoài; gia công', example: 'Many companies outsource their customer service operations.', exampleVi: 'Nhiều công ty thuê ngoài hoạt động dịch vụ khách hàng.', collocations: ['outsource production', 'outsource to', 'outsourcing jobs'] },
  { id: 'ielts-econ-003', word: 'subsidise', ipa: '/ˈsʌb.sɪ.daɪz/', pos: 'verb', band: '7.0+', topic: 'Economics', meaning: 'To support financially; to pay part of the cost of', meaningVi: 'Trợ cấp; tài trợ', example: 'The government subsidises public transportation to keep fares low.', exampleVi: 'Chính phủ trợ cấp giao thông công cộng để giữ giá vé thấp.', collocations: ['government subsidies', 'heavily subsidised', 'agricultural subsidies'] },

  // ── Urbanisation ──
  { id: 'ielts-urban-001', word: 'urbanisation', ipa: '/ˌɜː.bən.aɪˈzeɪ.ʃən/', pos: 'noun', band: '6.5+', topic: 'Urbanisation', meaning: 'The process of making an area more urban', meaningVi: 'Đô thị hóa', example: 'Rapid urbanisation has led to overcrowding in many cities.', exampleVi: 'Đô thị hóa nhanh chóng đã dẫn đến quá tải ở nhiều thành phố.', collocations: ['rapid urbanisation', 'rate of urbanisation', 'urbanisation trends'] },
  { id: 'ielts-urban-002', word: 'congestion', ipa: '/kənˈdʒes.tʃən/', pos: 'noun', band: '6.5+', topic: 'Urbanisation', meaning: 'Overcrowding; too many vehicles or people in one place', meaningVi: 'Tắc nghẽn; ùn tắc', example: 'Traffic congestion costs the economy billions each year.', exampleVi: 'Ùn tắc giao thông gây thiệt hại hàng tỷ cho nền kinh tế mỗi năm.', collocations: ['traffic congestion', 'congestion charge', 'reduce congestion'] },
  { id: 'ielts-urban-003', word: 'sprawl', ipa: '/sprɔːl/', pos: 'noun/verb', sublist: 0, band: '7.0+', topic: 'Urbanisation', meaning: 'Uncontrolled expansion of urban areas', meaningVi: 'Sự mở rộng tràn lan (đô thị)', example: 'Urban sprawl has consumed much of the surrounding farmland.', exampleVi: 'Sự mở rộng tràn lan đô thị đã ngốn nhiều đất nông nghiệp xung quanh.', collocations: ['urban sprawl', 'suburban sprawl', 'limit sprawl'] },

  // ── Crime & Law ──
  { id: 'ielts-crime-001', word: 'deterrent', ipa: '/dɪˈter.ənt/', pos: 'noun', band: '7.0+', topic: 'Crime', meaning: 'Something that discourages someone from doing something', meaningVi: 'Sự răn đe; biện pháp ngăn ngừa', example: 'Heavy fines can serve as a deterrent against littering.', exampleVi: 'Phạt nặng có thể đóng vai trò răn đe chống xả rác.', collocations: ['act as a deterrent', 'effective deterrent', 'nuclear deterrent'] },
  { id: 'ielts-crime-002', word: 'rehabilitation', ipa: '/ˌriː.hə.bɪl.ɪˈteɪ.ʃən/', pos: 'noun', band: '7.0+', topic: 'Crime', meaning: 'The process of helping someone return to normal life', meaningVi: 'Phục hồi; cải tạo', example: 'Rehabilitation programs aim to reduce reoffending rates.', exampleVi: 'Các chương trình cải tạo nhằm giảm tỷ lệ tái phạm.', collocations: ['prison rehabilitation', 'rehabilitation programs', 'drug rehabilitation'] },
  { id: 'ielts-crime-003', word: 'recidivism', ipa: '/rɪˈsɪd.ɪ.vɪ.zəm/', pos: 'noun', band: '8.0+', topic: 'Crime', meaning: 'The tendency to relapse into criminal behavior', meaningVi: 'Sự tái phạm', example: 'Education in prisons has been shown to reduce recidivism.', exampleVi: 'Giáo dục trong nhà tù đã được chứng minh là giảm sự tái phạm.', collocations: ['reduce recidivism', 'recidivism rate', 'high recidivism'] },
];

// ─── Public API ──────────────────────────────────────────────────────

export const AWL_SUBLISTS: Record<number, AWLSublist> = {
  1: sublist1,
  2: sublist2,
};

/** All AWL words flattened */
export function getAllAWLWords(): AWLWord[] {
  return Object.values(AWL_SUBLISTS).flat();
}

/** Get AWL words by sublist number */
export function getAWLSublist(n: number): AWLSublist {
  return AWL_SUBLISTS[n] ?? [];
}

/** Get all IELTS topic vocabulary */
export function getIELTSTopicVocabulary(): readonly IELTSTopicVocab[] {
  return IELTS_TOPIC_VOCABULARY;
}

/** Get IELTS topic vocabulary by topic */
export function getIELTSVocabularyByTopic(topic: string): IELTSTopicVocab[] {
  return IELTS_TOPIC_VOCABULARY.filter(v => v.topic === topic);
}

/** All unique IELTS topics */
export function getIELTSTopics(): string[] {
  return [...new Set(IELTS_TOPIC_VOCABULARY.map(v => v.topic))];
}

/** Total word count */
export function getIELTSVocabStats() {
  const awlCount = getAllAWLWords().length;
  const topicCount = IELTS_TOPIC_VOCABULARY.length;
  return {
    awlHeadwords: awlCount,
    topicWords: topicCount,
    totalWords: awlCount + topicCount,
    sublists: Object.keys(AWL_SUBLISTS).length,
    topics: getIELTSTopics().length,
  };
}
