import type { KoreanTopikLessonDescriptor, KoreanTopikLessonId, KoreanTopikSkill } from './koreanTopikRegistry';

export interface HangulRomanization { hangul: string; romanization: string; }
export interface KoreanVocabularyCard extends HangulRomanization { id: `ko:topik:topik1:vocab:${string}`; meaningVi: string; partOfSpeech: string; example: HangulRomanization & { translationVi: string }; }
export interface KoreanVocabularyDeck { id: Extract<KoreanTopikLessonId, `ko:topik:topik1:vocabulary:${string}`>; title: string; cards: readonly KoreanVocabularyCard[]; }
export interface KoreanQuestion { id: string; prompt: HangulRomanization; choices: readonly Readonly<{ id: string; text: HangulRomanization; meaningVi: string }>[]; correctChoiceId: string; analysis: string; }
export interface KoreanLessonContent { id: Exclude<KoreanTopikLessonId, `ko:topik:topik1:vocabulary:${string}`>; skill: Exclude<KoreanTopikSkill, 'vocabulary'>; title: string; explanation: readonly string[]; examples: readonly (HangulRomanization & { translationVi: string })[]; questions: readonly KoreanQuestion[]; passage?: HangulRomanization & { translationVi: string }; }

const card = (id: string, hangul: string, romanization: string, meaningVi: string, partOfSpeech: string, exampleHangul: string, exampleRomanization: string, translationVi: string): KoreanVocabularyCard => ({ id: `ko:topik:topik1:vocab:${id}`, hangul, romanization, meaningVi, partOfSpeech, example: { hangul: exampleHangul, romanization: exampleRomanization, translationVi } });

const cards: readonly KoreanVocabularyCard[] = [
  card('001','안녕하세요','annyeonghaseyo','xin chào','câu chào','안녕하세요, 민수 씨.','annyeonghaseyo, Minsu ssi.','Xin chào, bạn Minsu.'), card('002','감사합니다','gamsahamnida','cảm ơn','câu cảm ơn','감사합니다.','gamsahamnida.','Cảm ơn.'),
  card('003','저','jeo','tôi (khiêm nhường)','đại từ','저는 학생이에요.','jeoneun haksaeng-ieyo.','Tôi là học sinh.'), card('004','이름','ireum','tên','danh từ','이름이 뭐예요?','ireumi mwoyeyo?','Tên bạn là gì?'),
  card('005','학생','haksaeng','học sinh; sinh viên','danh từ','저는 학생이에요.','jeoneun haksaeng-ieyo.','Tôi là học sinh.'), card('006','선생님','seonsaengnim','giáo viên','danh từ','선생님은 친절해요.','seonsaengnimeun chinjeolhaeyo.','Giáo viên tốt bụng.'),
  card('007','친구','chingu','bạn','danh từ','친구예요.','chinguyeyo.','Là bạn.'), card('008','한국','Hanguk','Hàn Quốc','danh từ riêng','한국 사람이에요.','Hanguk saramieyo.','Là người Hàn Quốc.'),
  card('009','사람','saram','người','danh từ','좋은 사람이에요.','joeun saramieyo.','Là người tốt.'), card('010','나라','nara','đất nước','danh từ','어느 나라예요?','eoneu narayeyo?','Là nước nào?'),
  card('011','네','ne','vâng','thán từ','네, 맞아요.','ne, majayo.','Vâng, đúng vậy.'), card('012','아니요','aniyo','không','thán từ','아니요, 학생이 아니에요.','aniyo, haksaengi anieyo.','Không, không phải học sinh.'),
  card('013','책','chaek','sách','danh từ','책이 있어요.','chaegi isseoyo.','Có sách.'), card('014','학교','hakgyo','trường học','danh từ','학교에 가요.','hakgyoe gayo.','Đi đến trường.'),
  card('015','물','mul','nước','danh từ','물을 마셔요.','mureul masyeoyo.','Uống nước.'), card('016','커피','keopi','cà phê','danh từ','커피를 좋아해요.','keopireul joahaeyo.','Thích cà phê.'),
  card('017','좋아요','joayo','tốt; thích','tính từ','오늘 날씨가 좋아요.','oneul nalssiga joayo.','Hôm nay thời tiết đẹp.'), card('018','뭐','mwo','gì','đại từ nghi vấn','뭐예요?','mwoyeyo?','Là gì?'),
  card('019','이','i','này','định từ','이 책이에요.','i chaegieyo.','Đây là sách.'), card('020','그','geu','đó','định từ','그 사람은 친구예요.','geu sarameun chinguyeyo.','Người đó là bạn.'),
  card('021','오늘','oneul','hôm nay','danh từ thời gian','오늘 학교에 가요.','oneul hakgyoe gayo.','Hôm nay đi học.'), card('022','내일','naeil','ngày mai','danh từ thời gian','내일 만나요.','naeil mannayo.','Ngày mai gặp.'),
  card('023','지금','jigeum','bây giờ','trạng từ','지금 공부해요.','jigeum gongbuhaeyo.','Bây giờ học.'), card('024','아침','achim','buổi sáng','danh từ','아침에 커피를 마셔요.','achime keopireul masyeoyo.','Buổi sáng uống cà phê.'),
  card('025','저녁','jeonyeok','buổi tối','danh từ','저녁에 집에 가요.','jeonyeoge jibe gayo.','Buổi tối về nhà.'), card('026','집','jip','nhà','danh từ','집에 있어요.','jibe isseoyo.','Ở nhà.'),
  card('027','가다','gada','đi','động từ','학교에 가요.','hakgyoe gayo.','Đi đến trường.'), card('028','오다','oda','đến','động từ','친구가 와요.','chinguga wayo.','Bạn đến.'),
  card('029','공부하다','gongbuhada','học','động từ','한국어를 공부해요.','hangugeoreul gongbuhaeyo.','Học tiếng Hàn.'), card('030','먹다','meokda','ăn','động từ','밥을 먹어요.','babeul meogeoyo.','Ăn cơm.'),
  card('031','마시다','masida','uống','động từ','물을 마셔요.','mureul masyeoyo.','Uống nước.'), card('032','보다','boda','xem','động từ','책을 봐요.','chaegeul bwayo.','Đọc/xem sách.'),
  card('033','크다','keuda','to; lớn','tính từ','학교가 커요.','hakgyoga keoyo.','Trường lớn.'), card('034','작다','jakda','nhỏ','tính từ','집이 작아요.','jibi jagayo.','Nhà nhỏ.'),
  card('035','많다','manta','nhiều','tính từ','친구가 많아요.','chinguga manayo.','Có nhiều bạn.'), card('036','하다','hada','làm','động từ','무엇을 해요?','mueoseul haeyo?','Làm gì?'),
  card('037','한국어','hangugeo','tiếng Hàn','danh từ','한국어를 공부해요.','hangugeoreul gongbuhaeyo.','Học tiếng Hàn.'), card('038','밥','bap','cơm; bữa ăn','danh từ','밥을 먹어요.','babeul meogeoyo.','Ăn cơm.'),
  card('039','만나다','mannada','gặp','động từ','친구를 만나요.','chingureul mannayo.','Gặp bạn.'), card('040','그리고','geurigo','và; rồi','liên từ','학교에 가요. 그리고 공부해요.','hakgyoe gayo. geurigo gongbuhaeyo.','Đi học rồi học bài.'),
];

export const KOREAN_TOPIK1_VOCABULARY_DECKS: readonly KoreanVocabularyDeck[] = [
  { id: 'ko:topik:topik1:vocabulary:foundations-01', title: 'Từ nền tảng', cards: cards.slice(0, 20) },
  { id: 'ko:topik:topik1:vocabulary:daily-life-02', title: 'Sinh hoạt hằng ngày', cards: cards.slice(20, 40) },
] as const;

const choice = (id: string, hangul: string, romanization: string, meaningVi: string) => ({ id, text: { hangul, romanization }, meaningVi });
export const KOREAN_TOPIK1_LESSONS: readonly KoreanLessonContent[] = [
  { id:'ko:topik:topik1:hangul:foundations-01', skill:'hangul', title:'Phụ âm, nguyên âm và âm tiết', explanation:['Hangul ghép phụ âm đầu với nguyên âm để tạo âm tiết. Ví dụ ㄱ + ㅏ tạo 가 (ga).','Bài này là nhận diện chữ cái cố định; chưa đánh giá viết tay hoặc phát âm bằng microphone.'], examples:[{hangul:'ㄱ + ㅏ = 가',romanization:'g + a = ga',translationVi:'Phụ âm ㄱ kết hợp nguyên âm ㅏ.'}], questions:[{id:'hangul-q1',prompt:{hangul:'가',romanization:'ga'},choices:[choice('a','ga','ga','ga'),choice('b','na','na','na'),choice('c','da','da','da')],correctChoiceId:'a',analysis:'가 gồm ㄱ + ㅏ, đọc gần là ga.'},{id:'hangul-q2',prompt:{hangul:'나',romanization:'na'},choices:[choice('a','ma','ma','ma'),choice('b','na','na','na'),choice('c','sa','sa','sa')],correctChoiceId:'b',analysis:'나 gồm ㄴ + ㅏ, đọc là na.'}] },
  { id:'ko:topik:topik1:pronunciation:batchim-01', skill:'pronunciation', title:'Batchim cơ bản', explanation:['Batchim là phụ âm cuối âm tiết. Trong 책 (chaek), ㄱ là batchim.','Bài học chỉ nhận diện chính tả/romanization đã biên soạn, không tuyên bố chấm phát âm.'], examples:[{hangul:'책',romanization:'chaek',translationVi:'sách; ㄱ là phụ âm cuối'}], questions:[{id:'batchim-q1',prompt:{hangul:'책',romanization:'chaek'},choices:[choice('a','ㄱ','giyeok','batchim ㄱ'),choice('b','ㅏ','a','nguyên âm ㅏ'),choice('c','ㅊ','chieut','phụ âm đầu')],correctChoiceId:'a',analysis:'Trong 책, thành phần cuối là ㄱ nên đây là batchim.'}] },
  { id:'ko:topik:topik1:grammar:ieyo-yeyo-01', skill:'grammar', title:'이에요 / 예요', explanation:['Nối danh từ với 이에요 sau phụ âm cuối và 예요 sau nguyên âm cuối. 학생 + 이에요 → 학생이에요.','Đây là đuôi lịch sự hiện tại để giới thiệu hoặc xác định danh từ.'], examples:[{hangul:'저는 학생이에요.',romanization:'jeoneun haksaeng-ieyo.',translationVi:'Tôi là học sinh.'},{hangul:'저는 민수예요.',romanization:'jeoneun Minsu-yeyo.',translationVi:'Tôi là Minsu.'}], questions:[{id:'ieyo-q1',prompt:{hangul:'저는 학생___ .',romanization:'jeoneun haksaeng___.'},choices:[choice('a','이에요','ieyo','là (sau phụ âm cuối)'),choice('b','예요','yeyo','là (sau nguyên âm cuối)'),choice('c','가요','gayo','đi')],correctChoiceId:'a',analysis:'학생 kết thúc bằng batchim ㄱ nên dùng 이에요.'},{id:'ieyo-q2',prompt:{hangul:'저는 민수___ .',romanization:'jeoneun Minsu___.'},choices:[choice('a','이에요','ieyo','là'),choice('b','예요','yeyo','là (sau nguyên âm cuối)'),choice('c','아니요','aniyo','không')],correctChoiceId:'b',analysis:'민수 kết thúc bằng nguyên âm ㅜ nên dùng 예요.'}] },
  { id:'ko:topik:topik1:reading:introduction-01', skill:'reading', title:'Giới thiệu bản thân', explanation:['Đọc cả đoạn, sau đó tìm tên và thông tin được nêu trực tiếp. Không suy đoán từ kiến thức ngoài bài.'], examples:[], passage:{hangul:'안녕하세요. 저는 민수예요. 저는 한국 학생이에요. 이 사람은 제 친구 수진이에요.',romanization:'annyeonghaseyo. jeoneun Minsu-yeyo. jeoneun Hanguk haksaeng-ieyo. i sarameun je chingu Sujin-ieyo.',translationVi:'Xin chào. Tôi là Minsu. Tôi là học sinh Hàn Quốc. Người này là bạn Sujin của tôi.'}, questions:[{id:'intro-read-q1',prompt:{hangul:'민수는 누구예요?',romanization:'Minsuneun nuguyeyo?'},choices:[choice('a','한국 학생','Hanguk haksaeng','học sinh Hàn Quốc'),choice('b','선생님','seonsaengnim','giáo viên'),choice('c','수진','Sujin','Sujin')],correctChoiceId:'a',analysis:'Đoạn văn nói trực tiếp “저는 한국 학생이에요”.'},{id:'intro-read-q2',prompt:{hangul:'수진은 민수의 누구예요?',romanization:'Sujineun Minsuu nuguyeyo?'},choices:[choice('a','친구','chingu','bạn'),choice('b','학생','haksaeng','học sinh'),choice('c','책','chaek','sách')],correctChoiceId:'a',analysis:'Câu cuối xác định 수진 là 제 친구, tức bạn của Minsu.'}] },
  { id:'ko:topik:topik1:grammar:topic-eun-neun-02', skill:'grammar', title:'Tiểu từ chủ đề 은 / 는', explanation:['은/는 đánh dấu chủ đề: dùng 은 sau phụ âm cuối, 는 sau nguyên âm cuối. 학생은…; 저는….','Tiểu từ này không tự dịch từng chữ mà hướng người nghe đến chủ đề đang nói.'], examples:[{hangul:'저는 학생이에요.',romanization:'jeoneun haksaeng-ieyo.',translationVi:'Còn tôi thì là học sinh.'},{hangul:'책은 커요.',romanization:'chaegeun keoyo.',translationVi:'Còn sách thì lớn.'}], questions:[{id:'topic-q1',prompt:{hangul:'저___ 학생이에요.',romanization:'jeo___ haksaeng-ieyo.'},choices:[choice('a','는','neun','tiểu từ sau nguyên âm'),choice('b','은','eun','tiểu từ sau phụ âm'),choice('c','을','eul','tiểu từ tân ngữ')],correctChoiceId:'a',analysis:'저 kết thúc bằng nguyên âm ㅓ nên dùng 는.'},{id:'topic-q2',prompt:{hangul:'책___ 커요.',romanization:'chaek___ keoyo.'},choices:[choice('a','는','neun','tiểu từ sau nguyên âm'),choice('b','은','eun','tiểu từ sau phụ âm'),choice('c','가','ga','tiểu từ chủ ngữ')],correctChoiceId:'b',analysis:'책 có batchim ㄱ nên dùng 은.'}] },
  { id:'ko:topik:topik1:reading:daily-life-02', skill:'reading', title:'Một ngày đi học', explanation:['Đọc mốc thời gian và hoạt động rồi đối chiếu từng câu hỏi với câu chứa bằng chứng trực tiếp.'], examples:[], passage:{hangul:'민수는 아침에 학교에 가요. 학교에서 한국어를 공부해요. 저녁에는 집에 가요. 그리고 친구를 만나요.',romanization:'Minsuneun achime hakgyoe gayo. hakgyoeseo hangugeoreul gongbuhaeyo. jeonyeog-eneun jibe gayo. geurigo chingureul mannayo.',translationVi:'Minsu đi đến trường vào buổi sáng. Ở trường, bạn ấy học tiếng Hàn. Buổi tối bạn ấy về nhà. Sau đó gặp bạn.'}, questions:[{id:'daily-read-q1',prompt:{hangul:'민수는 아침에 어디에 가요?',romanization:'Minsuneun achime eodie gayo?'},choices:[choice('a','학교','hakgyo','trường học'),choice('b','집','jip','nhà'),choice('c','나라','nara','đất nước')],correctChoiceId:'a',analysis:'Câu đầu nói rõ 아침에 학교에 가요: buổi sáng đi tới trường.'},{id:'daily-read-q2',prompt:{hangul:'민수는 저녁에 무엇을 해요?',romanization:'Minsuneun jeonyeoge mueoseul haeyo?'},choices:[choice('a','집에 가요','jibe gayo','về nhà'),choice('b','학교에 가요','hakgyoe gayo','đi học'),choice('c','커피를 마셔요','keopireul masyeoyo','uống cà phê')],correctChoiceId:'a',analysis:'Đoạn nói 저녁에는 집에 가요, tức buổi tối Minsu về nhà.'}] },
] as const;

const hasRomanization = (value: string) => /[a-z]/iu.test(value);
export function validateKoreanTopikContent(decks: readonly KoreanVocabularyDeck[], lessons: readonly KoreanLessonContent[], registry: readonly KoreanTopikLessonDescriptor[]): string[] {
  const issues: string[] = []; const ids = new Set<string>(); const registryIds = new Set(registry.map((item) => item.id));
  for (const deck of decks) { if (!registryIds.has(deck.id)) issues.push(`deck missing registry: ${deck.id}`); if (deck.cards.length !== 20) issues.push(`invalid deck size: ${deck.id}`); for (const item of deck.cards) { if (ids.has(item.id)) issues.push(`duplicate content id: ${item.id}`); ids.add(item.id); if (!item.hangul.trim() || !item.meaningVi.trim() || !hasRomanization(item.romanization)) issues.push(`invalid vocabulary: ${item.id}`); } }
  for (const lesson of lessons) { if (!registryIds.has(lesson.id)) issues.push(`lesson missing registry: ${lesson.id}`); if (ids.has(lesson.id)) issues.push(`duplicate content id: ${lesson.id}`); ids.add(lesson.id); if (!lesson.title.trim() || lesson.explanation.length === 0 || lesson.questions.length === 0) issues.push(`incomplete lesson: ${lesson.id}`); const questionIds = new Set<string>(); for (const question of lesson.questions) { if (questionIds.has(question.id)) issues.push(`duplicate question id: ${lesson.id}:${question.id}`); questionIds.add(question.id); if (!question.prompt.hangul.trim() || !hasRomanization(question.prompt.romanization) || !question.analysis.trim()) issues.push(`invalid question: ${lesson.id}:${question.id}`); if (!question.choices.some((item) => item.id === question.correctChoiceId)) issues.push(`missing answer: ${lesson.id}:${question.id}`); if (new Set(question.choices.map((item) => item.id)).size !== question.choices.length) issues.push(`duplicate choice id: ${lesson.id}:${question.id}`); } }
  for (const descriptor of registry) if (descriptor.skill !== 'vocabulary' && !lessons.some((lesson) => lesson.id === descriptor.id)) issues.push(`registry missing lesson: ${descriptor.id}`);
  return [...new Set(issues)];
}
