export interface VocabularyItem {
  id: string;
  word: string;
  partOfSpeech: 'noun' | 'verb' | 'adjective' | 'adverb' | 'phrase' | 'preposition' | 'conjunction';
  level: 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';
  meaning: string;
  example: string;
  translation: string;
  pronunciation: string;
  tags: string[];
  collocations?: string[];
  synonyms?: string[];
  commonMistakes?: string;
}

export const vocabularyBank: VocabularyItem[] = [
  // ═══ A1 — Basics & Everyday ═══
  { id: 'v1', word: 'hello', partOfSpeech: 'noun', level: 'A1', meaning: 'a greeting used when meeting someone', example: 'Hello, how are you today?', translation: 'Xin chào', pronunciation: '/həˈləʊ/', tags: ['greetings'], collocations: ['say hello', 'hello there'], synonyms: ['hi', 'hey'] },
  { id: 'v2', word: 'family', partOfSpeech: 'noun', level: 'A1', meaning: 'a group of people related to each other', example: 'I have a big family.', translation: 'Gia đình', pronunciation: '/ˈfæm.əl.i/', tags: ['people', 'basics'], collocations: ['family member', 'start a family'] },
  { id: 'v3', word: 'water', partOfSpeech: 'noun', level: 'A1', meaning: 'a clear liquid essential for life', example: 'Can I have a glass of water?', translation: 'Nước', pronunciation: '/ˈwɔː.tər/', tags: ['food', 'basics'], collocations: ['drink water', 'water bottle', 'hot water'] },
  { id: 'v4', word: 'eat', partOfSpeech: 'verb', level: 'A1', meaning: 'to put food into the mouth and swallow it', example: 'I eat breakfast at 7 AM.', translation: 'Ăn', pronunciation: '/iːt/', tags: ['food', 'basics', 'daily'], collocations: ['eat lunch', 'eat out'], commonMistakes: 'Past tense is "ate", not "eated"' },
  { id: 'v5', word: 'school', partOfSpeech: 'noun', level: 'A1', meaning: 'a place where children go to learn', example: 'My school starts at 8 o\'clock.', translation: 'Trường học', pronunciation: '/skuːl/', tags: ['education', 'basics'], collocations: ['go to school', 'school bus', 'after school'] },
  { id: 'v6', word: 'good', partOfSpeech: 'adjective', level: 'A1', meaning: 'of a high quality or standard', example: 'This is a good book.', translation: 'Tốt', pronunciation: '/ɡʊd/', tags: ['basics', 'description'], synonyms: ['great', 'fine', 'nice'], commonMistakes: 'Use "well" as adverb: "She sings well" not "She sings good"' },
  { id: 'v7', word: 'big', partOfSpeech: 'adjective', level: 'A1', meaning: 'of considerable size or extent', example: 'They live in a big house.', translation: 'To, lớn', pronunciation: '/bɪɡ/', tags: ['description', 'basics'], synonyms: ['large', 'huge'], collocations: ['big deal', 'big city'] },
  { id: 'v8', word: 'work', partOfSpeech: 'verb', level: 'A1', meaning: 'to do a job or activity to earn money', example: 'I work in an office.', translation: 'Làm việc', pronunciation: '/wɜːk/', tags: ['job', 'daily'], collocations: ['work hard', 'go to work', 'work from home'] },
  { id: 'v9', word: 'friend', partOfSpeech: 'noun', level: 'A1', meaning: 'a person you know well and like', example: 'She is my best friend.', translation: 'Bạn bè', pronunciation: '/frend/', tags: ['people', 'basics'], collocations: ['best friend', 'make friends', 'close friend'] },
  { id: 'v10', word: 'happy', partOfSpeech: 'adjective', level: 'A1', meaning: 'feeling pleasure and enjoyment', example: 'I am happy to see you.', translation: 'Hạnh phúc, vui', pronunciation: '/ˈhæp.i/', tags: ['emotion', 'basics'], synonyms: ['glad', 'pleased', 'joyful'], collocations: ['happy birthday', 'happy ending'] },
  { id: 'v11', word: 'house', partOfSpeech: 'noun', level: 'A1', meaning: 'a building for people to live in', example: 'We bought a new house.', translation: 'Nhà', pronunciation: '/haʊs/', tags: ['home', 'basics'], collocations: ['house price', 'move house'] },
  { id: 'v12', word: 'book', partOfSpeech: 'noun', level: 'A1', meaning: 'a set of pages with writing or pictures', example: 'I am reading a book about history.', translation: 'Sách', pronunciation: '/bʊk/', tags: ['education', 'basics'], collocations: ['book a ticket', 'textbook', 'read a book'] },

  // ═══ A2 — Elementary ═══
  { id: 'v13', word: 'improve', partOfSpeech: 'verb', level: 'A2', meaning: 'to make something better', example: 'I want to improve my English skills.', translation: 'Cải thiện', pronunciation: '/ɪmˈpruːv/', tags: ['learning', 'growth'], collocations: ['improve dramatically', 'room for improvement'], synonyms: ['enhance', 'develop'] },
  { id: 'v14', word: 'language', partOfSpeech: 'noun', level: 'A2', meaning: 'the method of human communication using words', example: 'English is a widely spoken language.', translation: 'Ngôn ngữ', pronunciation: '/ˈlæŋ.ɡwɪdʒ/', tags: ['education', 'communication'], collocations: ['body language', 'foreign language', 'language barrier'] },
  { id: 'v15', word: 'describe', partOfSpeech: 'verb', level: 'A2', meaning: 'to say what something or someone is like', example: 'Can you describe your hometown?', translation: 'Mô tả', pronunciation: '/dɪˈskraɪb/', tags: ['communication', 'ielts'], collocations: ['describe in detail', 'hard to describe'] },
  { id: 'v16', word: 'weather', partOfSpeech: 'noun', level: 'A2', meaning: 'the temperature and other atmospheric conditions', example: 'The weather is sunny today.', translation: 'Thời tiết', pronunciation: '/ˈweð.ər/', tags: ['nature', 'daily'], collocations: ['weather forecast', 'bad weather', 'weather conditions'] },
  { id: 'v17', word: 'travel', partOfSpeech: 'verb', level: 'A2', meaning: 'to go from one place to another', example: 'I love to travel to new countries.', translation: 'Du lịch', pronunciation: '/ˈtræv.əl/', tags: ['travel', 'ielts'], collocations: ['travel abroad', 'travel agent', 'travel by train'], synonyms: ['journey', 'trip'] },
  { id: 'v18', word: 'expensive', partOfSpeech: 'adjective', level: 'A2', meaning: 'costing a lot of money', example: 'This restaurant is too expensive.', translation: 'Đắt', pronunciation: '/ɪkˈspen.sɪv/', tags: ['money', 'shopping'], synonyms: ['costly', 'pricey'], commonMistakes: 'Don\'t say "more expensive" — it\'s already comparative in some contexts' },
  { id: 'v19', word: 'neighbour', partOfSpeech: 'noun', level: 'A2', meaning: 'a person who lives next door or nearby', example: 'Our neighbours are very friendly.', translation: 'Hàng xóm', pronunciation: '/ˈneɪ.bər/', tags: ['people', 'community'], collocations: ['next-door neighbour', 'neighbouring country'] },
  { id: 'v20', word: 'worried', partOfSpeech: 'adjective', level: 'A2', meaning: 'feeling anxious about problems or unpleasant things', example: 'I\'m worried about the exam.', translation: 'Lo lắng', pronunciation: '/ˈwʌr.id/', tags: ['emotion'], synonyms: ['anxious', 'concerned'], collocations: ['worried about', 'worried sick'] },
  { id: 'v21', word: 'restaurant', partOfSpeech: 'noun', level: 'A2', meaning: 'a place where you pay to sit and eat a meal', example: 'Let\'s go to a restaurant tonight.', translation: 'Nhà hàng', pronunciation: '/ˈres.tər.ɒnt/', tags: ['food', 'places'], collocations: ['fast-food restaurant', 'book a restaurant'] },
  { id: 'v22', word: 'exciting', partOfSpeech: 'adjective', level: 'A2', meaning: 'causing great enthusiasm and eagerness', example: 'The movie was really exciting.', translation: 'Hào hứng, thú vị', pronunciation: '/ɪkˈsaɪ.tɪŋ/', tags: ['emotion', 'entertainment'], synonyms: ['thrilling', 'exhilarating'], commonMistakes: '"Exciting" describes the thing; "excited" describes the person' },

  // ═══ B1 — Intermediate ═══
  { id: 'v23', word: 'environment', partOfSpeech: 'noun', level: 'B1', meaning: 'the natural world around us', example: 'We must protect the environment for future generations.', translation: 'Môi trường', pronunciation: '/ɪnˈvaɪ.rən.mənt/', tags: ['nature', 'ielts'], collocations: ['protect the environment', 'working environment'], synonyms: ['surroundings', 'ecosystem'] },
  { id: 'v24', word: 'opportunity', partOfSpeech: 'noun', level: 'B1', meaning: 'a favourable time or situation for doing something', example: 'This job is a great opportunity.', translation: 'Cơ hội', pronunciation: '/ˌɒp.əˈtʃuː.nə.ti/', tags: ['career', 'ielts'], collocations: ['job opportunity', 'miss an opportunity', 'equal opportunities'] },
  { id: 'v25', word: 'experience', partOfSpeech: 'noun', level: 'B1', meaning: 'knowledge gained from doing something', example: 'She has 10 years of teaching experience.', translation: 'Kinh nghiệm', pronunciation: '/ɪkˈspɪə.ri.əns/', tags: ['career', 'ielts'], collocations: ['work experience', 'life experience', 'learning experience'] },
  { id: 'v26', word: 'technology', partOfSpeech: 'noun', level: 'B1', meaning: 'the application of scientific knowledge for practical purposes', example: 'Technology has changed the way we communicate.', translation: 'Công nghệ', pronunciation: '/tekˈnɒl.ə.dʒi/', tags: ['technology', 'ielts'], collocations: ['information technology', 'modern technology'] },
  { id: 'v27', word: 'pollution', partOfSpeech: 'noun', level: 'B1', meaning: 'the presence of harmful substances in the environment', example: 'Air pollution is a serious problem in big cities.', translation: 'Ô nhiễm', pronunciation: '/pəˈluː.ʃən/', tags: ['nature', 'ielts'], collocations: ['air pollution', 'water pollution', 'reduce pollution'] },
  { id: 'v28', word: 'recommend', partOfSpeech: 'verb', level: 'B1', meaning: 'to suggest something as being good or suitable', example: 'I recommend this book to all learners.', translation: 'Giới thiệu, đề xuất', pronunciation: '/ˌrek.əˈmend/', tags: ['communication'], collocations: ['highly recommend', 'recommend doing something'], commonMistakes: 'Use gerund after: "I recommend reading" not "I recommend to read"' },
  { id: 'v29', word: 'advantage', partOfSpeech: 'noun', level: 'B1', meaning: 'a condition that puts someone in a favourable position', example: 'Speaking two languages is a great advantage.', translation: 'Lợi thế', pronunciation: '/ədˈvɑːn.tɪdʒ/', tags: ['ielts', 'academic'], collocations: ['take advantage of', 'competitive advantage'], synonyms: ['benefit', 'plus'] },
  { id: 'v30', word: 'confident', partOfSpeech: 'adjective', level: 'B1', meaning: 'feeling sure about your own ability', example: 'She is confident about passing the exam.', translation: 'Tự tin', pronunciation: '/ˈkɒn.fɪ.dənt/', tags: ['personality', 'ielts'], collocations: ['self-confident', 'confident in'], commonMistakes: '"Confident" (adjective) vs "confidant" (a trusted person)' },
  { id: 'v31', word: 'achieve', partOfSpeech: 'verb', level: 'B1', meaning: 'to successfully reach a goal', example: 'She achieved her target IELTS band score.', translation: 'Đạt được', pronunciation: '/əˈtʃiːv/', tags: ['success', 'ielts'], collocations: ['achieve a goal', 'achieve success'], synonyms: ['accomplish', 'attain'] },
  { id: 'v32', word: 'community', partOfSpeech: 'noun', level: 'B1', meaning: 'a group of people living in the same area or sharing interests', example: 'The local community organised a clean-up event.', translation: 'Cộng đồng', pronunciation: '/kəˈmjuː.nə.ti/', tags: ['society', 'ielts'], collocations: ['local community', 'online community', 'community service'] },
  { id: 'v33', word: 'government', partOfSpeech: 'noun', level: 'B1', meaning: 'the group of people who officially control a country', example: 'The government announced new education policies.', translation: 'Chính phủ', pronunciation: '/ˈɡʌv.ən.mənt/', tags: ['politics', 'ielts'], collocations: ['local government', 'government policy'] },
  { id: 'v34', word: 'transport', partOfSpeech: 'noun', level: 'B1', meaning: 'a system for carrying people or goods from place to place', example: 'Public transport is very efficient in this city.', translation: 'Giao thông', pronunciation: '/ˈtræn.spɔːt/', tags: ['travel', 'ielts'], collocations: ['public transport', 'means of transport'] },

  // ═══ B2 — Upper Intermediate ═══
  { id: 'v35', word: 'sustainable', partOfSpeech: 'adjective', level: 'B2', meaning: 'able to continue over time without harming the environment', example: 'We need sustainable energy sources.', translation: 'Bền vững', pronunciation: '/səˈsteɪ.nə.bəl/', tags: ['nature', 'academic', 'ielts'], collocations: ['sustainable development', 'sustainable energy'] },
  { id: 'v36', word: 'significant', partOfSpeech: 'adjective', level: 'B2', meaning: 'large or important enough to have an effect', example: 'There has been a significant increase in online learning.', translation: 'Đáng kể', pronunciation: '/sɪɡˈnɪf.ɪ.kənt/', tags: ['academic', 'ielts'], collocations: ['significant impact', 'statistically significant'], synonyms: ['considerable', 'notable'] },
  { id: 'v37', word: 'consequence', partOfSpeech: 'noun', level: 'B2', meaning: 'a result of a particular action or situation', example: 'Climate change has serious consequences.', translation: 'Hậu quả', pronunciation: '/ˈkɒn.sɪ.kwəns/', tags: ['academic', 'ielts'], collocations: ['as a consequence', 'face the consequences'], synonyms: ['result', 'outcome'] },
  { id: 'v38', word: 'influence', partOfSpeech: 'noun', level: 'B2', meaning: 'the power to affect people\'s thinking or actions', example: 'Social media has a huge influence on young people.', translation: 'Ảnh hưởng', pronunciation: '/ˈɪn.flu.əns/', tags: ['society', 'ielts'], collocations: ['under the influence', 'have an influence on'], synonyms: ['impact', 'effect'] },
  { id: 'v39', word: 'complicated', partOfSpeech: 'adjective', level: 'B2', meaning: 'consisting of many connected parts, difficult to understand', example: 'The instructions are too complicated.', translation: 'Phức tạp', pronunciation: '/ˈkɒm.plɪ.keɪ.tɪd/', tags: ['description'], synonyms: ['complex', 'intricate'], commonMistakes: '"Complicated" and "complex" are similar but "complex" is more neutral' },
  { id: 'v40', word: 'controversial', partOfSpeech: 'adjective', level: 'B2', meaning: 'causing strong disagreement among people', example: 'The policy is highly controversial.', translation: 'Gây tranh cãi', pronunciation: '/ˌkɒn.trəˈvɜː.ʃəl/', tags: ['politics', 'ielts', 'academic'], collocations: ['controversial issue', 'controversial decision'] },
  { id: 'v41', word: 'contribute', partOfSpeech: 'verb', level: 'B2', meaning: 'to give something in order to help achieve something', example: 'Everyone can contribute to protecting the environment.', translation: 'Đóng góp', pronunciation: '/kənˈtrɪb.juːt/', tags: ['academic', 'ielts'], collocations: ['contribute to', 'make a contribution'], commonMistakes: 'Always "contribute TO something" not "contribute for"' },
  { id: 'v42', word: 'obviously', partOfSpeech: 'adverb', level: 'B2', meaning: 'in a way that is easy to understand or see', example: 'She was obviously tired after the long journey.', translation: 'Rõ ràng', pronunciation: '/ˈɒb.vi.əs.li/', tags: ['discourse', 'academic'], synonyms: ['clearly', 'evidently'] },
  { id: 'v43', word: 'perspective', partOfSpeech: 'noun', level: 'B2', meaning: 'a particular way of thinking about something', example: 'Let\'s look at this from a different perspective.', translation: 'Góc nhìn, quan điểm', pronunciation: '/pəˈspek.tɪv/', tags: ['academic', 'ielts'], collocations: ['from a different perspective', 'gain perspective'], synonyms: ['viewpoint', 'point of view'] },
  { id: 'v44', word: 'approximately', partOfSpeech: 'adverb', level: 'B2', meaning: 'close to an exact amount or number but not completely', example: 'The project will take approximately three months.', translation: 'Xấp xỉ, khoảng', pronunciation: '/əˈprɒk.sɪ.mət.li/', tags: ['academic', 'ielts'], synonyms: ['roughly', 'about', 'around'] },
  { id: 'v45', word: 'emphasize', partOfSpeech: 'verb', level: 'B2', meaning: 'to give special importance to something', example: 'The teacher emphasized the importance of practice.', translation: 'Nhấn mạnh', pronunciation: '/ˈem.fə.saɪz/', tags: ['academic', 'ielts'], collocations: ['emphasize the importance', 'strongly emphasize'], synonyms: ['stress', 'highlight'] },

  // ═══ C1 — Advanced ═══
  { id: 'v46', word: 'ubiquitous', partOfSpeech: 'adjective', level: 'C1', meaning: 'present, appearing, or found everywhere', example: 'Smartphones have become ubiquitous in modern society.', translation: 'Phổ biến, có mặt khắp nơi', pronunciation: '/juːˈbɪk.wɪ.təs/', tags: ['technology', 'ielts', 'advanced'], synonyms: ['omnipresent', 'pervasive'] },
  { id: 'v47', word: 'paradigm', partOfSpeech: 'noun', level: 'C1', meaning: 'a typical example or model of something', example: 'The internet created a new paradigm for communication.', translation: 'Mô hình, khuôn mẫu', pronunciation: '/ˈpær.ə.daɪm/', tags: ['academic', 'ielts'], collocations: ['paradigm shift', 'new paradigm'] },
  { id: 'v48', word: 'unprecedented', partOfSpeech: 'adjective', level: 'C1', meaning: 'never having happened before', example: 'The pandemic caused unprecedented disruption.', translation: 'Chưa từng có', pronunciation: '/ʌnˈpres.ɪ.den.tɪd/', tags: ['academic', 'ielts'], collocations: ['unprecedented growth', 'unprecedented times'] },
  { id: 'v49', word: 'exacerbate', partOfSpeech: 'verb', level: 'C1', meaning: 'to make something worse', example: 'The drought exacerbated the food shortage.', translation: 'Làm trầm trọng thêm', pronunciation: '/ɪɡˈzæs.ər.beɪt/', tags: ['academic', 'ielts'], synonyms: ['worsen', 'aggravate'], commonMistakes: 'Do not confuse with "exasperate" (to annoy)' },
  { id: 'v50', word: 'mitigate', partOfSpeech: 'verb', level: 'C1', meaning: 'to make something less harmful or serious', example: 'Governments must mitigate the effects of climate change.', translation: 'Giảm thiểu', pronunciation: '/ˈmɪt.ɪ.ɡeɪt/', tags: ['academic', 'ielts'], collocations: ['mitigate risk', 'mitigate the impact'], synonyms: ['alleviate', 'reduce'] },
  { id: 'v51', word: 'proliferation', partOfSpeech: 'noun', level: 'C1', meaning: 'rapid increase in number or amount', example: 'The proliferation of fake news is concerning.', translation: 'Sự gia tăng nhanh', pronunciation: '/prəˌlɪf.ərˈeɪ.ʃən/', tags: ['academic', 'ielts'], collocations: ['nuclear proliferation', 'proliferation of technology'] },
  { id: 'v52', word: 'pragmatic', partOfSpeech: 'adjective', level: 'C1', meaning: 'dealing with problems in a practical and sensible way', example: 'We need a pragmatic approach to education reform.', translation: 'Thực dụng, thực tế', pronunciation: '/præɡˈmæt.ɪk/', tags: ['academic', 'personality'], synonyms: ['practical', 'realistic'] },
  { id: 'v53', word: 'deteriorate', partOfSpeech: 'verb', level: 'C1', meaning: 'to become worse', example: 'Air quality continues to deteriorate in urban areas.', translation: 'Xấu đi, xuống cấp', pronunciation: '/dɪˈtɪə.ri.ə.reɪt/', tags: ['academic', 'ielts'], collocations: ['deteriorate rapidly', 'health deteriorates'], synonyms: ['decline', 'worsen'] },
  { id: 'v54', word: 'comprehensive', partOfSpeech: 'adjective', level: 'C1', meaning: 'including everything that is necessary; thorough', example: 'The report provides a comprehensive analysis of the problem.', translation: 'Toàn diện', pronunciation: '/ˌkɒm.prɪˈhen.sɪv/', tags: ['academic', 'ielts'], collocations: ['comprehensive plan', 'comprehensive review'], synonyms: ['thorough', 'complete'] },

  // ═══ C2 — Mastery ═══
  { id: 'v55', word: 'ephemeral', partOfSpeech: 'adjective', level: 'C2', meaning: 'lasting for a very short time', example: 'Social media fame is often ephemeral.', translation: 'Phù du, chóng tàn', pronunciation: '/ɪˈfem.ər.əl/', tags: ['abstract', 'ielts', 'advanced'], synonyms: ['fleeting', 'transient', 'short-lived'] },
  { id: 'v56', word: 'anachronistic', partOfSpeech: 'adjective', level: 'C2', meaning: 'belonging to a different period of time', example: 'Some educational practices are anachronistic.', translation: 'Lỗi thời, không hợp thời', pronunciation: '/əˌnæk.rəˈnɪs.tɪk/', tags: ['culture', 'advanced'] },
  { id: 'v57', word: 'perfunctory', partOfSpeech: 'adjective', level: 'C2', meaning: 'done without care or interest, just as a formality', example: 'He gave a perfunctory nod and left.', translation: 'Qua loa, chiếu lệ', pronunciation: '/pəˈfʌŋk.tər.i/', tags: ['advanced'], synonyms: ['cursory', 'superficial'] },
  { id: 'v58', word: 'sycophant', partOfSpeech: 'noun', level: 'C2', meaning: 'a person who praises powerful people to gain advantage', example: 'He surrounds himself with sycophants.', translation: 'Kẻ nịnh hót', pronunciation: '/ˈsɪk.ə.fænt/', tags: ['people', 'advanced'], synonyms: ['flatterer', 'yes-man'] },
  { id: 'v59', word: 'quintessential', partOfSpeech: 'adjective', level: 'C2', meaning: 'representing the most perfect example of something', example: 'Paris is the quintessential romantic city.', translation: 'Tinh túy, điển hình nhất', pronunciation: '/ˌkwɪn.tɪˈsen.ʃəl/', tags: ['description', 'advanced'], synonyms: ['archetypal', 'definitive'] },
  { id: 'v60', word: 'vicissitudes', partOfSpeech: 'noun', level: 'C2', meaning: 'changes of fortune or circumstances', example: 'The vicissitudes of life teach us resilience.', translation: 'Những thăng trầm', pronunciation: '/vɪˈsɪs.ɪ.tjuːdz/', tags: ['abstract', 'advanced'] },

  // ═══ IELTS Topic: Education ═══
  { id: 'v61', word: 'curriculum', partOfSpeech: 'noun', level: 'B2', meaning: 'the subjects studied in a school or course', example: 'The school has updated its curriculum.', translation: 'Chương trình giảng dạy', pronunciation: '/kəˈrɪk.jə.ləm/', tags: ['education', 'ielts'], collocations: ['national curriculum', 'curriculum vitae'] },
  { id: 'v62', word: 'discipline', partOfSpeech: 'noun', level: 'B1', meaning: 'the ability to control behaviour; or a field of study', example: 'Self-discipline is key to success.', translation: 'Kỷ luật / Ngành học', pronunciation: '/ˈdɪs.ə.plɪn/', tags: ['education', 'ielts'], collocations: ['self-discipline', 'academic discipline'] },
  { id: 'v63', word: 'literacy', partOfSpeech: 'noun', level: 'B2', meaning: 'the ability to read and write', example: 'Digital literacy is essential in today\'s world.', translation: 'Biết đọc biết viết', pronunciation: '/ˈlɪt.ər.ə.si/', tags: ['education', 'ielts'], collocations: ['literacy rate', 'digital literacy', 'financial literacy'] },

  // ═══ IELTS Topic: Health ═══
  { id: 'v64', word: 'obesity', partOfSpeech: 'noun', level: 'B2', meaning: 'the condition of being extremely overweight', example: 'Childhood obesity is a growing concern.', translation: 'Béo phì', pronunciation: '/əʊˈbiː.sə.ti/', tags: ['health', 'ielts'], collocations: ['obesity epidemic', 'combat obesity'] },
  { id: 'v65', word: 'sedentary', partOfSpeech: 'adjective', level: 'C1', meaning: 'involving a lot of sitting and not much physical activity', example: 'A sedentary lifestyle increases health risks.', translation: 'Ít vận động', pronunciation: '/ˈsed.ən.tər.i/', tags: ['health', 'ielts'], collocations: ['sedentary lifestyle', 'sedentary job'] },
  { id: 'v66', word: 'well-being', partOfSpeech: 'noun', level: 'B2', meaning: 'the state of being comfortable, healthy, and happy', example: 'We should prioritize mental well-being.', translation: 'Sức khỏe, hạnh phúc', pronunciation: '/ˌwel ˈbiː.ɪŋ/', tags: ['health', 'ielts'], collocations: ['mental well-being', 'physical well-being'] },

  // ═══ IELTS Topic: Urbanisation ═══
  { id: 'v67', word: 'urbanisation', partOfSpeech: 'noun', level: 'B2', meaning: 'the process of making an area more urban', example: 'Rapid urbanisation causes housing shortages.', translation: 'Đô thị hóa', pronunciation: '/ˌɜː.bən.aɪˈzeɪ.ʃən/', tags: ['society', 'ielts'], collocations: ['rapid urbanisation', 'urbanisation rate'] },
  { id: 'v68', word: 'infrastructure', partOfSpeech: 'noun', level: 'B2', meaning: 'the basic systems and services of a country', example: 'The city needs to invest in its infrastructure.', translation: 'Cơ sở hạ tầng', pronunciation: '/ˈɪn.frə.strʌk.tʃər/', tags: ['society', 'ielts'], collocations: ['transport infrastructure', 'digital infrastructure'] },
  { id: 'v69', word: 'congestion', partOfSpeech: 'noun', level: 'B2', meaning: 'a situation where roads are too crowded to move freely', example: 'Traffic congestion is worst during rush hour.', translation: 'Tắc nghẽn', pronunciation: '/kənˈdʒes.tʃən/', tags: ['transport', 'ielts'], collocations: ['traffic congestion', 'congestion charge'] },

  // ═══ IELTS Topic: Technology ═══
  { id: 'v70', word: 'automation', partOfSpeech: 'noun', level: 'B2', meaning: 'the use of machines to do work instead of people', example: 'Automation is transforming the manufacturing industry.', translation: 'Tự động hóa', pronunciation: '/ˌɔː.təˈmeɪ.ʃən/', tags: ['technology', 'ielts'], collocations: ['industrial automation', 'office automation'] },
  { id: 'v71', word: 'artificial intelligence', partOfSpeech: 'noun', level: 'B2', meaning: 'computer systems able to perform tasks that normally require human intelligence', example: 'Artificial intelligence is used in language learning apps.', translation: 'Trí tuệ nhân tạo', pronunciation: '/ˌɑː.tɪ.fɪʃ.əl ɪnˈtel.ɪ.dʒəns/', tags: ['technology', 'ielts'], collocations: ['AI technology', 'artificial intelligence research'] },
  { id: 'v72', word: 'surveillance', partOfSpeech: 'noun', level: 'C1', meaning: 'close observation, especially of a suspected person', example: 'CCTV surveillance has increased in cities.', translation: 'Giám sát', pronunciation: '/sɜːˈveɪ.ləns/', tags: ['technology', 'ielts', 'society'], collocations: ['under surveillance', 'surveillance camera'] },

  // ═══ Academic & Linking Words ═══
  { id: 'v73', word: 'nevertheless', partOfSpeech: 'adverb', level: 'B2', meaning: 'in spite of that; however', example: 'The plan has risks. Nevertheless, we should proceed.', translation: 'Tuy nhiên', pronunciation: '/ˌnev.ə.ðəˈles/', tags: ['academic', 'ielts', 'linking'], synonyms: ['however', 'nonetheless'] },
  { id: 'v74', word: 'furthermore', partOfSpeech: 'adverb', level: 'B2', meaning: 'in addition; besides', example: 'The product is affordable. Furthermore, it is eco-friendly.', translation: 'Hơn nữa', pronunciation: '/ˌfɜː.ðəˈmɔːr/', tags: ['academic', 'ielts', 'linking'], synonyms: ['moreover', 'additionally'] },
  { id: 'v75', word: 'whereas', partOfSpeech: 'conjunction', level: 'B2', meaning: 'in contrast or comparison with the fact that', example: 'Some prefer online learning, whereas others prefer classrooms.', translation: 'Trong khi', pronunciation: '/weərˈæz/', tags: ['academic', 'ielts', 'linking'] },

  // ═══ Phrasal Verbs ═══
  { id: 'v76', word: 'bring up', partOfSpeech: 'phrase', level: 'B1', meaning: 'to raise a child; or to mention a topic', example: 'She was brought up in a small village.', translation: 'Nuôi dạy / Đề cập', pronunciation: '/brɪŋ ʌp/', tags: ['phrasal verb', 'ielts'], commonMistakes: 'Two meanings: raising children AND mentioning topics' },
  { id: 'v77', word: 'carry out', partOfSpeech: 'phrase', level: 'B1', meaning: 'to complete a task or activity', example: 'Scientists carried out extensive research.', translation: 'Thực hiện', pronunciation: '/ˈkær.i aʊt/', tags: ['phrasal verb', 'academic', 'ielts'], synonyms: ['conduct', 'perform'] },
  { id: 'v78', word: 'come across', partOfSpeech: 'phrase', level: 'B1', meaning: 'to find something by chance; to seem', example: 'I came across an interesting article today.', translation: 'Tình cờ gặp', pronunciation: '/kʌm əˈkrɒs/', tags: ['phrasal verb'], synonyms: ['encounter', 'stumble upon'] },
  { id: 'v79', word: 'give up', partOfSpeech: 'phrase', level: 'A2', meaning: 'to stop doing something; to quit', example: 'Don\'t give up on your dreams.', translation: 'Từ bỏ', pronunciation: '/ɡɪv ʌp/', tags: ['phrasal verb', 'motivation'], synonyms: ['quit', 'abandon'] },
  { id: 'v80', word: 'look forward to', partOfSpeech: 'phrase', level: 'B1', meaning: 'to feel excited about something that is going to happen', example: 'I look forward to hearing from you.', translation: 'Mong chờ', pronunciation: '/lʊk ˈfɔː.wəd tuː/', tags: ['phrasal verb', 'communication'], commonMistakes: 'Always followed by noun/gerund: "look forward to meeting" not "look forward to meet"' },

  // ═══ Idioms ═══
  { id: 'v81', word: 'break the ice', partOfSpeech: 'phrase', level: 'B1', meaning: 'to make people feel more comfortable in a social situation', example: 'A joke can help break the ice at a meeting.', translation: 'Phá vỡ sự ngại ngùng', pronunciation: '/breɪk ðə aɪs/', tags: ['idiom', 'social'] },
  { id: 'v82', word: 'a piece of cake', partOfSpeech: 'phrase', level: 'B1', meaning: 'something that is very easy to do', example: 'The exam was a piece of cake.', translation: 'Dễ như ăn bánh', pronunciation: '/ə piːs əv keɪk/', tags: ['idiom'] },
  { id: 'v83', word: 'hit the books', partOfSpeech: 'phrase', level: 'B1', meaning: 'to study hard', example: 'I need to hit the books for my IELTS exam.', translation: 'Học bài chăm chỉ', pronunciation: '/hɪt ðə bʊks/', tags: ['idiom', 'education'] },
  { id: 'v84', word: 'once in a blue moon', partOfSpeech: 'phrase', level: 'B2', meaning: 'very rarely', example: 'I only eat fast food once in a blue moon.', translation: 'Rất hiếm khi', pronunciation: '/wʌns ɪn ə bluː muːn/', tags: ['idiom', 'time'] },

  // ═══ Collocations ═══
  { id: 'v85', word: 'make a decision', partOfSpeech: 'phrase', level: 'B1', meaning: 'to decide', example: 'You need to make a decision quickly.', translation: 'Đưa ra quyết định', pronunciation: '/meɪk ə dɪˈsɪʒ.ən/', tags: ['collocation'], commonMistakes: '"Make a decision" not "do a decision"' },
  { id: 'v86', word: 'take into account', partOfSpeech: 'phrase', level: 'B2', meaning: 'to consider something when making a judgment', example: 'We should take into account all the factors.', translation: 'Xem xét, cân nhắc', pronunciation: '/teɪk ɪn.tuː əˈkaʊnt/', tags: ['collocation', 'academic', 'ielts'], synonyms: ['consider', 'bear in mind'] },

  // ═══ More B1/B2 for density ═══
  { id: 'v87', word: 'essential', partOfSpeech: 'adjective', level: 'B1', meaning: 'absolutely necessary; extremely important', example: 'Clean water is essential for good health.', translation: 'Thiết yếu', pronunciation: '/ɪˈsen.ʃəl/', tags: ['academic', 'ielts'], synonyms: ['vital', 'crucial', 'fundamental'], collocations: ['essential for', 'essential skills'] },
  { id: 'v88', word: 'diverse', partOfSpeech: 'adjective', level: 'B2', meaning: 'including many different types of people or things', example: 'London is one of the most diverse cities in the world.', translation: 'Đa dạng', pronunciation: '/daɪˈvɜːs/', tags: ['society', 'ielts'], collocations: ['culturally diverse', 'diverse range'], synonyms: ['varied', 'multifaceted'] },
  { id: 'v89', word: 'inevitable', partOfSpeech: 'adjective', level: 'B2', meaning: 'certain to happen and unable to be prevented', example: 'Change is inevitable in any society.', translation: 'Không thể tránh khỏi', pronunciation: '/ɪnˈev.ɪ.tə.bəl/', tags: ['academic', 'ielts'], synonyms: ['unavoidable', 'inescapable'] },
  { id: 'v90', word: 'phenomenon', partOfSpeech: 'noun', level: 'B2', meaning: 'something that exists and can be observed', example: 'Global warming is a well-documented phenomenon.', translation: 'Hiện tượng', pronunciation: '/fɪˈnɒm.ɪ.nən/', tags: ['academic', 'ielts'], commonMistakes: 'Plural is "phenomena" not "phenomenons"' },
  { id: 'v91', word: 'demonstrate', partOfSpeech: 'verb', level: 'B2', meaning: 'to show something clearly; to prove', example: 'The study demonstrates a clear link between exercise and health.', translation: 'Chứng minh, thể hiện', pronunciation: '/ˈdem.ən.streɪt/', tags: ['academic', 'ielts'], collocations: ['demonstrate clearly', 'demonstrate the ability'], synonyms: ['show', 'prove', 'illustrate'] },
  { id: 'v92', word: 'regarding', partOfSpeech: 'preposition', level: 'B2', meaning: 'about; concerning', example: 'I have a question regarding the assignment.', translation: 'Về, liên quan đến', pronunciation: '/rɪˈɡɑː.dɪŋ/', tags: ['academic', 'formal', 'ielts'], synonyms: ['concerning', 'about', 'with respect to'] },
  { id: 'v93', word: 'beneficial', partOfSpeech: 'adjective', level: 'B2', meaning: 'producing good results; helpful', example: 'Regular exercise is beneficial for mental health.', translation: 'Có lợi', pronunciation: '/ˌben.ɪˈfɪʃ.əl/', tags: ['health', 'ielts'], collocations: ['mutually beneficial', 'beneficial effects'], synonyms: ['advantageous', 'helpful'] },
  { id: 'v94', word: 'adequate', partOfSpeech: 'adjective', level: 'B2', meaning: 'enough in quantity or quality', example: 'The school has adequate resources for all students.', translation: 'Đầy đủ', pronunciation: '/ˈæd.ɪ.kwət/', tags: ['academic', 'ielts'], synonyms: ['sufficient', 'enough'], commonMistakes: '"Adequate" implies just enough — not as positive as "excellent"' },
  { id: 'v95', word: 'innovative', partOfSpeech: 'adjective', level: 'B2', meaning: 'introducing new ideas or methods', example: 'The company is known for its innovative products.', translation: 'Sáng tạo, đổi mới', pronunciation: '/ˈɪn.ə.veɪ.tɪv/', tags: ['technology', 'ielts'], synonyms: ['creative', 'groundbreaking'], collocations: ['innovative approach', 'innovative technology'] },
  { id: 'v96', word: 'allocate', partOfSpeech: 'verb', level: 'C1', meaning: 'to give something officially for a particular purpose', example: 'The government allocated funds for education.', translation: 'Phân bổ', pronunciation: '/ˈæl.ə.keɪt/', tags: ['academic', 'ielts'], collocations: ['allocate resources', 'allocate budget'], synonyms: ['assign', 'distribute'] },
  { id: 'v97', word: 'indigenous', partOfSpeech: 'adjective', level: 'C1', meaning: 'originating in a particular place; native', example: 'We must protect indigenous cultures.', translation: 'Bản địa', pronunciation: '/ɪnˈdɪdʒ.ɪ.nəs/', tags: ['culture', 'ielts'], synonyms: ['native', 'aboriginal'] },
  { id: 'v98', word: 'obsolete', partOfSpeech: 'adjective', level: 'C1', meaning: 'no longer produced or used; out of date', example: 'Many traditional skills are becoming obsolete.', translation: 'Lỗi thời', pronunciation: '/ˈɒb.sə.liːt/', tags: ['technology', 'ielts'], synonyms: ['outdated', 'antiquated'] },
  { id: 'v99', word: 'resilience', partOfSpeech: 'noun', level: 'C1', meaning: 'the ability to recover quickly from difficulties', example: 'Children show remarkable resilience.', translation: 'Khả năng phục hồi', pronunciation: '/rɪˈzɪl.i.əns/', tags: ['psychology', 'ielts'], collocations: ['show resilience', 'build resilience'], synonyms: ['toughness', 'adaptability'] },
  { id: 'v100', word: 'scrutinize', partOfSpeech: 'verb', level: 'C1', meaning: 'to examine something very carefully', example: 'The committee will scrutinize the proposal.', translation: 'Xem xét kỹ lưỡng', pronunciation: '/ˈskruː.tɪ.naɪz/', tags: ['academic', 'ielts'], synonyms: ['examine', 'inspect', 'analyze'] },
];
