export interface WritingPrompt {
  id: string;
  topic: string;
  level: 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'IELTS Task 1 Academic' | 'IELTS Task 1 General' | 'IELTS Task 2';
  prompt: string;
  instructions?: string;
  minWords: number;
  sampleOutline?: string[];
  evaluationCriteria?: string[];
  tags: string[];
}

export const writingPrompts: WritingPrompt[] = [
  { id: 'w1', topic: 'My Daily Routine', level: 'A1', prompt: 'Write about your daily routine. What time do you wake up? What do you do in the morning, afternoon, and evening?', minWords: 50, evaluationCriteria: ['Use present simple correctly', 'Include time expressions', 'Use basic vocabulary'], tags: ['basics', 'daily life'] },
  { id: 'w2', topic: 'My Best Friend', level: 'A1', prompt: 'Write about your best friend. What is their name? What do they look like? Why are they your best friend?', minWords: 50, tags: ['people', 'basics'] },
  { id: 'w3', topic: 'My Favourite Food', level: 'A2', prompt: 'Write about your favourite food. What is it? How is it made? When do you usually eat it? Why do you like it?', minWords: 80, tags: ['food'] },
  { id: 'w4', topic: 'A Holiday I Enjoyed', level: 'A2', prompt: 'Write about a holiday or trip you enjoyed. Where did you go? What did you do? Who did you go with?', minWords: 80, tags: ['travel'] },
  { id: 'w5', topic: 'The Importance of Exercise', level: 'B1', prompt: 'Write an essay about why exercise is important for health. Include at least two benefits and give examples from your own experience.', minWords: 120, sampleOutline: ['Introduction: Exercise is important because...', 'Body 1: Physical benefits', 'Body 2: Mental benefits', 'Conclusion: Summary and personal opinion'], tags: ['health'] },
  { id: 'w6', topic: 'Advantages of Learning Languages', level: 'B1', prompt: 'Write about the advantages of learning foreign languages. Give at least three reasons with examples.', minWords: 150, tags: ['education', 'language'] },
  { id: 'w7', topic: 'Technology in Education', level: 'IELTS Task 2', prompt: 'Some people believe that technology has a negative impact on education. Others think it improves the learning experience. Discuss both views and give your own opinion.', instructions: 'Write at least 250 words. Include an introduction, two body paragraphs, and a conclusion. Use linking words and provide specific examples.', minWords: 250, sampleOutline: ['Introduction: paraphrase the question + thesis', 'Body 1: Arguments that technology harms education', 'Body 2: Arguments that technology benefits education', 'Conclusion: your opinion + summary'], evaluationCriteria: ['Task Achievement: address both views + give opinion', 'Coherence: use linking words (however, furthermore, on the other hand)', 'Lexical Resource: topic-specific vocabulary', 'Grammatical Range: use complex sentences'], tags: ['technology', 'education', 'ielts'] },
  { id: 'w8', topic: 'Urbanisation', level: 'IELTS Task 2', prompt: 'In many countries, people are moving from rural areas to cities. What are the causes of this trend? What problems can it lead to?', instructions: 'Write at least 250 words.', minWords: 250, sampleOutline: ['Introduction: paraphrase + outline', 'Body 1: Causes (jobs, education, facilities)', 'Body 2: Problems (overcrowding, pollution, housing)', 'Conclusion: summary'], tags: ['urbanisation', 'ielts'] },
  { id: 'w9', topic: 'Environment Protection', level: 'IELTS Task 2', prompt: 'The best way to solve environmental problems is to increase the price of fuel. Do you agree or disagree?', instructions: 'Write at least 250 words. Give reasons for your answer and include relevant examples.', minWords: 250, tags: ['environment', 'ielts'] },
  { id: 'w10', topic: 'Formal Letter: Complaint', level: 'IELTS Task 1 General', prompt: 'You recently bought a product online that arrived damaged. Write a letter to the company. In your letter: describe the product you purchased, explain the problem, and say what action you would like the company to take.', instructions: 'Write at least 150 words. Use formal language.', minWords: 150, tags: ['formal', 'ielts'] },
  { id: 'w11', topic: 'Graph Description: Population Growth', level: 'IELTS Task 1 Academic', prompt: 'The graph below shows the population growth of three cities (City A, City B, City C) from 1990 to 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.', instructions: 'Write at least 150 words. Start with an overview. Use data language: increased, decreased, fluctuated, remained stable.', minWords: 150, sampleOutline: ['Introduction: paraphrase what the graph shows', 'Overview: main trends', 'Body 1: Details about City A and B', 'Body 2: Details about City C and comparison'], tags: ['academic', 'ielts'] },
  { id: 'w12', topic: 'Opinion: Work-Life Balance', level: 'B2', prompt: 'Write an opinion essay: Is it more important to have a high salary or a good work-life balance? Give reasons and examples.', minWords: 200, tags: ['work', 'opinion'] },
  { id: 'w13', topic: 'Problem and Solution: Stress', level: 'B2', prompt: 'Many young people today suffer from stress. What are the main causes of stress among young people? What solutions can you suggest?', minWords: 200, tags: ['health', 'society'] },
  { id: 'w14', topic: 'Email to a Friend', level: 'A2', prompt: 'Write an email to a friend inviting them to your birthday party. Include the date, time, location, and what you will do.', minWords: 60, tags: ['communication', 'social'] },
  { id: 'w15', topic: 'Advantages and Disadvantages of Social Media', level: 'B2', prompt: 'Write about the advantages and disadvantages of social media. Do the advantages outweigh the disadvantages?', minWords: 200, tags: ['technology', 'society'] },
  { id: 'w16', topic: 'Crime and Punishment', level: 'IELTS Task 2', prompt: 'Some people believe that the best way to reduce crime is to give longer prison sentences. Others think there are better ways to reduce crime. Discuss both views and give your opinion.', instructions: 'Write at least 250 words.', minWords: 250, tags: ['society', 'ielts'] },
  { id: 'w17', topic: 'Health and Diet', level: 'IELTS Task 2', prompt: 'In some countries, the average weight of people is increasing and their levels of health and fitness are decreasing. What do you think are the causes of these problems and what measures could be taken to solve them?', instructions: 'Write at least 250 words.', minWords: 250, tags: ['health', 'ielts'] },
  { id: 'w18', topic: 'Describe Your Hometown', level: 'B1', prompt: 'Write a description of your hometown. What is it famous for? What do you like and dislike about it?', minWords: 120, tags: ['places'] },
  { id: 'w19', topic: 'Formal Letter: Job Application', level: 'B2', prompt: 'Write a formal letter applying for a job as an English teacher at an international school. Include your qualifications, experience, and why you are suitable for the role.', minWords: 180, tags: ['work', 'formal'] },
  { id: 'w20', topic: 'Global Tourism', level: 'IELTS Task 2', prompt: 'International tourism has brought enormous benefits to many places. At the same time, there is concern about its impact on local inhabitants and the environment. Do the disadvantages of international tourism outweigh the advantages?', instructions: 'Write at least 250 words.', minWords: 250, tags: ['tourism', 'ielts'] },
];
