
-- Auto-generated Seed Data for realworld_lessons

INSERT INTO public.realworld_lessons (id, language_id, unit, "order", data)
VALUES ('en-survival-1', 'en', 1, 1, '{"id":"en-survival-1","language":"en","unit":1,"order":1,"titleVi":"Chào và giới thiệu","titleEn":"Say hello and introduce yourself","canDoVi":"Tôi có thể nói tên của mình khi gặp người mới.","scenario":{"settingVi":"Bạn gặp một người mới ở lớp.","roles":["Người học","Bạn cùng lớp"]},"dialogue":[{"speaker":"A","text":"Hello, I’m Lan.","vi":"Chào, tôi là Lan."},{"speaker":"B","text":"Nice to meet you, Lan.","vi":"Rất vui được gặp bạn, Lan."}],"chunks":[{"text":"Hello, I’m ...","vi":"Chào, tôi là ...","useWhenVi":"khi tự giới thiệu","vietnameseLearnerCueVi":"Nói tên bạn sau I’m."},{"text":"Nice to meet you.","vi":"Rất vui được gặp bạn.","useWhenVi":"khi mới gặp ai","vietnameseLearnerCueVi":"Dùng sau lời chào."},{"text":"What’s your name?","vi":"Bạn tên là gì?","useWhenVi":"khi hỏi tên","vietnameseLearnerCueVi":"Mở đầu bằng What’s."}],"contextCue":{"titleVi":"Bắt đầu câu chuyện","bodyVi":"Tự tin nói xin chào."},"comprehension":{"promptVi":"Đâu là cách nói Xin chào?","options":["Hello, I’m Lan.","The platform is two."],"correctAnswer":"Hello, I’m Lan.","explanationVi":"Hello là cách chào cơ bản."},"production":{"promptVi":"Bạn hãy tự giới thiệu bản thân.","requiredSlots":["tên của bạn"],"exemplar":"Hello, I’m Mai. Nice to meet you.","rejectExactModelCopy":true},"retrieval":{"promptVi":"Hãy gõ lại câu dùng để tự giới thiệu.","cueVi":"Hello, I''m ...","acceptedPatterns":[{"requiredFragments":["hello","i''m"],"rejectedNames":["lan","mai"]},{"requiredFragments":["hello","i am"]}],"answerHintVi":"Gợi ý: bắt đầu bằng \"Hello, I''m ...\""},"selfReview":["Phát âm rõ ràng","Dùng đúng tên"]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET data = EXCLUDED.data, unit = EXCLUDED.unit, "order" = EXCLUDED.order;

INSERT INTO public.realworld_lessons (id, language_id, unit, "order", data)
VALUES ('fr-survival-1', 'fr', 1, 1, '{"id":"fr-survival-1","language":"fr","unit":1,"order":1,"titleVi":"Chào và giới thiệu","titleEn":"Say hello and introduce yourself","canDoVi":"Tôi có thể nói tên của mình khi gặp người mới.","scenario":{"settingVi":"Bạn gặp một người mới ở lớp.","roles":["Người học","Bạn cùng lớp"]},"dialogue":[{"speaker":"A","text":"Bonjour, je m’appelle Lan.","vi":"Chào, tôi là Lan."},{"speaker":"B","text":"Enchanté, Lan.","vi":"Rất vui được gặp bạn, Lan."}],"chunks":[{"text":"Bonjour, je m’appelle ...","vi":"Chào, tôi là ...","useWhenVi":"khi tự giới thiệu","vietnameseLearnerCueVi":"Nói tên bạn."},{"text":"Enchanté.","vi":"Rất vui được gặp bạn.","useWhenVi":"khi mới gặp ai","vietnameseLearnerCueVi":"Dùng sau lời chào."},{"text":"Comment tu t’appelles ?","vi":"Bạn tên là gì?","useWhenVi":"khi hỏi tên","vietnameseLearnerCueVi":"Mở đầu bằng Comment."}],"contextCue":{"titleVi":"Bắt đầu câu chuyện","bodyVi":"Tự tin nói xin chào."},"comprehension":{"promptVi":"Đâu là cách nói Xin chào?","options":["Bonjour, je m’appelle Lan.","Je suis une pomme."],"correctAnswer":"Bonjour, je m’appelle Lan.","explanationVi":"Bonjour là xin chào."},"production":{"promptVi":"Bạn hãy tự giới thiệu bản thân.","requiredSlots":["tên của bạn"],"exemplar":"Bonjour, je m’appelle Mai. Enchanté.","rejectExactModelCopy":true},"retrieval":{"promptVi":"Hãy gõ lại câu dùng để tự giới thiệu.","cueVi":"Bonjour, je m''appelle ...","acceptedPatterns":[{"requiredFragments":["bonjour","m''appelle"],"rejectedNames":["lan","mai"]}],"answerHintVi":"Gợi ý: bắt đầu bằng \"Bonjour, je m''appelle ...\""},"selfReview":["Phát âm rõ ràng","Dùng đúng tên"]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET data = EXCLUDED.data, unit = EXCLUDED.unit, "order" = EXCLUDED.order;

INSERT INTO public.realworld_lessons (id, language_id, unit, "order", data)
VALUES ('de-survival-1', 'de', 1, 1, '{"id":"de-survival-1","language":"de","unit":1,"order":1,"titleVi":"Chào và giới thiệu","titleEn":"Say hello and introduce yourself","canDoVi":"Tôi có thể nói tên của mình khi gặp người mới.","scenario":{"settingVi":"Bạn gặp một người mới ở lớp.","roles":["Người học","Bạn cùng lớp"]},"dialogue":[{"speaker":"A","text":"Hallo, ich bin Lan.","vi":"Chào, tôi là Lan."},{"speaker":"B","text":"Freut mich, Lan.","vi":"Rất vui được gặp bạn, Lan."}],"chunks":[{"text":"Hallo, ich bin ...","vi":"Chào, tôi là ...","useWhenVi":"khi tự giới thiệu","vietnameseLearnerCueVi":"Nói tên bạn."},{"text":"Freut mich.","vi":"Rất vui được gặp bạn.","useWhenVi":"khi mới gặp ai","vietnameseLearnerCueVi":"Dùng sau lời chào."},{"text":"Wie heißt du?","vi":"Bạn tên là gì?","useWhenVi":"khi hỏi tên","vietnameseLearnerCueVi":"Mở đầu bằng Wie."}],"contextCue":{"titleVi":"Bắt đầu câu chuyện","bodyVi":"Tự tin nói xin chào."},"comprehension":{"promptVi":"Đâu là cách nói Xin chào?","options":["Hallo, ich bin Lan.","Ich bin ein Auto."],"correctAnswer":"Hallo, ich bin Lan.","explanationVi":"Hallo là xin chào."},"production":{"promptVi":"Bạn hãy tự giới thiệu bản thân.","requiredSlots":["tên của bạn"],"exemplar":"Hallo, ich bin Mai. Freut mich.","rejectExactModelCopy":true},"retrieval":{"promptVi":"Hãy gõ lại câu dùng để tự giới thiệu.","cueVi":"Hallo, ich bin ...","acceptedPatterns":[{"requiredFragments":["hallo","ich bin"],"rejectedNames":["lan","mai"]}],"answerHintVi":"Gợi ý: bắt đầu bằng \"Hallo, ich bin ...\""},"selfReview":["Phát âm rõ ràng","Dùng đúng tên"]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET data = EXCLUDED.data, unit = EXCLUDED.unit, "order" = EXCLUDED.order;

INSERT INTO public.realworld_lessons (id, language_id, unit, "order", data)
VALUES ('zh-survival-1', 'zh', 1, 1, '{"id":"zh-survival-1","language":"zh","unit":1,"order":1,"titleVi":"Chào và giới thiệu","titleEn":"Say hello and introduce yourself","canDoVi":"Tôi có thể nói tên của mình khi gặp người mới.","scenario":{"settingVi":"Bạn gặp một người mới ở lớp.","roles":["Người học","Bạn cùng lớp"]},"dialogue":[{"speaker":"A","text":"你好，我叫Lan。","vi":"Chào, tôi là Lan."},{"speaker":"B","text":"很高兴认识你，Lan。","vi":"Rất vui được gặp bạn, Lan."}],"chunks":[{"text":"你好，我叫...","vi":"Chào, tôi là...","useWhenVi":"khi tự giới thiệu","vietnameseLearnerCueVi":"Nói tên bạn."},{"text":"很高兴认识你。","vi":"Rất vui được gặp bạn.","useWhenVi":"khi mới gặp ai","vietnameseLearnerCueVi":"Dùng sau lời chào."},{"text":"你叫什么名字？","vi":"Bạn tên là gì?","useWhenVi":"khi hỏi tên","vietnameseLearnerCueVi":"Hỏi tên."}],"contextCue":{"titleVi":"Bắt đầu câu chuyện","bodyVi":"Tự tin nói xin chào."},"comprehension":{"promptVi":"Đâu là cách nói Xin chào?","options":["你好，我叫Lan。","我是一只猫。"],"correctAnswer":"你好，我叫Lan。","explanationVi":"你好 là xin chào."},"production":{"promptVi":"Bạn hãy tự giới thiệu bản thân.","requiredSlots":["tên của bạn"],"exemplar":"你好，我叫Mai。很高兴认识你。","rejectExactModelCopy":true},"retrieval":{"promptVi":"Hãy gõ lại câu dùng để tự giới thiệu.","cueVi":"你好，我叫...","acceptedPatterns":[{"requiredFragments":["你好","我叫"],"rejectedNames":["lan","mai"]}],"answerHintVi":"Gợi ý: bắt đầu bằng \"你好，我叫...\""},"selfReview":["Phát âm rõ ràng","Dùng đúng tên"]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET data = EXCLUDED.data, unit = EXCLUDED.unit, "order" = EXCLUDED.order;

INSERT INTO public.realworld_lessons (id, language_id, unit, "order", data)
VALUES ('ja-survival-1', 'ja', 1, 1, '{"id":"ja-survival-1","language":"ja","unit":1,"order":1,"titleVi":"Chào và giới thiệu","titleEn":"Say hello and introduce yourself","canDoVi":"Tôi có thể nói tên của mình khi gặp người mới.","scenario":{"settingVi":"Bạn gặp một người mới ở lớp.","roles":["Người học","Bạn cùng lớp"]},"dialogue":[{"speaker":"A","text":"こんにちは、私はランです。","vi":"Chào, tôi là Lan."},{"speaker":"B","text":"はじめまして、ランさん。","vi":"Rất vui được gặp bạn, Lan."}],"chunks":[{"text":"こんにちは、私は...です。","vi":"Chào, tôi là...","useWhenVi":"khi tự giới thiệu","vietnameseLearnerCueVi":"Nói tên bạn."},{"text":"はじめまして。","vi":"Rất vui được gặp bạn.","useWhenVi":"khi mới gặp ai","vietnameseLearnerCueVi":"Dùng sau lời chào."},{"text":"お名前は何ですか？","vi":"Bạn tên là gì?","useWhenVi":"khi hỏi tên","vietnameseLearnerCueVi":"Hỏi tên."}],"contextCue":{"titleVi":"Bắt đầu câu chuyện","bodyVi":"Tự tin nói xin chào."},"comprehension":{"promptVi":"Đâu là cách nói Xin chào?","options":["こんにちは、私はランです。","私は車です。"],"correctAnswer":"こんにちは、私はランです。","explanationVi":"こんにちは là xin chào."},"production":{"promptVi":"Bạn hãy tự giới thiệu bản thân.","requiredSlots":["tên của bạn"],"exemplar":"こんにちは、私はマイです。はじめまして。","rejectExactModelCopy":true},"retrieval":{"promptVi":"Hãy gõ lại câu dùng để tự giới thiệu.","cueVi":"こんにちは、私は...です。","acceptedPatterns":[{"requiredFragments":["こんにちは","私","です"],"rejectedNames":["ラン","マイ"]}],"answerHintVi":"Gợi ý: bắt đầu bằng \"こんにちは、私は...\""},"selfReview":["Phát âm rõ ràng","Dùng đúng tên"]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET data = EXCLUDED.data, unit = EXCLUDED.unit, "order" = EXCLUDED.order;

INSERT INTO public.realworld_lessons (id, language_id, unit, "order", data)
VALUES ('ko-survival-1', 'ko', 1, 1, '{"id":"ko-survival-1","language":"ko","unit":1,"order":1,"titleVi":"Chào và giới thiệu","titleEn":"Say hello and introduce yourself","canDoVi":"Tôi có thể nói tên của mình khi gặp người mới.","scenario":{"settingVi":"Bạn gặp một người mới ở lớp.","roles":["Người học","Bạn cùng lớp"]},"dialogue":[{"speaker":"A","text":"안녕하세요, 저는 란입니다.","vi":"Chào, tôi là Lan."},{"speaker":"B","text":"만나서 반갑습니다, 란씨.","vi":"Rất vui được gặp bạn, Lan."}],"chunks":[{"text":"안녕하세요, 저는 ...입니다.","vi":"Chào, tôi là...","useWhenVi":"khi tự giới thiệu","vietnameseLearnerCueVi":"Nói tên bạn."},{"text":"만나서 반갑습니다.","vi":"Rất vui được gặp bạn.","useWhenVi":"khi mới gặp ai","vietnameseLearnerCueVi":"Dùng sau lời chào."},{"text":"이름이 무엇입니까?","vi":"Bạn tên là gì?","useWhenVi":"khi hỏi tên","vietnameseLearnerCueVi":"Hỏi tên."}],"contextCue":{"titleVi":"Bắt đầu câu chuyện","bodyVi":"Tự tin nói xin chào."},"comprehension":{"promptVi":"Đâu là cách nói Xin chào?","options":["안녕하세요, 저는 란입니다.","저는 사과입니다."],"correctAnswer":"안녕하세요, 저는 란입니다.","explanationVi":"안녕하세요 là xin chào."},"production":{"promptVi":"Bạn hãy tự giới thiệu bản thân.","requiredSlots":["tên của bạn"],"exemplar":"안녕하세요, 저는 마이입니다. 만나서 반갑습니다.","rejectExactModelCopy":true},"retrieval":{"promptVi":"Hãy gõ lại câu dùng để tự giới thiệu.","cueVi":"안녕하세요, 저는 ...입니다.","acceptedPatterns":[{"requiredFragments":["안녕하세요","저는","입니다"],"rejectedNames":["란","마이"]}],"answerHintVi":"Gợi ý: bắt đầu bằng \"안녕하세요...\""},"selfReview":["Phát âm rõ ràng","Dùng đúng tên"]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET data = EXCLUDED.data, unit = EXCLUDED.unit, "order" = EXCLUDED.order;

INSERT INTO public.realworld_lessons (id, language_id, unit, "order", data)
VALUES ('es-survival-1', 'es', 1, 1, '{"id":"es-survival-1","language":"es","unit":1,"order":1,"titleVi":"Chào và giới thiệu","titleEn":"Say hello and introduce yourself","canDoVi":"Tôi có thể nói tên của mình khi gặp người mới.","scenario":{"settingVi":"Bạn gặp một người mới ở lớp.","roles":["Người học","Bạn cùng lớp"]},"dialogue":[{"speaker":"A","text":"Hola, soy Lan.","vi":"Chào, tôi là Lan."},{"speaker":"B","text":"Encantado, Lan.","vi":"Rất vui được gặp bạn, Lan."}],"chunks":[{"text":"Hola, soy ...","vi":"Chào, tôi là ...","useWhenVi":"khi tự giới thiệu","vietnameseLearnerCueVi":"Nói tên bạn."},{"text":"Encantado.","vi":"Rất vui được gặp bạn.","useWhenVi":"khi mới gặp ai","vietnameseLearnerCueVi":"Dùng sau lời chào."},{"text":"¿Cómo te llamas?","vi":"Bạn tên là gì?","useWhenVi":"khi hỏi tên","vietnameseLearnerCueVi":"Hỏi tên."}],"contextCue":{"titleVi":"Bắt đầu câu chuyện","bodyVi":"Tự tin nói xin chào."},"comprehension":{"promptVi":"Đâu là cách nói Xin chào?","options":["Hola, soy Lan.","El coche es rojo."],"correctAnswer":"Hola, soy Lan.","explanationVi":"Hola là xin chào."},"production":{"promptVi":"Bạn hãy tự giới thiệu bản thân.","requiredSlots":["tên của bạn"],"exemplar":"Hola, soy Mai. Encantada.","rejectExactModelCopy":true},"retrieval":{"promptVi":"Hãy gõ lại câu dùng để tự giới thiệu.","cueVi":"Hola, soy ...","acceptedPatterns":[{"requiredFragments":["hola","soy"],"rejectedNames":["lan","mai"]}],"answerHintVi":"Gợi ý: bắt đầu bằng \"Hola, soy ...\""},"selfReview":["Phát âm rõ ràng","Dùng đúng tên"]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET data = EXCLUDED.data, unit = EXCLUDED.unit, "order" = EXCLUDED.order;

INSERT INTO public.realworld_lessons (id, language_id, unit, "order", data)
VALUES ('it-survival-1', 'it', 1, 1, '{"id":"it-survival-1","language":"it","unit":1,"order":1,"titleVi":"Chào và giới thiệu","titleEn":"Say hello and introduce yourself","canDoVi":"Tôi có thể nói tên của mình khi gặp người mới.","scenario":{"settingVi":"Bạn gặp một người mới ở lớp.","roles":["Người học","Bạn cùng lớp"]},"dialogue":[{"speaker":"A","text":"Ciao, sono Lan.","vi":"Chào, tôi là Lan."},{"speaker":"B","text":"Piacere, Lan.","vi":"Rất vui được gặp bạn, Lan."}],"chunks":[{"text":"Ciao, sono ...","vi":"Chào, tôi là ...","useWhenVi":"khi tự giới thiệu","vietnameseLearnerCueVi":"Nói tên bạn."},{"text":"Piacere.","vi":"Rất vui được gặp bạn.","useWhenVi":"khi mới gặp ai","vietnameseLearnerCueVi":"Dùng sau lời chào."},{"text":"Come ti chiami?","vi":"Bạn tên là gì?","useWhenVi":"khi hỏi tên","vietnameseLearnerCueVi":"Hỏi tên."}],"contextCue":{"titleVi":"Bắt đầu câu chuyện","bodyVi":"Tự tin nói xin chào."},"comprehension":{"promptVi":"Đâu là cách nói Xin chào?","options":["Ciao, sono Lan.","La pizza è buona."],"correctAnswer":"Ciao, sono Lan.","explanationVi":"Ciao là xin chào."},"production":{"promptVi":"Bạn hãy tự giới thiệu bản thân.","requiredSlots":["tên của bạn"],"exemplar":"Ciao, sono Mai. Piacere.","rejectExactModelCopy":true},"retrieval":{"promptVi":"Hãy gõ lại câu dùng để tự giới thiệu.","cueVi":"Ciao, sono ...","acceptedPatterns":[{"requiredFragments":["ciao","sono"],"rejectedNames":["lan","mai"]}],"answerHintVi":"Gợi ý: bắt đầu bằng \"Ciao, sono ...\""},"selfReview":["Phát âm rõ ràng","Dùng đúng tên"]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET data = EXCLUDED.data, unit = EXCLUDED.unit, "order" = EXCLUDED.order;

INSERT INTO public.realworld_lessons (id, language_id, unit, "order", data)
VALUES ('pt-survival-1', 'pt', 1, 1, '{"id":"pt-survival-1","language":"pt","unit":1,"order":1,"titleVi":"Chào và giới thiệu","titleEn":"Say hello and introduce yourself","canDoVi":"Tôi có thể nói tên của mình khi gặp người mới.","scenario":{"settingVi":"Bạn gặp một người mới ở lớp.","roles":["Người học","Bạn cùng lớp"]},"dialogue":[{"speaker":"A","text":"Olá, eu sou Lan.","vi":"Chào, tôi là Lan."},{"speaker":"B","text":"Prazer, Lan.","vi":"Rất vui được gặp bạn, Lan."}],"chunks":[{"text":"Olá, eu sou ...","vi":"Chào, tôi là ...","useWhenVi":"khi tự giới thiệu","vietnameseLearnerCueVi":"Nói tên bạn."},{"text":"Prazer.","vi":"Rất vui được gặp bạn.","useWhenVi":"khi mới gặp ai","vietnameseLearnerCueVi":"Dùng sau lời chào."},{"text":"Como você se chama?","vi":"Bạn tên là gì?","useWhenVi":"khi hỏi tên","vietnameseLearnerCueVi":"Hỏi tên."}],"contextCue":{"titleVi":"Bắt đầu câu chuyện","bodyVi":"Tự tin nói xin chào."},"comprehension":{"promptVi":"Đâu là cách nói Xin chào?","options":["Olá, eu sou Lan.","A casa é grande."],"correctAnswer":"Olá, eu sou Lan.","explanationVi":"Olá là xin chào."},"production":{"promptVi":"Bạn hãy tự giới thiệu bản thân.","requiredSlots":["tên của bạn"],"exemplar":"Olá, eu sou Mai. Prazer.","rejectExactModelCopy":true},"retrieval":{"promptVi":"Hãy gõ lại câu dùng để tự giới thiệu.","cueVi":"Olá, eu sou ...","acceptedPatterns":[{"requiredFragments":["olá","sou"],"rejectedNames":["lan","mai"]}],"answerHintVi":"Gợi ý: bắt đầu bằng \"Olá, eu sou ...\""},"selfReview":["Phát âm rõ ràng","Dùng đúng tên"]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET data = EXCLUDED.data, unit = EXCLUDED.unit, "order" = EXCLUDED.order;

INSERT INTO public.realworld_lessons (id, language_id, unit, "order", data)
VALUES ('ru-survival-1', 'ru', 1, 1, '{"id":"ru-survival-1","language":"ru","unit":1,"order":1,"titleVi":"Chào và giới thiệu","titleEn":"Say hello and introduce yourself","canDoVi":"Tôi có thể nói tên của mình khi gặp người mới.","scenario":{"settingVi":"Bạn gặp một người mới ở lớp.","roles":["Người học","Bạn cùng lớp"]},"dialogue":[{"speaker":"A","text":"Здравствуйте, я Лан.","vi":"Chào, tôi là Lan."},{"speaker":"B","text":"Очень приятно, Лан.","vi":"Rất vui được gặp bạn, Lan."}],"chunks":[{"text":"Здравствуйте, я ...","vi":"Chào, tôi là ...","useWhenVi":"khi tự giới thiệu","vietnameseLearnerCueVi":"Nói tên bạn."},{"text":"Очень приятно.","vi":"Rất vui được gặp bạn.","useWhenVi":"khi mới gặp ai","vietnameseLearnerCueVi":"Dùng sau lời chào."},{"text":"Как вас зовут?","vi":"Bạn tên là gì?","useWhenVi":"khi hỏi tên","vietnameseLearnerCueVi":"Hỏi tên."}],"contextCue":{"titleVi":"Bắt đầu câu chuyện","bodyVi":"Tự tin nói xin chào."},"comprehension":{"promptVi":"Đâu là cách nói Xin chào?","options":["Здравствуйте, я Лан.","Это стол."],"correctAnswer":"Здравствуйте, я Лан.","explanationVi":"Здравствуйте là xin chào."},"production":{"promptVi":"Bạn hãy tự giới thiệu bản thân.","requiredSlots":["tên của bạn"],"exemplar":"Здравствуйте, я Май. Очень приятно.","rejectExactModelCopy":true},"retrieval":{"promptVi":"Hãy gõ lại câu dùng để tự giới thiệu.","cueVi":"Здравствуйте, я ...","acceptedPatterns":[{"requiredFragments":["здравствуйте","я"],"rejectedNames":["лан","май"]}],"answerHintVi":"Gợi ý: bắt đầu bằng \"Здравствуйте, я ...\""},"selfReview":["Phát âm rõ ràng","Dùng đúng tên"]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET data = EXCLUDED.data, unit = EXCLUDED.unit, "order" = EXCLUDED.order;

INSERT INTO public.realworld_lessons (id, language_id, unit, "order", data)
VALUES ('vi-survival-1', 'vi', 1, 1, '{"id":"vi-survival-1","language":"vi","unit":1,"order":1,"titleVi":"Chào và giới thiệu","titleEn":"Say hello and introduce yourself","canDoVi":"Tôi có thể nói tên của mình khi gặp người mới.","scenario":{"settingVi":"Bạn gặp một người mới ở lớp.","roles":["Người học","Bạn cùng lớp"]},"dialogue":[{"speaker":"A","text":"Xin chào, tôi là Lan.","vi":"Chào, tôi là Lan."},{"speaker":"B","text":"Rất vui được gặp bạn, Lan.","vi":"Rất vui được gặp bạn, Lan."}],"chunks":[{"text":"Xin chào, tôi là ...","vi":"Chào, tôi là ...","useWhenVi":"khi tự giới thiệu","vietnameseLearnerCueVi":"Nói tên bạn."},{"text":"Rất vui được gặp bạn.","vi":"Rất vui được gặp bạn.","useWhenVi":"khi mới gặp ai","vietnameseLearnerCueVi":"Dùng sau lời chào."},{"text":"Bạn tên là gì?","vi":"Bạn tên là gì?","useWhenVi":"khi hỏi tên","vietnameseLearnerCueVi":"Hỏi tên."}],"contextCue":{"titleVi":"Bắt đầu câu chuyện","bodyVi":"Tự tin nói xin chào."},"comprehension":{"promptVi":"Đâu là cách nói Xin chào?","options":["Xin chào, tôi là Lan.","Trời hôm nay đẹp."],"correctAnswer":"Xin chào, tôi là Lan.","explanationVi":"Xin chào là câu chào cơ bản."},"production":{"promptVi":"Bạn hãy tự giới thiệu bản thân.","requiredSlots":["tên của bạn"],"exemplar":"Xin chào, tôi là Mai. Rất vui được gặp bạn.","rejectExactModelCopy":true},"retrieval":{"promptVi":"Hãy gõ lại câu dùng để tự giới thiệu.","cueVi":"Xin chào, tôi là ...","acceptedPatterns":[{"requiredFragments":["xin chào","tôi là"],"rejectedNames":["lan","mai"]}],"answerHintVi":"Gợi ý: bắt đầu bằng \"Xin chào, tôi là ...\""},"selfReview":["Phát âm rõ ràng","Dùng đúng tên"]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET data = EXCLUDED.data, unit = EXCLUDED.unit, "order" = EXCLUDED.order;

INSERT INTO public.realworld_lessons (id, language_id, unit, "order", data)
VALUES ('th-survival-1', 'th', 1, 1, '{"id":"th-survival-1","language":"th","unit":1,"order":1,"titleVi":"Chào và giới thiệu","titleEn":"Say hello and introduce yourself","canDoVi":"Tôi có thể nói tên của mình khi gặp người mới.","scenario":{"settingVi":"Bạn gặp một người mới ở lớp.","roles":["Người học","Bạn cùng lớp"]},"dialogue":[{"speaker":"A","text":"สวัสดี ฉันชื่อหลาน","vi":"Chào, tôi là Lan."},{"speaker":"B","text":"ยินดีที่ได้รู้จัก หลาน","vi":"Rất vui được gặp bạn, Lan."}],"chunks":[{"text":"สวัสดี ฉันชื่อ ...","vi":"Chào, tôi là ...","useWhenVi":"khi tự giới thiệu","vietnameseLearnerCueVi":"Nói tên bạn."},{"text":"ยินดีที่ได้รู้จัก","vi":"Rất vui được gặp bạn.","useWhenVi":"khi mới gặp ai","vietnameseLearnerCueVi":"Dùng sau lời chào."},{"text":"คุณชื่ออะไร?","vi":"Bạn tên là gì?","useWhenVi":"khi hỏi tên","vietnameseLearnerCueVi":"Hỏi tên."}],"contextCue":{"titleVi":"Bắt đầu câu chuyện","bodyVi":"Tự tin nói xin chào."},"comprehension":{"promptVi":"Đâu là cách nói Xin chào?","options":["สวัสดี ฉันชื่อหลาน","ฉันหิวข้าว"],"correctAnswer":"สวัสดี ฉันชื่อหลาน","explanationVi":"สวัสดี là xin chào."},"production":{"promptVi":"Bạn hãy tự giới thiệu bản thân.","requiredSlots":["tên của bạn"],"exemplar":"สวัสดี ฉันชื่อไม ยินดีที่ได้รู้จัก","rejectExactModelCopy":true},"retrieval":{"promptVi":"Hãy gõ lại câu dùng để tự giới thiệu.","cueVi":"สวัสดี ฉันชื่อ ...","acceptedPatterns":[{"requiredFragments":["สวัสดี","ฉันชื่อ"],"rejectedNames":["หลาน","ไม"]}],"answerHintVi":"Gợi ý: bắt đầu bằng \"สวัสดี ฉันชื่อ ...\""},"selfReview":["Phát âm rõ ràng","Dùng đúng tên"]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET data = EXCLUDED.data, unit = EXCLUDED.unit, "order" = EXCLUDED.order;

INSERT INTO public.realworld_lessons (id, language_id, unit, "order", data)
VALUES ('ar-survival-1', 'ar', 1, 1, '{"id":"ar-survival-1","language":"ar","unit":1,"order":1,"titleVi":"Chào và giới thiệu","titleEn":"Say hello and introduce yourself","canDoVi":"Tôi có thể nói tên của mình khi gặp người mới.","scenario":{"settingVi":"Bạn gặp một người mới ở lớp.","roles":["Người học","Bạn cùng lớp"]},"dialogue":[{"speaker":"A","text":"مرحباً، أنا لان.","vi":"Chào, tôi là Lan."},{"speaker":"B","text":"تشرفنا، لان.","vi":"Rất vui được gặp bạn, Lan."}],"chunks":[{"text":"مرحباً، أنا ...","vi":"Chào, tôi là ...","useWhenVi":"khi tự giới thiệu","vietnameseLearnerCueVi":"Nói tên bạn."},{"text":"تشرفنا.","vi":"Rất vui được gặp bạn.","useWhenVi":"khi mới gặp ai","vietnameseLearnerCueVi":"Dùng sau lời chào."},{"text":"ما اسمك؟","vi":"Bạn tên là gì?","useWhenVi":"khi hỏi tên","vietnameseLearnerCueVi":"Hỏi tên."}],"contextCue":{"titleVi":"Bắt đầu câu chuyện","bodyVi":"Tự tin nói xin chào."},"comprehension":{"promptVi":"Đâu là cách nói Xin chào?","options":["مرحباً، أنا لان.","أنا أحب التفاح."],"correctAnswer":"مرحباً، أنا لان.","explanationVi":"مرحباً là xin chào."},"production":{"promptVi":"Bạn hãy tự giới thiệu bản thân.","requiredSlots":["tên của bạn"],"exemplar":"مرحباً، أنا ماي. تشرفنا.","rejectExactModelCopy":true},"retrieval":{"promptVi":"Hãy gõ lại câu dùng để tự giới thiệu.","cueVi":"مرحباً، أنا ...","acceptedPatterns":[{"requiredFragments":["مرحباً","أنا"],"rejectedNames":["لان","ماي"]}],"answerHintVi":"Gợi ý: bắt đầu bằng \"مرحباً، أنا ...\""},"selfReview":["Phát âm rõ ràng","Dùng đúng tên"]}'::jsonb)
ON CONFLICT (id) DO UPDATE SET data = EXCLUDED.data, unit = EXCLUDED.unit, "order" = EXCLUDED.order;
