import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { describe, it } from 'node:test';

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8');

describe('AI Coach Hub shell', () => {
  it('registers the generic /app/ai route and page export', () => {
    const app = read('../../src/App.tsx');
    const pages = read('../../src/pages/index.ts');
    const page = read('../../src/pages/app/AICoachHubPage.tsx');

    assert.match(app, /AICoachHubPage/);
    assert.match(app, /<Route path="ai" element={<AICoachHubPage \/>} \/>/);
    assert.match(pages, /AICoachHubPage.*\.\/app\/AICoachHubPage/);
    assert.match(page, /<AICoachHubShell\s*\/>/);
  });

  it('links to all five registered feature routes', () => {
    const shell = read('../../src/components/ai/AICoachHubShell.tsx');

    for (const route of [
      '/app/ai-tutor',
      '/app/practice-generator',
      '/app/learner-memory',
      '/app/ai-writing',
      '/app/ai-speaking',
    ]) {
      assert.match(shell, new RegExp(`to=\\{feature\\.route\\}`));
      assert.ok(shell.includes('viewModel.features.map'));
      assert.ok(route.startsWith('/app/'));
    }
  });

  it('adds one small Practice Hub entry point', () => {
    const practiceHub = read('../../src/pages/app/PracticeHubPage.tsx');

    assert.match(practiceHub, /to="\/app\/ai"/);
    assert.match(practiceHub, /AI Coach Hub/);
  });

  it('renders registry metadata only and never invokes AI services', () => {
    const sources = [
      read('../../src/platform/ai/aiFeatureRegistry.ts'),
      read('../../src/platform/ai/aiFeatureRegistryViewModel.ts'),
      read('../../src/components/ai/AICoachHubShell.tsx'),
      read('../../src/pages/app/AICoachHubPage.tsx'),
    ].join('\n');

    assert.doesNotMatch(sources, /AIService|\.execute\(|Math\.random|Date\.now|setTimeout/);
    assert.doesNotMatch(sources, /fake typing|streaming delay|generated insight|personalized recommendation/i);
    assert.doesNotMatch(sources, /IELTS|TOEIC|TOEFL|band score|Speaking Part|Writing Task/i);
    assert.doesNotMatch(
      sources,
      /unlimited AI|ChatGPT-like|official IELTS score|guaranteed band|stronger than ELSA/i,
    );
  });

  it('keeps model and learner-memory status copy explicit', () => {
    const shell = read('../../src/components/ai/AICoachHubShell.tsx');
    const viewModel = read('../../src/platform/ai/aiFeatureRegistryViewModel.ts');

    assert.match(shell, /feature\.availabilityLabel/);
    assert.match(shell, /feature\.learnerMemoryLabel/);
    assert.match(viewModel, /Local model required/);
    assert.match(viewModel, /Consent-gated learner memory/);
    assert.match(viewModel, /No AI output is generated by this hub/);
  });
});
