import {
  AI_FEATURE_REGISTRY,
  type AIFeatureDefinition,
  type AIFeatureId,
  type AIFeatureStatus,
} from './aiFeatureRegistry.ts';

export interface AICoachHubFeatureViewModel {
  id: AIFeatureId;
  label: string;
  description: string;
  route: `/app/${string}`;
  category: AIFeatureDefinition['category'];
  status: AIFeatureStatus;
  safetyNote: string;
  availabilityLabel: string;
  availabilityDescription: string;
  learnerMemoryLabel: string;
}

export interface AICoachHubViewModel {
  eyebrow: string;
  heading: string;
  description: string;
  foundationHeading: string;
  foundationDescription: string;
  noOutputNotice: string;
  features: AICoachHubFeatureViewModel[];
}

function availabilityCopy(feature: AIFeatureDefinition): Pick<
  AICoachHubFeatureViewModel,
  'availabilityLabel' | 'availabilityDescription'
> {
  if (feature.requiresLocalModel) {
    return {
      availabilityLabel: 'Local model required',
      availabilityDescription:
        'The shell is available, but output requires an approved local model and a ready runtime.',
    };
  }

  return {
    availabilityLabel: 'Available without a model',
    availabilityDescription: 'This local control does not require a generation model.',
  };
}

function learnerMemoryLabel(feature: AIFeatureDefinition): string {
  if (feature.supportsLearnerMemory) return 'Consent-gated learner memory';
  if (feature.id === 'learner-memory') return 'Local consent controls';
  return 'No learner memory context';
}

export function buildAICoachHubViewModel(
  registry: readonly AIFeatureDefinition[] = AI_FEATURE_REGISTRY,
): AICoachHubViewModel {
  return {
    eyebrow: 'Platform AI tools',
    heading: 'AI Coach Hub',
    description: 'Open the current learning shells and local learner-memory controls from one place.',
    foundationHeading: 'Local AI foundation status',
    foundationDescription:
      'This hub does not verify a model or runtime. Open a coach shell to see its current unavailable-safe state.',
    noOutputNotice: 'No AI output is generated by this hub.',
    features: registry.map((feature) => ({
      id: feature.id,
      label: feature.label,
      description: feature.description,
      route: feature.route,
      category: feature.category,
      status: feature.status,
      safetyNote: feature.safetyNote,
      learnerMemoryLabel: learnerMemoryLabel(feature),
      ...availabilityCopy(feature),
    })),
  };
}
