import type {
  AICapabilityReport,
  AITier,
} from './aiCapabilityDetector.ts';
import type { ModelReadinessState } from './aiReadiness.ts';
import type {
  LocalRuntimeStatus,
} from './localRuntimeState.ts';
import type { LocalRuntimeUnavailableReason } from './localRuntimeErrors.ts';

export const AI_READINESS_COPY = {
  eyebrow: 'Platform AI readiness',
  heading: 'Local AI readiness',
  loadingHeading: 'Checking local AI capability',
  loadingDescription: 'Reading device signals without downloading or running a model.',
  errorHeading: 'AI readiness unavailable',
  errorDescription: 'The capability report could not be read. No AI output is available.',
  limitationsHeading: 'Current limitations',
  noOutputNotice: 'No AI output is generated by this panel.',
} as const;

export type AIReadinessTone = 'positive' | 'neutral' | 'warning' | 'unavailable';

export interface AIReadinessSnapshot {
  capabilityReport: AICapabilityReport;
  modelReadiness?: ModelReadinessState;
  runtimeStatus?: LocalRuntimeStatus;
  runtimeReason?: LocalRuntimeUnavailableReason;
}

export interface AIReadinessStatusItem {
  id: 'tier' | 'browser' | 'webgpu' | 'wasm' | 'device' | 'network' | 'storage' | 'model' | 'runtime';
  label: string;
  value: string;
  detail?: string;
  tone: AIReadinessTone;
}

export interface AIReadinessViewModel {
  eyebrow: string;
  heading: string;
  summary: string;
  statusLabel: string;
  tone: AIReadinessTone;
  tier: AITier;
  items: AIReadinessStatusItem[];
  limitations: string[];
  limitationsHeading: string;
  modelStatus: string;
  runtimeStatus: string;
  runtimeDetail: string;
  noOutputNotice: string;
}

const reasonLabels: Record<string, string> = {
  'browser-unsupported': 'Browser support is unavailable.',
  'webgpu-unavailable': 'WebGPU is unavailable; a fallback may be used.',
  'wasm-unavailable': 'WASM fallback is unavailable.',
  'insufficient-capability': 'Device capability is below the selected requirement.',
  'capability-unknown': 'Device capability evidence is incomplete.',
  'storage-unavailable': 'Local storage or cache storage is unavailable.',
  'model-not-installed': 'No approved model is installed.',
  'model-not-approved': 'No approved model is available.',
  'model-corrupted': 'The installed model failed integrity checks.',
  'model-update-required': 'The installed model needs an approved update.',
  'runtime-not-installed': 'The local runtime is not installed.',
  'runtime-not-implemented': 'The local runtime is not implemented yet.',
  'runtime-not-ready': 'The local runtime is not ready.',
  'runtime-disposed': 'The local runtime has been disposed.',
  'invalid-runtime-session': 'The local runtime session is invalid.',
  'invalid-state-transition': 'The local runtime reported an invalid state transition.',
  'generation-failed': 'The local runtime request failed.',
};

function labelForReason(reason: string): string {
  return reasonLabels[reason] ?? 'The platform reported an unavailable capability.';
}

function labelForTier(tier: AITier): string {
  return tier === 'unavailable'
    ? 'Unavailable'
    : tier.replace('-local', ' local').replace(/^./, character => character.toUpperCase());
}

function labelForBrowser(name: string): string {
  return name === 'unknown' ? 'Unknown browser' : name.charAt(0).toUpperCase() + name.slice(1);
}

function formatDeviceEvidence(report: AICapabilityReport): Pick<AIReadinessStatusItem, 'value' | 'detail' | 'tone'> {
  const { memoryGb, hardwareConcurrency } = report.capability.device;
  const memory = memoryGb === undefined ? undefined : `${memoryGb} GB memory`;
  const cores = hardwareConcurrency === undefined ? undefined : `${hardwareConcurrency} CPU cores`;

  if (!memory && !cores) {
    return {
      value: 'Not reported',
      detail: 'No memory or CPU evidence was supplied.',
      tone: 'neutral',
    };
  }

  return {
    value: [memory, cores].filter(Boolean).join(' · '),
    detail: memory && cores ? 'Reported device evidence.' : 'Partial device evidence; missing signals remain unknown.',
    tone: 'neutral',
  };
}

function formatModelState(
  state: ModelReadinessState | undefined,
): Pick<AIReadinessStatusItem, 'value' | 'detail' | 'tone'> {
  if (!state || state.status === 'not-installed') {
    return {
      value: 'Not installed',
      detail: 'This device may support local AI, but no approved model is installed.',
      tone: 'warning',
    };
  }

  if (state.status === 'unavailable') {
    return {
      value: 'Unavailable',
      detail: labelForReason(state.reason),
      tone: 'unavailable',
    };
  }

  return {
    value: 'Ready',
    detail: `Approved model ${state.modelId} is installed for the ${labelForTier(state.tier)} tier.`,
    tone: 'positive',
  };
}

function formatRuntimeState(
  status: LocalRuntimeStatus,
  reason?: LocalRuntimeUnavailableReason,
): { label: string; detail: string; tone: AIReadinessTone } {
  switch (status) {
    case 'ready':
      return { label: 'Ready', detail: 'The local runtime reports a ready session.', tone: 'positive' };
    case 'loading':
      return { label: 'Loading', detail: 'The local runtime is preparing a model session.', tone: 'neutral' };
    case 'generating':
      return { label: 'Generating', detail: 'The local runtime is processing a request.', tone: 'neutral' };
    case 'needs-model':
      return { label: 'Needs model', detail: 'The local runtime cannot start without an installed model.', tone: 'warning' };
    case 'failed':
      return { label: 'Failed', detail: labelForReason(reason ?? 'generation-failed'), tone: 'unavailable' };
    case 'disposed':
      return { label: 'Disposed', detail: labelForReason('runtime-disposed'), tone: 'unavailable' };
    case 'unavailable':
      return {
        label: reason === 'runtime-not-implemented' ? 'Not implemented' : 'Unavailable',
        detail: labelForReason(reason ?? 'runtime-not-ready'),
        tone: 'unavailable',
      };
    case 'idle':
    default:
      return { label: 'Idle', detail: 'The local runtime has not started.', tone: 'neutral' };
  }
}

function uniqueLimitations(values: string[]): string[] {
  return [...new Set(values)];
}

export function buildAIReadinessViewModel(snapshot: AIReadinessSnapshot): AIReadinessViewModel {
  const { capabilityReport } = snapshot;
  const runtimeStatus = snapshot.runtimeStatus ?? 'unavailable';
  const model = formatModelState(snapshot.modelReadiness);
  const runtime = formatRuntimeState(runtimeStatus, snapshot.runtimeReason);
  const modelReady = snapshot.modelReadiness?.status === 'ready';
  const runtimeReady = runtimeStatus === 'ready';
  const capabilityReady = capabilityReport.localAIAvailable;
  const fullyReady = capabilityReady && modelReady && runtimeReady;

  let summary = 'Local AI is not ready yet.';
  let statusLabel = 'Not ready';
  let tone: AIReadinessTone = 'warning';

  if (fullyReady) {
    summary = 'Local AI runtime and an approved model are ready for supported platform operations.';
    statusLabel = 'Ready for supported operations';
    tone = 'positive';
  } else if (capabilityReport.tier === 'unavailable') {
    summary = 'This device is not currently suitable for local AI. Local AI is not ready yet.';
    statusLabel = 'Unavailable';
    tone = 'unavailable';
  } else if (!modelReady) {
    summary = 'This device may support local AI, but no approved model is installed. Local AI is not ready yet.';
  } else if (!runtimeReady) {
    summary = 'The device and model may be compatible, but the local runtime is not ready yet.';
  }

  const device = formatDeviceEvidence(capabilityReport);
  const storageValue = capabilityReport.capability.storage.localStorageAvailable || capabilityReport.capability.storage.cacheStorageAvailable
    ? 'Available'
    : 'Unavailable';
  const storageDetail = [
    capabilityReport.capability.storage.localStorageAvailable ? 'local storage' : undefined,
    capabilityReport.capability.storage.cacheStorageAvailable ? 'cache storage' : undefined,
  ].filter(Boolean).join(' and ') || 'No local persistence signal is available.';
  const webgpuAdapter = capabilityReport.capability.webgpu.adapterAvailable;
  const webgpuValue = !capabilityReport.capability.webgpu.supported || webgpuAdapter === false
    ? 'Unavailable'
    : webgpuAdapter === true
      ? 'Available'
      : 'API detected';
  const webgpuTone: AIReadinessTone = webgpuAdapter === true
    ? 'positive'
    : capabilityReport.capability.webgpu.supported
      ? 'neutral'
      : 'warning';
  const webgpuDetail = !capabilityReport.capability.webgpu.supported
    ? 'WebGPU API was not detected; WASM may provide a fallback.'
    : webgpuAdapter === null
      ? 'API detected; adapter availability is not confirmed.'
      : webgpuAdapter
        ? 'Adapter detected.'
        : 'No compatible adapter was detected; WASM may provide a fallback.';

  const items: AIReadinessStatusItem[] = [
    {
      id: 'tier',
      label: 'Capability tier',
      value: labelForTier(capabilityReport.tier),
      detail: capabilityReport.localAIAvailable ? 'The detector found a compatible local capability profile.' : 'The detector did not authorize local model execution.',
      tone: capabilityReport.localAIAvailable ? 'positive' : 'warning',
    },
    {
      id: 'browser',
      label: 'Browser',
      value: capabilityReport.capability.browser.supported ? 'Supported' : 'Unsupported',
      detail: labelForBrowser(capabilityReport.capability.browser.name),
      tone: capabilityReport.capability.browser.supported ? 'positive' : 'unavailable',
    },
    {
      id: 'webgpu',
      label: 'WebGPU',
      value: webgpuValue,
      detail: webgpuDetail,
      tone: webgpuTone,
    },
    {
      id: 'wasm',
      label: 'WASM fallback',
      value: capabilityReport.capability.wasm.supported ? 'Fallback available' : 'Unavailable',
      detail: capabilityReport.capability.wasm.supported ? 'A lower-capability local path is detectable.' : 'No local fallback was detected.',
      tone: capabilityReport.capability.wasm.supported ? 'neutral' : 'unavailable',
    },
    {
      id: 'device',
      label: 'Device evidence',
      value: device.value,
      detail: device.detail,
      tone: device.tone,
    },
    {
      id: 'network',
      label: 'Connection',
      value: capabilityReport.capability.network.online ? 'Online' : 'Offline',
      detail: capabilityReport.capability.network.online ? 'Network access is currently reported.' : 'Offline mode does not install or run a model.',
      tone: capabilityReport.capability.network.online ? 'neutral' : 'warning',
    },
    {
      id: 'storage',
      label: 'Storage and cache',
      value: storageValue,
      detail: storageDetail,
      tone: storageValue === 'Available' ? 'positive' : 'unavailable',
    },
    {
      id: 'model',
      label: 'Model readiness',
      value: model.value,
      detail: model.detail,
      tone: model.tone,
    },
    {
      id: 'runtime',
      label: 'Runtime status',
      value: runtime.label,
      detail: runtime.detail,
      tone: runtime.tone,
    },
  ];

  const limitationReasons: string[] = capabilityReport.limitations.map(labelForReason);
  if (!modelReady) limitationReasons.push(labelForReason(snapshot.modelReadiness?.status === 'unavailable' ? snapshot.modelReadiness.reason : 'model-not-installed'));
  if (!runtimeReady) limitationReasons.push(labelForReason(snapshot.runtimeReason ?? 'runtime-not-implemented'));

  return {
    eyebrow: AI_READINESS_COPY.eyebrow,
    heading: AI_READINESS_COPY.heading,
    summary,
    statusLabel,
    tone,
    tier: capabilityReport.tier,
    items,
    limitations: uniqueLimitations(limitationReasons),
    limitationsHeading: AI_READINESS_COPY.limitationsHeading,
    modelStatus: model.value,
    runtimeStatus: runtime.label,
    runtimeDetail: runtime.detail,
    noOutputNotice: AI_READINESS_COPY.noOutputNotice,
  };
}
