import type {
  AIService,
  AIServiceContext,
  AIServiceResponse,
  AIServiceUnavailableReason,
} from './aiServiceTypes.ts';

interface AITutorViewModelBase {
  heading: string;
  description: string;
  isAiGenerated: false;
}

export type AITutorViewModel =
  | AITutorViewModelBase & { status: 'idle' }
  | AITutorViewModelBase & { status: 'submitting' }
  | AITutorViewModelBase & {
      status: 'unavailable';
      reason: AIServiceUnavailableReason;
    }
  | AITutorViewModelBase & {
      status: 'needs-model';
      reason: 'model-not-installed';
    }
  | AITutorViewModelBase & {
      status: 'failed';
      reason: AIServiceUnavailableReason;
    }
  | {
      status: 'success';
      heading: string;
      description: string;
      output: string;
      isAiGenerated: true;
    };

export interface AITutorRequestInput {
  prompt: string;
  sourceLanguage?: string;
  targetLanguage?: string;
  skillArea?: string;
  requestId?: string;
}

let requestSequence = 0;

function nextRequestId(): string {
  requestSequence += 1;
  return `ai-tutor-request-${requestSequence}`;
}

function optionalToken(value: string | undefined): string | undefined {
  const normalized = value?.trim();
  return normalized ? normalized : undefined;
}

function createLearningContext(input: AITutorRequestInput): AIServiceContext | undefined {
  const context: AIServiceContext = {};
  const sourceLanguage = optionalToken(input.sourceLanguage);
  const targetLanguage = optionalToken(input.targetLanguage);
  const skillArea = optionalToken(input.skillArea);

  if (sourceLanguage) context.sourceLanguage = sourceLanguage;
  if (targetLanguage) context.targetLanguage = targetLanguage;
  if (skillArea) context.skillArea = skillArea;

  return Object.keys(context).length > 0 ? context : undefined;
}

export function createIdleAITutorViewModel(): AITutorViewModel {
  return {
    status: 'idle',
    heading: 'Ask a learning question',
    description: 'Tutor output appears only when an approved local model and runtime are ready.',
    isAiGenerated: false,
  };
}

export function createSubmittingAITutorViewModel(): AITutorViewModel {
  return {
    status: 'submitting',
    heading: 'Checking Local AI Tutor availability',
    description: 'The platform is checking the current model and runtime state.',
    isAiGenerated: false,
  };
}

export function createFailedAITutorViewModel(
  reason: AIServiceUnavailableReason,
  description: string,
): AITutorViewModel {
  return {
    status: 'failed',
    heading: 'The tutor request could not be completed.',
    description,
    reason,
    isAiGenerated: false,
  };
}

export function mapAITutorResponse(response: AIServiceResponse): AITutorViewModel {
  switch (response.status) {
    case 'success':
      return {
        status: 'success',
        heading: 'Tutor response',
        description: 'Generated by an approved model and runtime with recorded provenance.',
        output: response.output.text,
        isAiGenerated: true,
      };

    case 'needs-model':
      return {
        status: 'needs-model',
        heading: 'No approved local model is installed.',
        description: 'You can continue learning without AI assistance.',
        reason: response.unavailableReason,
        isAiGenerated: false,
      };

    case 'unavailable':
      return {
        status: 'unavailable',
        heading: 'Local AI Tutor is not ready yet.',
        description: response.unavailableReason === 'runtime-not-implemented'
          ? 'The local AI runtime is not implemented. You can continue learning without AI assistance.'
          : 'No approved local model is installed. You can continue learning without AI assistance.',
        reason: response.unavailableReason,
        isAiGenerated: false,
      };

    case 'failed':
      return createFailedAITutorViewModel(
        response.error.reason,
        response.error.message,
      );
  }
}

export async function executeAITutorRequest(
  service: AIService,
  input: AITutorRequestInput,
): Promise<AITutorViewModel> {
  try {
    const response = await service.execute({
      requestId: optionalToken(input.requestId) ?? nextRequestId(),
      type: 'conversation',
      input: input.prompt,
      context: createLearningContext(input),
    });
    return mapAITutorResponse(response);
  } catch {
    return createFailedAITutorViewModel(
      'generation-failed',
      'The local tutor service could not process this request.',
    );
  }
}