import type { LocalModelArtifactCandidate } from './localModelArtifactTypes.ts';

function createArtifactCandidate(
  artifact: LocalModelArtifactCandidate,
): LocalModelArtifactCandidate {
  return artifact;
}

export const LOCAL_MODEL_ARTIFACT_MANIFEST: readonly LocalModelArtifactCandidate[] = [
  createArtifactCandidate({
    artifactId: 'qwen3-0-6b-light-artifact-candidate',
    candidateId: 'qwen3-0-6b-candidate',
    modelTier: 'light',
    displayName: 'Qwen3-0.6B light artifact candidate',
    parameterScaleLabel: '0.6B',
    quantizationLabel: 'Not selected',
    estimatedDownloadSizeMb: null,
    estimatedInstalledSizeMb: null,
    cacheBucket: 'planned-local-model-cache',
    approvalStatus: 'candidate-unapproved',
    licenseApprovalRequired: true,
    artifactApprovalRequired: true,
    benchmarkApprovalRequired: true,
    checksumRequired: true,
    checksumStatus: 'missing',
    downloadUrlStatus: 'absent',
    downloadable: false,
    cacheable: false,
    runtimeReady: false,
  }),
  createArtifactCandidate({
    artifactId: 'qwen3-1-7b-standard-artifact-candidate',
    candidateId: 'qwen3-1-7b-candidate',
    modelTier: 'standard',
    displayName: 'Qwen3-1.7B standard artifact candidate',
    parameterScaleLabel: '1.7B',
    quantizationLabel: 'Not selected',
    estimatedDownloadSizeMb: null,
    estimatedInstalledSizeMb: null,
    cacheBucket: 'planned-local-model-cache',
    approvalStatus: 'candidate-unapproved',
    licenseApprovalRequired: true,
    artifactApprovalRequired: true,
    benchmarkApprovalRequired: true,
    checksumRequired: true,
    checksumStatus: 'missing',
    downloadUrlStatus: 'absent',
    downloadable: false,
    cacheable: false,
    runtimeReady: false,
  }),
  createArtifactCandidate({
    artifactId: 'qwen3-4b-pro-artifact-candidate',
    candidateId: 'qwen3-4b-candidate',
    modelTier: 'pro',
    displayName: 'Qwen3-4B pro artifact candidate',
    parameterScaleLabel: '4B',
    quantizationLabel: 'Not selected',
    estimatedDownloadSizeMb: null,
    estimatedInstalledSizeMb: null,
    cacheBucket: 'planned-local-model-cache',
    approvalStatus: 'candidate-unapproved',
    licenseApprovalRequired: true,
    artifactApprovalRequired: true,
    benchmarkApprovalRequired: true,
    checksumRequired: true,
    checksumStatus: 'missing',
    downloadUrlStatus: 'absent',
    downloadable: false,
    cacheable: false,
    runtimeReady: false,
  }),
] as const;
