import { validateAIServiceResponse } from './aiServiceGuards.ts';
import type {
  AIService,
  AIServiceContext,
  AIServiceUnavailableReason,
} from './aiServiceTypes.ts';

interface PracticeGeneratorViewModelBase {
  heading: string;
  description: string;
  isAiGenerated: false;
}

export type PracticeGeneratorViewModel =
  | PracticeGeneratorViewModelBase & { status: 'idle' }
  | PracticeGeneratorViewModelBase & { status: 'submitting' }
  | PracticeGeneratorViewModelBase & {
      status: 'unavailable';
      reason: AIServiceUnavailableReason;
    }
  | PracticeGeneratorViewModelBase & {
      status: 'needs-model';
      reason: 'model-not-installed';
    }
  | PracticeGeneratorViewModelBase & {
      status: 'failed';
      reason: AIServiceUnavailableReason;
    }
  | {
      status: 'success';
      heading: string;
      description: string;
      output: string;
      isAiGenerated: true;
    };

export interface PracticeGeneratorRequestInput {
  language?: string;
  skillArea?: string;
  difficulty?: string;
  topic?: string;
  exerciseType?: string;
  requestId?: string;
}

let requestSequence = 0;

function nextRequestId(): string {
  requestSequence += 1;
  return `practice-generator-request-${requestSequence}`;
}

function optionalText(value: string | undefined): string | undefined {
  const normalized = value?.trim();
  return normalized ? normalized : undefined;
}

function createPracticeContext(
  input: PracticeGeneratorRequestInput,
): AIServiceContext | undefined {
  const context: AIServiceContext = {};
  const targetLanguage = optionalText(input.language);
  const skillArea = optionalText(input.skillArea);
  const difficulty = optionalText(input.difficulty);
  const topic = optionalText(input.topic);
  const exerciseType = optionalText(input.exerciseType);

  if (targetLanguage) context.targetLanguage = targetLanguage;
  if (skillArea) context.skillArea = skillArea;
  if (difficulty) context.difficulty = difficulty;
  if (topic) context.topic = topic;
  if (exerciseType) context.exerciseType = exerciseType;

  return Object.keys(context).length > 0 ? context : undefined;
}

export function createIdlePracticeGeneratorViewModel(): PracticeGeneratorViewModel {
  return {
    status: 'idle',
    heading: 'Configure a practice activity',
    description: 'Generated practice appears only when an approved local model and runtime are ready.',
    isAiGenerated: false,
  };
}

export function createSubmittingPracticeGeneratorViewModel(): PracticeGeneratorViewModel {
  return {
    status: 'submitting',
    heading: 'Checking practice generation availability',
    description: 'The platform is checking the current model and runtime state.',
    isAiGenerated: false,
  };
}

function failedViewModel(
  reason: AIServiceUnavailableReason,
  description: string,
): PracticeGeneratorViewModel {
  return {
    status: 'failed',
    heading: 'Practice generation could not be completed.',
    description,
    reason,
    isAiGenerated: false,
  };
}

export function mapPracticeGeneratorResponse(
  response: unknown,
): PracticeGeneratorViewModel {
  const validation = validateAIServiceResponse(response);
  if (!validation.valid) {
    return failedViewModel(
      'runtime-response-invalid',
      'The local AI service returned an invalid response, so no practice activity was shown.',
    );
  }

  const value = validation.value;
  switch (value.status) {
    case 'success':
      return {
        status: 'success',
        heading: 'Generated practice activity',
        description: 'Generated by an approved model and runtime with recorded provenance.',
        output: value.output.text.trim(),
        isAiGenerated: true,
      };

    case 'needs-model':
      return {
        status: 'needs-model',
        heading: 'No approved local model is installed.',
        description: 'You can continue with existing lessons and practice activities.',
        reason: value.unavailableReason,
        isAiGenerated: false,
      };

    case 'unavailable':
      return {
        status: 'unavailable',
        heading: 'Practice generation is not ready yet.',
        description: value.unavailableReason === 'runtime-not-implemented'
          ? 'The local runtime is not implemented. You can continue with existing lessons and practice activities.'
          : 'The local AI service is unavailable. You can continue with existing lessons and practice activities.',
        reason: value.unavailableReason,
        isAiGenerated: false,
      };

    case 'failed':
      return failedViewModel(value.error.reason, value.error.message);
  }
}

export async function executePracticeGeneratorRequest(
  service: AIService,
  input: PracticeGeneratorRequestInput,
): Promise<PracticeGeneratorViewModel> {
  try {
    const response = await service.execute({
      requestId: optionalText(input.requestId) ?? nextRequestId(),
      type: 'generate-practice',
      context: createPracticeContext(input),
    });
    return mapPracticeGeneratorResponse(response);
  } catch {
    return failedViewModel(
      'generation-failed',
      'The local practice generation service could not process this request.',
    );
  }
}
