import { createLearnerMemoryAIContext } from '../learning/learnerMemoryViewModel.ts';
import type { LearnerMemoryRecord } from '../learning/learnerMemoryTypes.ts';
import { validateAIServiceResponse } from './aiServiceGuards.ts';
import type {
  AIService,
  AIServiceContext,
  AIServiceUnavailableReason,
} from './aiServiceTypes.ts';

interface SpeakingCoachViewModelBase {
  heading: string;
  description: string;
  isAiGenerated: false;
}

export type SpeakingCoachViewModel =
  | SpeakingCoachViewModelBase & { status: 'idle' }
  | SpeakingCoachViewModelBase & { status: 'submitting' }
  | SpeakingCoachViewModelBase & {
      status: 'unavailable';
      reason: AIServiceUnavailableReason;
    }
  | SpeakingCoachViewModelBase & {
      status: 'needs-model';
      reason: 'model-not-installed';
    }
  | SpeakingCoachViewModelBase & {
      status: 'failed';
      reason: AIServiceUnavailableReason;
    }
  | {
      status: 'success';
      heading: string;
      description: string;
      feedback: string;
      isAiGenerated: true;
    };

export interface SpeakingCoachRequestInput {
  targetLanguage?: string;
  nativeLanguage?: string;
  speakingGoal?: string;
  difficulty?: string;
  topic?: string;
  transcript?: string;
  requestId?: string;
  learnerMemory?: LearnerMemoryRecord;
}

let requestSequence = 0;

function nextRequestId(): string {
  requestSequence += 1;
  return `speaking-coach-request-${requestSequence}`;
}

function optionalText(value: string | undefined): string | undefined {
  const normalized = value?.trim();
  return normalized || undefined;
}

function optionalContextToken(value: string | undefined): string | undefined {
  const normalized = optionalText(value);
  return normalized && /^[a-z][a-z0-9-]{1,63}$/i.test(normalized)
    ? normalized
    : undefined;
}

function createSpeakingContext(
  input: SpeakingCoachRequestInput,
): AIServiceContext {
  const context: AIServiceContext = { skillArea: 'speaking' };
  const sourceLanguage = optionalText(input.nativeLanguage);
  const targetLanguage = optionalText(input.targetLanguage);
  const speakingGoal = optionalContextToken(input.speakingGoal);
  const difficulty = optionalText(input.difficulty);
  const topic = optionalText(input.topic);

  if (sourceLanguage) context.sourceLanguage = sourceLanguage;
  if (targetLanguage) context.targetLanguage = targetLanguage;
  if (speakingGoal) context.exerciseType = speakingGoal;
  if (difficulty) context.difficulty = difficulty;
  if (topic) context.topic = topic;

  const learnerMemory = input.learnerMemory
    ? createLearnerMemoryAIContext(input.learnerMemory)
    : undefined;
  if (learnerMemory) context.learnerMemory = learnerMemory;

  return context;
}

export function createIdleSpeakingCoachViewModel(): SpeakingCoachViewModel {
  return {
    status: 'idle',
    heading: 'Request speaking feedback',
    description: 'Feedback appears only when an approved local model and runtime are ready.',
    isAiGenerated: false,
  };
}

export function createSubmittingSpeakingCoachViewModel(): SpeakingCoachViewModel {
  return {
    status: 'submitting',
    heading: 'Checking speaking feedback availability',
    description: 'The platform is checking the current model and runtime state.',
    isAiGenerated: false,
  };
}

function failedViewModel(
  reason: AIServiceUnavailableReason,
  description: string,
): SpeakingCoachViewModel {
  return {
    status: 'failed',
    heading: 'Speaking feedback could not be completed.',
    description,
    reason,
    isAiGenerated: false,
  };
}

export function mapSpeakingCoachResponse(
  response: unknown,
): SpeakingCoachViewModel {
  const validation = validateAIServiceResponse(response);
  if (!validation.valid) {
    return failedViewModel(
      'runtime-response-invalid',
      'The local AI service returned an invalid response, so no speaking feedback was shown.',
    );
  }

  const value = validation.value;
  if (value.requestType !== 'feedback' && value.requestType !== 'unknown') {
    return failedViewModel(
      'runtime-response-invalid',
      'The local AI service returned a response for a different request, so no speaking feedback was shown.',
    );
  }

  switch (value.status) {
    case 'success':
      return {
        status: 'success',
        heading: 'Speaking feedback',
        description: 'Generated by an approved model and runtime with recorded provenance.',
        feedback: value.output.text.trim(),
        isAiGenerated: true,
      };

    case 'needs-model':
      return {
        status: 'needs-model',
        heading: 'No approved local model is installed.',
        description: 'You can continue practising without generated feedback.',
        reason: value.unavailableReason,
        isAiGenerated: false,
      };

    case 'unavailable':
      return {
        status: 'unavailable',
        heading: 'Speaking feedback is not ready yet.',
        description: value.unavailableReason === 'runtime-not-implemented'
          ? 'The local AI runtime is not implemented. You can continue practising without generated feedback.'
          : 'The local AI service is unavailable. You can continue practising without generated feedback.',
        reason: value.unavailableReason,
        isAiGenerated: false,
      };

    case 'failed':
      return failedViewModel(value.error.reason, value.error.message);
  }
}

export async function executeSpeakingCoachRequest(
  service: AIService,
  input: SpeakingCoachRequestInput,
): Promise<SpeakingCoachViewModel> {
  const requestInput = optionalText(input.transcript) ?? optionalText(input.speakingGoal);
  if (!requestInput) {
    return failedViewModel(
      'invalid-request',
      'Enter a speaking goal or transcript before requesting feedback.',
    );
  }

  try {
    const response = await service.execute({
      requestId: optionalText(input.requestId) ?? nextRequestId(),
      type: 'feedback',
      input: requestInput,
      context: createSpeakingContext(input),
    });
    return mapSpeakingCoachResponse(response);
  } catch {
    return failedViewModel(
      'generation-failed',
      'The local speaking feedback service could not process this request.',
    );
  }
}
