import { createLearnerMemoryAIContext } from '../learning/learnerMemoryViewModel.ts';
import type { LearnerMemoryRecord } from '../learning/learnerMemoryTypes.ts';
import { validateAIServiceResponse } from './aiServiceGuards.ts';
import type {
  AIService,
  AIServiceContext,
  AIServiceUnavailableReason,
} from './aiServiceTypes.ts';

interface WritingCoachViewModelBase {
  heading: string;
  description: string;
  isAiGenerated: false;
}

export type WritingCoachViewModel =
  | WritingCoachViewModelBase & { status: 'idle' }
  | WritingCoachViewModelBase & { status: 'submitting' }
  | WritingCoachViewModelBase & {
      status: 'unavailable';
      reason: AIServiceUnavailableReason;
    }
  | WritingCoachViewModelBase & {
      status: 'needs-model';
      reason: 'model-not-installed';
    }
  | WritingCoachViewModelBase & {
      status: 'failed';
      reason: AIServiceUnavailableReason;
    }
  | {
      status: 'success';
      heading: string;
      description: string;
      feedback: string;
      isAiGenerated: true;
    };

export interface WritingCoachRequestInput {
  text: string;
  targetLanguage?: string;
  nativeLanguage?: string;
  writingGoal?: string;
  difficulty?: string;
  topic?: string;
  requestId?: string;
  learnerMemory?: LearnerMemoryRecord;
}

let requestSequence = 0;

function nextRequestId(): string {
  requestSequence += 1;
  return `writing-coach-request-${requestSequence}`;
}

function optionalText(value: string | undefined): string | undefined {
  const normalized = value?.trim();
  return normalized || undefined;
}

function createWritingContext(
  input: WritingCoachRequestInput,
): AIServiceContext {
  const context: AIServiceContext = { skillArea: 'writing' };
  const sourceLanguage = optionalText(input.nativeLanguage);
  const targetLanguage = optionalText(input.targetLanguage);
  const writingGoal = optionalText(input.writingGoal);
  const difficulty = optionalText(input.difficulty);
  const topic = optionalText(input.topic);

  if (sourceLanguage) context.sourceLanguage = sourceLanguage;
  if (targetLanguage) context.targetLanguage = targetLanguage;
  if (writingGoal) context.exerciseType = writingGoal;
  if (difficulty) context.difficulty = difficulty;
  if (topic) context.topic = topic;

  const learnerMemory = input.learnerMemory
    ? createLearnerMemoryAIContext(input.learnerMemory)
    : undefined;
  if (learnerMemory) context.learnerMemory = learnerMemory;

  return context;
}

export function createIdleWritingCoachViewModel(): WritingCoachViewModel {
  return {
    status: 'idle',
    heading: 'Submit writing for feedback',
    description: 'Feedback appears only when an approved local model and runtime are ready.',
    isAiGenerated: false,
  };
}

export function createSubmittingWritingCoachViewModel(): WritingCoachViewModel {
  return {
    status: 'submitting',
    heading: 'Checking writing feedback availability',
    description: 'The platform is checking the current model and runtime state.',
    isAiGenerated: false,
  };
}

function failedViewModel(
  reason: AIServiceUnavailableReason,
  description: string,
): WritingCoachViewModel {
  return {
    status: 'failed',
    heading: 'Writing feedback could not be completed.',
    description,
    reason,
    isAiGenerated: false,
  };
}

export function mapWritingCoachResponse(
  response: unknown,
): WritingCoachViewModel {
  const validation = validateAIServiceResponse(response);
  if (!validation.valid) {
    return failedViewModel(
      'runtime-response-invalid',
      'The local AI service returned an invalid response, so no writing feedback was shown.',
    );
  }

  const value = validation.value;
  if (value.requestType !== 'feedback' && value.requestType !== 'unknown') {
    return failedViewModel(
      'runtime-response-invalid',
      'The local AI service returned a response for a different request, so no writing feedback was shown.',
    );
  }

  switch (value.status) {
    case 'success':
      return {
        status: 'success',
        heading: 'Writing feedback',
        description: 'Generated by an approved model and runtime with recorded provenance.',
        feedback: value.output.text.trim(),
        isAiGenerated: true,
      };

    case 'needs-model':
      return {
        status: 'needs-model',
        heading: 'No approved local model is installed.',
        description: 'You can continue writing without generated feedback.',
        reason: value.unavailableReason,
        isAiGenerated: false,
      };

    case 'unavailable':
      return {
        status: 'unavailable',
        heading: 'Writing feedback is not ready yet.',
        description: value.unavailableReason === 'runtime-not-implemented'
          ? 'The local AI runtime is not implemented. You can continue writing without generated feedback.'
          : 'The local AI service is unavailable. You can continue writing without generated feedback.',
        reason: value.unavailableReason,
        isAiGenerated: false,
      };

    case 'failed':
      return failedViewModel(value.error.reason, value.error.message);
  }
}

export async function executeWritingCoachRequest(
  service: AIService,
  input: WritingCoachRequestInput,
): Promise<WritingCoachViewModel> {
  try {
    const response = await service.execute({
      requestId: optionalText(input.requestId) ?? nextRequestId(),
      type: 'feedback',
      input: input.text.trim(),
      context: createWritingContext(input),
    });
    return mapWritingCoachResponse(response);
  } catch {
    return failedViewModel(
      'generation-failed',
      'The local writing feedback service could not process this request.',
    );
  }
}
