const fs = require('fs');
const path = require('path');

const localesDir = path.join(process.cwd(), 'src/i18n/locales');
const base = {
  common: {
    dashboard: 'Dashboard', courses: 'Courses', lesson_player: 'Lesson', practice_hub: 'Practice', listening: 'Listening', speaking: 'Speaking', reading: 'Reading', writing: 'Writing', vocabulary: 'Vocabulary', grammar: 'Grammar', placement_test: 'Placement Test', ielts_dashboard: 'IELTS Dashboard', ielts_listening: 'IELTS Listening', ielts_reading: 'IELTS Reading', ielts_writing: 'IELTS Writing', ielts_speaking: 'IELTS Speaking', ai_speaking_coach: 'AI Speaking Coach', ai_writing_coach: 'AI Writing Coach', daily_missions: 'Daily Missions', leaderboard: 'Leaderboard', achievements: 'Achievements', community: 'Community', study_groups: 'Study Groups', chat: 'Chat', voice_rooms: 'Voice Rooms', friends: 'Friends', profile: 'Profile', settings: 'Settings', search: 'Search', notifications: 'Notifications', logout: 'Logout', save: 'Save', cancel: 'Cancel', edit: 'Edit', submit: 'Submit', start: 'Start', continue: 'Continue', back: 'Back', learn: 'Learn', skills: 'Skills', ielts: 'IELTS', ai_tools: 'AI Tools', gamification: 'Gamification', account: 'Account', all: 'All', listen: 'Listen', menu: 'Menu', supabase_live: 'Supabase Live', local_mode: 'Local Mode'
  },
  lesson: {
    generating: 'Generating lesson...', missing_data: 'This lesson is missing data.', missing_options: 'This lesson is missing answer options.', choose_another: 'Please choose another lesson.', progress: { step: 'Step {{current}} of {{total}}' }, types: { multiplechoice: 'Multiple choice', typewhatyouhear: 'Dictation', matchpairs: 'Match pairs', translate: 'Translation', listenchoose: 'Listen and choose', fillblank: 'Fill in the blank' }, instructions: { chooseCorrectMeaning: 'Choose the correct meaning', listenAndType: 'Listen carefully and type the word', selectPair: 'Select matching pairs.' }, questions: { whatIsMeaning: 'What is the meaning of "{{word}}"?', typeWhatYouHear: 'Type what you hear', grammarFocus: 'Grammar focus: {{topic}}. Which sentence is correct?' }, explanations: { correctMeaning: 'The correct meaning is {{meaning}}', example: 'Example: {{example}}', correctWordWas: 'The correct word was "{{word}}"' }, buttons: { check: 'Check', continue: 'Continue', tryAgain: 'Try again', skip: 'Skip', finish: 'Finish lesson' }, feedback: { correct: 'Correct!', incorrect: 'Not quite', correctAnswer: 'Correct answer' }, placeholders: { typeAnswer: 'Type your answer...', tapWords: 'Tap words to arrange...' }, completion: { title: 'Lesson complete!', accuracy: 'Accuracy', xpEarned: 'XP earned', coins: 'Coins', perfect: 'Perfect!', great: 'Great job!', good: 'Good work!', poor: 'Review this lesson again.' }, errors: { tts_not_supported: 'This browser does not have a voice for this language.', tts_blocked: 'The browser blocked audio. Please click again.', tts_failed: 'Audio could not be played.' }
  },
  vocabulary: { title: 'Vocabulary Trainer', description: 'Master vocabulary with real practice', flashcards: 'Flashcards', quiz: 'Quiz', fill_blank: 'Fill in blank', match: 'Match', search: 'Search words', level_filter: 'Level filter', all_levels: 'All levels', review_weak: 'Weak first', no_vocab: 'No vocabulary found', loading: 'Loading vocabulary...', flip: 'Flip', next: 'Next', next_question: 'Next question', mastery_again: 'Again', mastery_hard: 'Hard', mastery_good: 'Good', mastery_easy: 'Easy', meaning_quiz: 'Meaning quiz', score: 'Score', what_does_mean: 'What does {{word}} mean?', example: 'Example', fill_instruction: 'Fill in the blank', meaning: 'Meaning', translation: 'Translation', level: 'Level', pos: 'Part of speech', check: 'Check', correct_word_is: 'Correct! The word is {{word}}', incorrect_correct_is: 'Incorrect. The correct answer is {{word}}', match_instruction: 'Match words to meanings', matched: 'Matched', great_job: 'Great job!', play_again: 'Play again', tap_to_reveal: 'Tap to reveal' },
  settings: { title: 'Settings', description: 'Control languages, display, audio and privacy', appearance: 'Appearance', theme: 'Theme', dark: 'Dark', light: 'Light', language: 'Language', interface_language: 'Interface language', interface_language_desc: 'Language used by menus, buttons and pages', learning_language: 'Target language', learning_language_desc: 'Language you are learning', native_language: 'Native language', native_language_desc: 'Language used for meanings and explanations', audio: 'Audio', sound_effects: 'Sound effects', speech_speed: 'Speech speed', account: 'Account and learning', daily_goal: 'Daily XP goal', ielts_band: 'IELTS target band', privacy: 'Privacy', save_success: 'Settings saved', normal: 'Normal', slow: 'Slow', small: 'Small', large: 'Large', font_size: 'Font size', public_profile: 'Public profile', public_profile_desc: 'Allow others to see your profile' },
  profile: { edit_profile: 'Edit profile', display_name: 'Display name', username: 'Username', bio: 'Bio', custom_status: 'Custom status', avatar_url: 'Avatar', banner_url: 'Banner', save_changes: 'Save changes', recent_activity: 'Recent activity', badges: 'Badges', friends: 'Friends', stats: 'Stats', upload_avatar: 'Upload avatar', upload_banner: 'Upload banner', local_upload_note: 'Images are saved locally if cloud storage is not configured.' },
  practice: { writing_title: 'Writing Practice', speaking_title: 'Speaking Practice', word_count: 'Word count', start_recording: 'Start recording', stop_recording: 'Stop recording', play: 'Play', submit_evaluation: 'Submit for evaluation', feedback: 'Feedback', prompts: 'Prompts', back_to_prompts: 'Back to prompts', goal_duration: 'Goal duration', local_feedback: 'Local estimated feedback' },
  ielts: { estimated_score: 'Local estimated score — not official IELTS score', band: 'Band', part1: 'Part 1', part2: 'Part 2', part3: 'Part 3', task1: 'Task 1', task2: 'Task 2', disclaimer_bold: 'Local estimated score — not an official IELTS score.', disclaimer_text: 'This app uses simplified local heuristics and does not replace a certified examiner.' },
  social: { friends: 'Friends', chat_rooms: 'Chat rooms', voice_rooms: 'Voice rooms', search_users: 'Search users', create_room: 'Create room', room_id: 'Room ID', password: 'Password', join: 'Join', send: 'Send', no_friends: 'No friends yet', no_messages: 'No messages yet', live_notice: 'Live audio/video requires WebRTC/LiveKit setup.' },
  empty: { no_notifications: 'No notifications yet.', no_content: 'No content yet.' },
  error: { something_went_wrong: 'Something went wrong', page_load_failed: "This page couldn't be loaded properly.", try_again: 'Try again', go_dashboard: 'Go to dashboard' },
};

const patches = {
  vi: {
    common: { dashboard:'Bảng điều khiển', courses:'Khóa học', lesson_player:'Bài học', practice_hub:'Luyện tập', listening:'Nghe', speaking:'Nói', reading:'Đọc', writing:'Viết', vocabulary:'Từ vựng', grammar:'Ngữ pháp', placement_test:'Kiểm tra đầu vào', ielts_dashboard:'Bảng IELTS', ielts_listening:'IELTS Nghe', ielts_reading:'IELTS Đọc', ielts_writing:'IELTS Viết', ielts_speaking:'IELTS Nói', ai_speaking_coach:'AI luyện nói', ai_writing_coach:'AI luyện viết', daily_missions:'Nhiệm vụ ngày', leaderboard:'Xếp hạng', achievements:'Thành tựu', community:'Cộng đồng', study_groups:'Nhóm học', chat:'Trò chuyện', voice_rooms:'Phòng thoại', friends:'Bạn bè', profile:'Hồ sơ', settings:'Cài đặt', search:'Tìm kiếm', notifications:'Thông báo', logout:'Đăng xuất', save:'Lưu', cancel:'Hủy', edit:'Sửa', submit:'Gửi', start:'Bắt đầu', continue:'Tiếp tục', back:'Quay lại', learn:'Học tập', skills:'Kỹ năng', ielts:'IELTS', ai_tools:'Công cụ AI', gamification:'Trò chơi hóa', account:'Tài khoản', all:'Tất cả', listen:'Nghe', menu:'Menu', supabase_live:'Supabase Live', local_mode:'Chế độ cục bộ' },
    lesson: { generating:'Đang tạo bài học...', missing_data:'Bài học này đang thiếu dữ liệu.', missing_options:'Bài học này đang thiếu lựa chọn trả lời.', choose_another:'Hãy chọn bài khác.', progress:{step:'Bước {{current}} / {{total}}'}, types:{multiplechoice:'Trắc nghiệm', typewhatyouhear:'Nghe chép chính tả', matchpairs:'Ghép cặp', translate:'Dịch', listenchoose:'Nghe và chọn', fillblank:'Điền chỗ trống'}, instructions:{chooseCorrectMeaning:'Chọn nghĩa đúng', listenAndType:'Nghe kỹ và gõ lại từ', selectPair:'Chọn các cặp tương ứng.'}, questions:{whatIsMeaning:'Nghĩa của từ "{{word}}" là gì?', typeWhatYouHear:'Gõ lại những gì bạn nghe', grammarFocus:'Trọng tâm ngữ pháp: {{topic}}. Câu nào đúng?'}, explanations:{correctMeaning:'Nghĩa đúng là {{meaning}}', example:'Ví dụ: {{example}}', correctWordWas:'Từ đúng là "{{word}}"'}, buttons:{check:'Kiểm tra', continue:'Tiếp tục', tryAgain:'Thử lại', skip:'Bỏ qua', finish:'Hoàn thành'}, feedback:{correct:'Chính xác!', incorrect:'Chưa đúng', correctAnswer:'Đáp án đúng'}, placeholders:{typeAnswer:'Nhập câu trả lời...', tapWords:'Chạm vào từ để sắp xếp...'}, completion:{title:'Hoàn thành bài học!', accuracy:'Độ chính xác', xpEarned:'XP nhận được', coins:'Xu', perfect:'Hoàn hảo!', great:'Làm tốt lắm!', good:'Tốt!', poor:'Hãy ôn lại bài này.'}, errors:{tts_not_supported:'Trình duyệt chưa có giọng đọc cho ngôn ngữ này.', tts_blocked:'Trình duyệt đã chặn âm thanh. Hãy bấm lại.', tts_failed:'Không thể phát âm thanh.'} },
    vocabulary: { title:'Luyện từ vựng', description:'Học từ vựng bằng bài tập thật', flashcards:'Thẻ ghi nhớ', quiz:'Câu đố', fill_blank:'Điền chỗ trống', match:'Ghép từ', search:'Tìm từ', level_filter:'Lọc cấp độ', all_levels:'Tất cả cấp độ', review_weak:'Ôn từ yếu', no_vocab:'Chưa có từ vựng', loading:'Đang tải từ vựng...', flip:'Lật thẻ', next:'Tiếp', next_question:'Câu tiếp theo', mastery_again:'Học lại', mastery_hard:'Khó', mastery_good:'Tốt', mastery_easy:'Dễ', meaning_quiz:'Câu đố nghĩa', score:'Điểm', what_does_mean:'Từ {{word}} có nghĩa là gì?', example:'Ví dụ', fill_instruction:'Điền vào chỗ trống', meaning:'Nghĩa', translation:'Bản dịch', level:'Cấp độ', pos:'Từ loại', check:'Kiểm tra', correct_word_is:'Đúng rồi! Từ đó là {{word}}', incorrect_correct_is:'Sai rồi. Đáp án đúng là {{word}}', match_instruction:'Ghép từ với nghĩa', matched:'Đã ghép', great_job:'Tốt lắm!', play_again:'Chơi lại', tap_to_reveal:'Chạm để xem nghĩa' },
    settings: { title:'Cài đặt', description:'Điều chỉnh ngôn ngữ, giao diện, âm thanh và quyền riêng tư', appearance:'Giao diện', theme:'Chủ đề', dark:'Tối', light:'Sáng', language:'Ngôn ngữ', interface_language:'Ngôn ngữ giao diện', interface_language_desc:'Ngôn ngữ dùng cho menu, nút và trang', learning_language:'Ngôn ngữ đang học', learning_language_desc:'Ngôn ngữ bạn muốn học', native_language:'Ngôn ngữ mẹ đẻ', native_language_desc:'Ngôn ngữ dùng cho nghĩa và giải thích', audio:'Âm thanh', sound_effects:'Hiệu ứng âm thanh', speech_speed:'Tốc độ đọc', account:'Tài khoản và học tập', daily_goal:'Mục tiêu XP ngày', ielts_band:'Mục tiêu IELTS', privacy:'Quyền riêng tư', save_success:'Đã lưu cài đặt', normal:'Bình thường', slow:'Chậm', small:'Nhỏ', large:'Lớn', font_size:'Cỡ chữ', public_profile:'Hồ sơ công khai', public_profile_desc:'Cho phép người khác xem hồ sơ của bạn' },
    profile: { edit_profile:'Chỉnh sửa hồ sơ', display_name:'Tên hiển thị', username:'Tên người dùng', bio:'Tiểu sử', custom_status:'Trạng thái', avatar_url:'Ảnh đại diện', banner_url:'Ảnh bìa', save_changes:'Lưu thay đổi', recent_activity:'Hoạt động gần đây', badges:'Huy hiệu', friends:'Bạn bè', stats:'Thống kê', upload_avatar:'Tải ảnh đại diện', upload_banner:'Tải ảnh bìa', local_upload_note:'Ảnh sẽ lưu cục bộ nếu chưa cấu hình lưu trữ đám mây.' },
    practice: { writing_title:'Luyện viết', speaking_title:'Luyện nói', word_count:'Số từ', start_recording:'Bắt đầu ghi âm', stop_recording:'Dừng ghi âm', play:'Phát', submit_evaluation:'Gửi để đánh giá', feedback:'Phản hồi', prompts:'Đề luyện tập', back_to_prompts:'Quay lại danh sách đề', goal_duration:'Thời lượng mục tiêu', local_feedback:'Phản hồi ước tính cục bộ' },
    social: { friends:'Bạn bè', chat_rooms:'Phòng chat', voice_rooms:'Phòng thoại', search_users:'Tìm người dùng', create_room:'Tạo phòng', room_id:'ID phòng', password:'Mật khẩu', join:'Tham gia', send:'Gửi', no_friends:'Chưa có bạn bè', no_messages:'Chưa có tin nhắn', live_notice:'Gọi âm thanh/video thật cần WebRTC/LiveKit.' },
    empty: { no_notifications:'Chưa có thông báo.', no_content:'Chưa có nội dung.' },
    error: { something_went_wrong:'Đã xảy ra lỗi', page_load_failed:'Trang này chưa tải đúng.', try_again:'Thử lại', go_dashboard:'Về bảng điều khiển' }
  },
  es: { common: { dashboard:'Panel', courses:'Cursos', lesson_player:'Lección', practice_hub:'Práctica', listening:'Escucha', speaking:'Habla', reading:'Lectura', writing:'Escritura', vocabulary:'Vocabulario', grammar:'Gramática', placement_test:'Prueba inicial', ielts_dashboard:'Panel IELTS', ielts_listening:'IELTS Escucha', ielts_reading:'IELTS Lectura', ielts_writing:'IELTS Escritura', ielts_speaking:'IELTS Habla', daily_missions:'Misiones diarias', leaderboard:'Clasificación', achievements:'Logros', community:'Comunidad', study_groups:'Grupos de estudio', voice_rooms:'Salas de voz', friends:'Amigos', settings:'Configuración', save:'Guardar', cancel:'Cancelar', edit:'Editar', submit:'Enviar', start:'Empezar', continue:'Continuar', back:'Atrás', all:'Todo', listen:'Escuchar', local_mode:'Modo local' }, vocabulary:{ title:'Entrenador de vocabulario', description:'Aprende vocabulario con práctica real', flashcards:'Tarjetas', fill_blank:'Completar', match:'Emparejar', search:'Buscar palabras', all_levels:'Todos los niveles', review_weak:'Débiles primero', loading:'Cargando vocabulario...', mastery_again:'Otra vez', mastery_hard:'Difícil', mastery_good:'Bien', mastery_easy:'Fácil', meaning_quiz:'Quiz de significado', score:'Puntuación', what_does_mean:'¿Qué significa {{word}}?', example:'Ejemplo', check:'Comprobar', next_question:'Siguiente pregunta', tap_to_reveal:'Toca para revelar' }, settings:{...base.settings, title:'Configuración', language:'Idioma', interface_language:'Idioma de interfaz', learning_language:'Idioma objetivo', native_language:'Idioma nativo', save_success:'Configuración guardada'}, lesson:{...base.lesson, buttons:{...base.lesson.buttons, check:'Comprobar', continue:'Continuar', tryAgain:'Intentar de nuevo', skip:'Saltar', finish:'Terminar'}, progress:{step:'Paso {{current}} de {{total}}'}, questions:{...base.lesson.questions, whatIsMeaning:'¿Qué significa "{{word}}"?', typeWhatYouHear:'Escribe lo que escuchas'}, instructions:{...base.lesson.instructions, chooseCorrectMeaning:'Elige el significado correcto'}, feedback:{correct:'¡Correcto!', incorrect:'No del todo', correctAnswer:'Respuesta correcta'}} },
  de: { common: { dashboard:'Übersicht', courses:'Kurse', lesson_player:'Lektion', practice_hub:'Üben', listening:'Hören', speaking:'Sprechen', reading:'Lesen', writing:'Schreiben', vocabulary:'Wortschatz', grammar:'Grammatik', placement_test:'Einstufungstest', ielts_dashboard:'IELTS Übersicht', ielts_listening:'IELTS Hören', ielts_reading:'IELTS Lesen', ielts_writing:'IELTS Schreiben', ielts_speaking:'IELTS Sprechen', daily_missions:'Tägliche Aufgaben', leaderboard:'Rangliste', achievements:'Erfolge', community:'Gemeinschaft', study_groups:'Lerngruppen', voice_rooms:'Sprachräume', friends:'Freunde', settings:'Einstellungen', save:'Speichern', cancel:'Abbrechen', edit:'Bearbeiten', submit:'Senden', start:'Starten', continue:'Weiter', back:'Zurück', all:'Alle', listen:'Anhören', local_mode:'Lokaler Modus' }, vocabulary:{ title:'Wortschatztrainer', description:'Lerne Wörter mit echter Übung', flashcards:'Karteikarten', fill_blank:'Lücke füllen', match:'Zuordnen', search:'Wörter suchen', all_levels:'Alle Stufen', review_weak:'Schwache zuerst', loading:'Wortschatz wird geladen...', mastery_again:'Nochmal', mastery_hard:'Schwer', mastery_good:'Gut', mastery_easy:'Einfach', meaning_quiz:'Bedeutungsquiz', score:'Punktzahl', what_does_mean:'Was bedeutet {{word}}?', example:'Beispiel', check:'Prüfen', next_question:'Nächste Frage', tap_to_reveal:'Tippen zum Anzeigen' }, settings:{...base.settings, title:'Einstellungen', language:'Sprache', interface_language:'Oberflächensprache', learning_language:'Zielsprache', native_language:'Muttersprache', save_success:'Einstellungen gespeichert'}, lesson:{...base.lesson, buttons:{...base.lesson.buttons, check:'Prüfen', continue:'Weiter', tryAgain:'Erneut versuchen', skip:'Überspringen', finish:'Beenden'}, progress:{step:'Schritt {{current}} von {{total}}'}, questions:{...base.lesson.questions, whatIsMeaning:'Was bedeutet "{{word}}"?', typeWhatYouHear:'Tippe, was du hörst'}, instructions:{...base.lesson.instructions, chooseCorrectMeaning:'Wähle die richtige Bedeutung'}, feedback:{correct:'Richtig!', incorrect:'Nicht ganz', correctAnswer:'Richtige Antwort'}} },
};

const nonLatinLabels = {
  fr: 'Français', it: 'Italiano', pt: 'Português', ru: 'Русский', ja: '日本語', ko: '한국어', zh: '中文', th: 'ไทย', ar: 'العربية'
};

function deepMerge(a, b) {
  const out = { ...a };
  for (const [k, v] of Object.entries(b || {})) {
    if (v && typeof v === 'object' && !Array.isArray(v)) out[k] = deepMerge(out[k] || {}, v);
    else out[k] = v;
  }
  return out;
}
function readLocale(file) {
  const raw = fs.readFileSync(file, 'utf8');
  const match = raw.match(/export default\s+([\s\S]*);?\s*$/);
  if (!match) return {};
  return Function(`return (${match[1].replace(/;\s*$/, '')})`)();
}
function writeLocale(code, data) {
  fs.writeFileSync(path.join(localesDir, `${code}.ts`), `export default ${JSON.stringify(data, null, 2)};\n`);
}

for (const file of fs.readdirSync(localesDir).filter(f => f.endsWith('.ts'))) {
  const code = file.replace(/\.ts$/, '');
  const current = readLocale(path.join(localesDir, file));
  let patch = patches[code] || {};
  if (!patches[code] && code !== 'en') {
    patch = { common: { ...base.common, settings: nonLatinLabels[code] ? `${base.common.settings}` : base.common.settings }, settings: { ...base.settings, title: nonLatinLabels[code] || base.settings.title } };
  }
  writeLocale(code, deepMerge(deepMerge(base, current), patch));
}
